# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  
  teamsNotification:
    # enables the generic Microsoft Teams notification for new tasks
    enabled: true
    # technical user that sends ivy-notifications
    username: ""
    # secret of the technical user
    # [password]
    userpass: ""
