/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphDateTimeTimeZone;

import java.util.ArrayList;
import java.util.List;
/**
 * CalendaridMicrosoftGraphGetScheduleBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class CalendaridMicrosoftGraphGetScheduleBody1 {
  @JsonProperty("Schedules")
  private List<String> schedules = null;

  @JsonProperty("EndTime")
  private MicrosoftGraphDateTimeTimeZone endTime = null;

  @JsonProperty("StartTime")
  private MicrosoftGraphDateTimeTimeZone startTime = null;

  @JsonProperty("AvailabilityViewInterval")
  private Integer availabilityViewInterval = null;

  public CalendaridMicrosoftGraphGetScheduleBody1 schedules(List<String> schedules) {
    this.schedules = schedules;
    return this;
  }

  public CalendaridMicrosoftGraphGetScheduleBody1 addSchedulesItem(String schedulesItem) {
    if (this.schedules == null) {
      this.schedules = new ArrayList<>();
    }
    this.schedules.add(schedulesItem);
    return this;
  }

   /**
   * Get schedules
   * @return schedules
  **/
  public List<String> getSchedules() {
    return schedules;
  }

  public void setSchedules(List<String> schedules) {
    this.schedules = schedules;
  }

  public CalendaridMicrosoftGraphGetScheduleBody1 endTime(MicrosoftGraphDateTimeTimeZone endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  public MicrosoftGraphDateTimeTimeZone getEndTime() {
    return endTime;
  }

  public void setEndTime(MicrosoftGraphDateTimeTimeZone endTime) {
    this.endTime = endTime;
  }

  public CalendaridMicrosoftGraphGetScheduleBody1 startTime(MicrosoftGraphDateTimeTimeZone startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  public MicrosoftGraphDateTimeTimeZone getStartTime() {
    return startTime;
  }

  public void setStartTime(MicrosoftGraphDateTimeTimeZone startTime) {
    this.startTime = startTime;
  }

  public CalendaridMicrosoftGraphGetScheduleBody1 availabilityViewInterval(Integer availabilityViewInterval) {
    this.availabilityViewInterval = availabilityViewInterval;
    return this;
  }

   /**
   * Get availabilityViewInterval
   * minimum: -2147483648
   * maximum: 2147483647
   * @return availabilityViewInterval
  **/
  public Integer getAvailabilityViewInterval() {
    return availabilityViewInterval;
  }

  public void setAvailabilityViewInterval(Integer availabilityViewInterval) {
    this.availabilityViewInterval = availabilityViewInterval;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalendaridMicrosoftGraphGetScheduleBody1 calendaridMicrosoftGraphGetScheduleBody1 = (CalendaridMicrosoftGraphGetScheduleBody1) o;
    return Objects.equals(this.schedules, calendaridMicrosoftGraphGetScheduleBody1.schedules) &&
        Objects.equals(this.endTime, calendaridMicrosoftGraphGetScheduleBody1.endTime) &&
        Objects.equals(this.startTime, calendaridMicrosoftGraphGetScheduleBody1.startTime) &&
        Objects.equals(this.availabilityViewInterval, calendaridMicrosoftGraphGetScheduleBody1.availabilityViewInterval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schedules, endTime, startTime, availabilityViewInterval);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalendaridMicrosoftGraphGetScheduleBody1 {\n");
    
    sb.append("    schedules: ").append(toIndentedString(schedules)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    availabilityViewInterval: ").append(toIndentedString(availabilityViewInterval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
