/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * DriveItemidMicrosoftGraphCreateLinkBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class DriveItemidMicrosoftGraphCreateLinkBody {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("scope")
  private String scope = null;

  @JsonProperty("expirationDateTime")
  private OffsetDateTime expirationDateTime = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("retainInheritedPermissions")
  private Boolean retainInheritedPermissions = false;

  public DriveItemidMicrosoftGraphCreateLinkBody type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DriveItemidMicrosoftGraphCreateLinkBody scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public DriveItemidMicrosoftGraphCreateLinkBody expirationDateTime(OffsetDateTime expirationDateTime) {
    this.expirationDateTime = expirationDateTime;
    return this;
  }

   /**
   * Get expirationDateTime
   * @return expirationDateTime
  **/
  public OffsetDateTime getExpirationDateTime() {
    return expirationDateTime;
  }

  public void setExpirationDateTime(OffsetDateTime expirationDateTime) {
    this.expirationDateTime = expirationDateTime;
  }

  public DriveItemidMicrosoftGraphCreateLinkBody password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public DriveItemidMicrosoftGraphCreateLinkBody message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public DriveItemidMicrosoftGraphCreateLinkBody retainInheritedPermissions(Boolean retainInheritedPermissions) {
    this.retainInheritedPermissions = retainInheritedPermissions;
    return this;
  }

   /**
   * Get retainInheritedPermissions
   * @return retainInheritedPermissions
  **/
  public Boolean isRetainInheritedPermissions() {
    return retainInheritedPermissions;
  }

  public void setRetainInheritedPermissions(Boolean retainInheritedPermissions) {
    this.retainInheritedPermissions = retainInheritedPermissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DriveItemidMicrosoftGraphCreateLinkBody driveItemidMicrosoftGraphCreateLinkBody = (DriveItemidMicrosoftGraphCreateLinkBody) o;
    return Objects.equals(this.type, driveItemidMicrosoftGraphCreateLinkBody.type) &&
        Objects.equals(this.scope, driveItemidMicrosoftGraphCreateLinkBody.scope) &&
        Objects.equals(this.expirationDateTime, driveItemidMicrosoftGraphCreateLinkBody.expirationDateTime) &&
        Objects.equals(this.password, driveItemidMicrosoftGraphCreateLinkBody.password) &&
        Objects.equals(this.message, driveItemidMicrosoftGraphCreateLinkBody.message) &&
        Objects.equals(this.retainInheritedPermissions, driveItemidMicrosoftGraphCreateLinkBody.retainInheritedPermissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, scope, expirationDateTime, password, message, retainInheritedPermissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DriveItemidMicrosoftGraphCreateLinkBody {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    expirationDateTime: ").append(toIndentedString(expirationDateTime)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    retainInheritedPermissions: ").append(toIndentedString(retainInheritedPermissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
