/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphTimeSlot;

/**
 * EventidMicrosoftGraphTentativelyAcceptBody1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class EventidMicrosoftGraphTentativelyAcceptBody1 {
  @JsonProperty("Comment")
  private String comment = null;

  @JsonProperty("SendResponse")
  private Boolean sendResponse = false;

  @JsonProperty("ProposedNewTime")
  private MicrosoftGraphTimeSlot proposedNewTime = null;

  public EventidMicrosoftGraphTentativelyAcceptBody1 comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public EventidMicrosoftGraphTentativelyAcceptBody1 sendResponse(Boolean sendResponse) {
    this.sendResponse = sendResponse;
    return this;
  }

   /**
   * Get sendResponse
   * @return sendResponse
  **/
  public Boolean isSendResponse() {
    return sendResponse;
  }

  public void setSendResponse(Boolean sendResponse) {
    this.sendResponse = sendResponse;
  }

  public EventidMicrosoftGraphTentativelyAcceptBody1 proposedNewTime(MicrosoftGraphTimeSlot proposedNewTime) {
    this.proposedNewTime = proposedNewTime;
    return this;
  }

   /**
   * Get proposedNewTime
   * @return proposedNewTime
  **/
  public MicrosoftGraphTimeSlot getProposedNewTime() {
    return proposedNewTime;
  }

  public void setProposedNewTime(MicrosoftGraphTimeSlot proposedNewTime) {
    this.proposedNewTime = proposedNewTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventidMicrosoftGraphTentativelyAcceptBody1 eventidMicrosoftGraphTentativelyAcceptBody1 = (EventidMicrosoftGraphTentativelyAcceptBody1) o;
    return Objects.equals(this.comment, eventidMicrosoftGraphTentativelyAcceptBody1.comment) &&
        Objects.equals(this.sendResponse, eventidMicrosoftGraphTentativelyAcceptBody1.sendResponse) &&
        Objects.equals(this.proposedNewTime, eventidMicrosoftGraphTentativelyAcceptBody1.proposedNewTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, sendResponse, proposedNewTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventidMicrosoftGraphTentativelyAcceptBody1 {\n");
    
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    sendResponse: ").append(toIndentedString(sendResponse)).append("\n");
    sb.append("    proposedNewTime: ").append(toIndentedString(proposedNewTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
