/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ManagedDeviceidMicrosoftGraphWipeBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class ManagedDeviceidMicrosoftGraphWipeBody {
  @JsonProperty("keepEnrollmentData")
  private Boolean keepEnrollmentData = false;

  @JsonProperty("keepUserData")
  private Boolean keepUserData = false;

  @JsonProperty("macOsUnlockCode")
  private String macOsUnlockCode = null;

  @JsonProperty("persistEsimDataPlan")
  private Boolean persistEsimDataPlan = false;

  public ManagedDeviceidMicrosoftGraphWipeBody keepEnrollmentData(Boolean keepEnrollmentData) {
    this.keepEnrollmentData = keepEnrollmentData;
    return this;
  }

   /**
   * Get keepEnrollmentData
   * @return keepEnrollmentData
  **/
  public Boolean isKeepEnrollmentData() {
    return keepEnrollmentData;
  }

  public void setKeepEnrollmentData(Boolean keepEnrollmentData) {
    this.keepEnrollmentData = keepEnrollmentData;
  }

  public ManagedDeviceidMicrosoftGraphWipeBody keepUserData(Boolean keepUserData) {
    this.keepUserData = keepUserData;
    return this;
  }

   /**
   * Get keepUserData
   * @return keepUserData
  **/
  public Boolean isKeepUserData() {
    return keepUserData;
  }

  public void setKeepUserData(Boolean keepUserData) {
    this.keepUserData = keepUserData;
  }

  public ManagedDeviceidMicrosoftGraphWipeBody macOsUnlockCode(String macOsUnlockCode) {
    this.macOsUnlockCode = macOsUnlockCode;
    return this;
  }

   /**
   * Get macOsUnlockCode
   * @return macOsUnlockCode
  **/
  public String getMacOsUnlockCode() {
    return macOsUnlockCode;
  }

  public void setMacOsUnlockCode(String macOsUnlockCode) {
    this.macOsUnlockCode = macOsUnlockCode;
  }

  public ManagedDeviceidMicrosoftGraphWipeBody persistEsimDataPlan(Boolean persistEsimDataPlan) {
    this.persistEsimDataPlan = persistEsimDataPlan;
    return this;
  }

   /**
   * Get persistEsimDataPlan
   * @return persistEsimDataPlan
  **/
  public Boolean isPersistEsimDataPlan() {
    return persistEsimDataPlan;
  }

  public void setPersistEsimDataPlan(Boolean persistEsimDataPlan) {
    this.persistEsimDataPlan = persistEsimDataPlan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagedDeviceidMicrosoftGraphWipeBody managedDeviceidMicrosoftGraphWipeBody = (ManagedDeviceidMicrosoftGraphWipeBody) o;
    return Objects.equals(this.keepEnrollmentData, managedDeviceidMicrosoftGraphWipeBody.keepEnrollmentData) &&
        Objects.equals(this.keepUserData, managedDeviceidMicrosoftGraphWipeBody.keepUserData) &&
        Objects.equals(this.macOsUnlockCode, managedDeviceidMicrosoftGraphWipeBody.macOsUnlockCode) &&
        Objects.equals(this.persistEsimDataPlan, managedDeviceidMicrosoftGraphWipeBody.persistEsimDataPlan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keepEnrollmentData, keepUserData, macOsUnlockCode, persistEsimDataPlan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagedDeviceidMicrosoftGraphWipeBody {\n");
    
    sb.append("    keepEnrollmentData: ").append(toIndentedString(keepEnrollmentData)).append("\n");
    sb.append("    keepUserData: ").append(toIndentedString(keepUserData)).append("\n");
    sb.append("    macOsUnlockCode: ").append(toIndentedString(macOsUnlockCode)).append("\n");
    sb.append("    persistEsimDataPlan: ").append(toIndentedString(persistEsimDataPlan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
