/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphExchangeIdFormat;

import java.util.ArrayList;
import java.util.List;
/**
 * MeMicrosoftGraphTranslateExchangeIdsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MeMicrosoftGraphTranslateExchangeIdsBody {
  @JsonProperty("InputIds")
  private List<String> inputIds = null;

  @JsonProperty("TargetIdType")
  private MicrosoftGraphExchangeIdFormat targetIdType = null;

  @JsonProperty("SourceIdType")
  private MicrosoftGraphExchangeIdFormat sourceIdType = null;

  public MeMicrosoftGraphTranslateExchangeIdsBody inputIds(List<String> inputIds) {
    this.inputIds = inputIds;
    return this;
  }

  public MeMicrosoftGraphTranslateExchangeIdsBody addInputIdsItem(String inputIdsItem) {
    if (this.inputIds == null) {
      this.inputIds = new ArrayList<>();
    }
    this.inputIds.add(inputIdsItem);
    return this;
  }

   /**
   * Get inputIds
   * @return inputIds
  **/
  public List<String> getInputIds() {
    return inputIds;
  }

  public void setInputIds(List<String> inputIds) {
    this.inputIds = inputIds;
  }

  public MeMicrosoftGraphTranslateExchangeIdsBody targetIdType(MicrosoftGraphExchangeIdFormat targetIdType) {
    this.targetIdType = targetIdType;
    return this;
  }

   /**
   * Get targetIdType
   * @return targetIdType
  **/
  public MicrosoftGraphExchangeIdFormat getTargetIdType() {
    return targetIdType;
  }

  public void setTargetIdType(MicrosoftGraphExchangeIdFormat targetIdType) {
    this.targetIdType = targetIdType;
  }

  public MeMicrosoftGraphTranslateExchangeIdsBody sourceIdType(MicrosoftGraphExchangeIdFormat sourceIdType) {
    this.sourceIdType = sourceIdType;
    return this;
  }

   /**
   * Get sourceIdType
   * @return sourceIdType
  **/
  public MicrosoftGraphExchangeIdFormat getSourceIdType() {
    return sourceIdType;
  }

  public void setSourceIdType(MicrosoftGraphExchangeIdFormat sourceIdType) {
    this.sourceIdType = sourceIdType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeMicrosoftGraphTranslateExchangeIdsBody meMicrosoftGraphTranslateExchangeIdsBody = (MeMicrosoftGraphTranslateExchangeIdsBody) o;
    return Objects.equals(this.inputIds, meMicrosoftGraphTranslateExchangeIdsBody.inputIds) &&
        Objects.equals(this.targetIdType, meMicrosoftGraphTranslateExchangeIdsBody.targetIdType) &&
        Objects.equals(this.sourceIdType, meMicrosoftGraphTranslateExchangeIdsBody.sourceIdType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputIds, targetIdType, sourceIdType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeMicrosoftGraphTranslateExchangeIdsBody {\n");
    
    sb.append("    inputIds: ").append(toIndentedString(inputIds)).append("\n");
    sb.append("    targetIdType: ").append(toIndentedString(targetIdType)).append("\n");
    sb.append("    sourceIdType: ").append(toIndentedString(sourceIdType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
