/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphRoot;

/**
 * MicrosoftGraphSiteCollection
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphSiteCollection {
  @JsonProperty("dataLocationCode")
  private String dataLocationCode = null;

  @JsonProperty("hostname")
  private String hostname = null;

  @JsonProperty("root")
  private MicrosoftGraphRoot root = null;

  public MicrosoftGraphSiteCollection dataLocationCode(String dataLocationCode) {
    this.dataLocationCode = dataLocationCode;
    return this;
  }

   /**
   * The geographic region code for where this site collection resides. Read-only.
   * @return dataLocationCode
  **/
  public String getDataLocationCode() {
    return dataLocationCode;
  }

  public void setDataLocationCode(String dataLocationCode) {
    this.dataLocationCode = dataLocationCode;
  }

  public MicrosoftGraphSiteCollection hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

   /**
   * The hostname for the site collection. Read-only.
   * @return hostname
  **/
  public String getHostname() {
    return hostname;
  }

  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public MicrosoftGraphSiteCollection root(MicrosoftGraphRoot root) {
    this.root = root;
    return this;
  }

   /**
   * Get root
   * @return root
  **/
  public MicrosoftGraphRoot getRoot() {
    return root;
  }

  public void setRoot(MicrosoftGraphRoot root) {
    this.root = root;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphSiteCollection microsoftGraphSiteCollection = (MicrosoftGraphSiteCollection) o;
    return Objects.equals(this.dataLocationCode, microsoftGraphSiteCollection.dataLocationCode) &&
        Objects.equals(this.hostname, microsoftGraphSiteCollection.hostname) &&
        Objects.equals(this.root, microsoftGraphSiteCollection.root);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataLocationCode, hostname, root);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphSiteCollection {\n");
    
    sb.append("    dataLocationCode: ").append(toIndentedString(dataLocationCode)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    root: ").append(toIndentedString(root)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
