/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphContentTypeOrder
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphContentTypeOrder {
  @JsonProperty("default")
  private Boolean _default = null;

  @JsonProperty("position")
  private Integer position = null;

  public MicrosoftGraphContentTypeOrder _default(Boolean _default) {
    this._default = _default;
    return this;
  }

   /**
   * Whether this is the default Content Type
   * @return _default
  **/
  public Boolean isDefault() {
    return _default;
  }

  public void setDefault(Boolean _default) {
    this._default = _default;
  }

  public MicrosoftGraphContentTypeOrder position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * Specifies the position in which the Content Type appears in the selection UI.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return position
  **/
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphContentTypeOrder microsoftGraphContentTypeOrder = (MicrosoftGraphContentTypeOrder) o;
    return Objects.equals(this._default, microsoftGraphContentTypeOrder._default) &&
        Objects.equals(this.position, microsoftGraphContentTypeOrder.position);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_default, position);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphContentTypeOrder {\n");
    
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
