/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphDocumentSetVersionItem
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphDocumentSetVersionItem {
  @JsonProperty("itemId")
  private String itemId = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("versionId")
  private String versionId = null;

  public MicrosoftGraphDocumentSetVersionItem itemId(String itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * The unique identifier for the item.
   * @return itemId
  **/
  public String getItemId() {
    return itemId;
  }

  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  public MicrosoftGraphDocumentSetVersionItem title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the item.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public MicrosoftGraphDocumentSetVersionItem versionId(String versionId) {
    this.versionId = versionId;
    return this;
  }

   /**
   * The version ID of the item.
   * @return versionId
  **/
  public String getVersionId() {
    return versionId;
  }

  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphDocumentSetVersionItem microsoftGraphDocumentSetVersionItem = (MicrosoftGraphDocumentSetVersionItem) o;
    return Objects.equals(this.itemId, microsoftGraphDocumentSetVersionItem.itemId) &&
        Objects.equals(this.title, microsoftGraphDocumentSetVersionItem.title) &&
        Objects.equals(this.versionId, microsoftGraphDocumentSetVersionItem.versionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, title, versionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphDocumentSetVersionItem {\n");
    
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
