/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphOnPremisesProvisioningError
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphOnPremisesProvisioningError {
  @JsonProperty("category")
  private String category = null;

  @JsonProperty("occurredDateTime")
  private OffsetDateTime occurredDateTime = null;

  @JsonProperty("propertyCausingError")
  private String propertyCausingError = null;

  @JsonProperty("value")
  private String value = null;

  public MicrosoftGraphOnPremisesProvisioningError category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Category of the provisioning error. Note: Currently, there is only one possible value. Possible value: PropertyConflict - indicates a property value is not unique. Other objects contain the same value for the property.
   * @return category
  **/
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public MicrosoftGraphOnPremisesProvisioningError occurredDateTime(OffsetDateTime occurredDateTime) {
    this.occurredDateTime = occurredDateTime;
    return this;
  }

   /**
   * The date and time at which the error occurred.
   * @return occurredDateTime
  **/
  public OffsetDateTime getOccurredDateTime() {
    return occurredDateTime;
  }

  public void setOccurredDateTime(OffsetDateTime occurredDateTime) {
    this.occurredDateTime = occurredDateTime;
  }

  public MicrosoftGraphOnPremisesProvisioningError propertyCausingError(String propertyCausingError) {
    this.propertyCausingError = propertyCausingError;
    return this;
  }

   /**
   * Name of the directory property causing the error. Current possible values: UserPrincipalName or ProxyAddress
   * @return propertyCausingError
  **/
  public String getPropertyCausingError() {
    return propertyCausingError;
  }

  public void setPropertyCausingError(String propertyCausingError) {
    this.propertyCausingError = propertyCausingError;
  }

  public MicrosoftGraphOnPremisesProvisioningError value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Value of the property causing the error.
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphOnPremisesProvisioningError microsoftGraphOnPremisesProvisioningError = (MicrosoftGraphOnPremisesProvisioningError) o;
    return Objects.equals(this.category, microsoftGraphOnPremisesProvisioningError.category) &&
        Objects.equals(this.occurredDateTime, microsoftGraphOnPremisesProvisioningError.occurredDateTime) &&
        Objects.equals(this.propertyCausingError, microsoftGraphOnPremisesProvisioningError.propertyCausingError) &&
        Objects.equals(this.value, microsoftGraphOnPremisesProvisioningError.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, occurredDateTime, propertyCausingError, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphOnPremisesProvisioningError {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    occurredDateTime: ").append(toIndentedString(occurredDateTime)).append("\n");
    sb.append("    propertyCausingError: ").append(toIndentedString(propertyCausingError)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
