/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphBaseItemVersion;
import com.microsoft.graph.MicrosoftGraphIdentitySet;
import com.microsoft.graph.MicrosoftGraphPublicationFacet;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphDriveItemVersion
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphDriveItemVersion extends MicrosoftGraphBaseItemVersion {
  @JsonProperty("content")
  private String content = null;

  @JsonProperty("size")
  private Long size = null;

  public MicrosoftGraphDriveItemVersion content(String content) {
    this.content = content;
    return this;
  }

   /**
   * The content stream for this version of the item.
   * @return content
  **/
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public MicrosoftGraphDriveItemVersion size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Indicates the size of the content stream for this version of the item.
   * @return size
  **/
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphDriveItemVersion microsoftGraphDriveItemVersion = (MicrosoftGraphDriveItemVersion) o;
    return Objects.equals(this.content, microsoftGraphDriveItemVersion.content) &&
        Objects.equals(this.size, microsoftGraphDriveItemVersion.size) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, size, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphDriveItemVersion {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
