/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Device Exchange Access State.
 */
public enum MicrosoftGraphDeviceManagementExchangeAccessState {
  NONE("none"),
  UNKNOWN("unknown"),
  ALLOWED("allowed"),
  BLOCKED("blocked"),
  QUARANTINED("quarantined");

  private String value;

  MicrosoftGraphDeviceManagementExchangeAccessState(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MicrosoftGraphDeviceManagementExchangeAccessState fromValue(String input) {
    for (MicrosoftGraphDeviceManagementExchangeAccessState b : MicrosoftGraphDeviceManagementExchangeAccessState.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
