/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphWebsiteType;

/**
 * MicrosoftGraphWebsite
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWebsite {
  @JsonProperty("address")
  private String address = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("type")
  private MicrosoftGraphWebsiteType type = null;

  public MicrosoftGraphWebsite address(String address) {
    this.address = address;
    return this;
  }

   /**
   * The URL of the website.
   * @return address
  **/
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public MicrosoftGraphWebsite displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name of the web site.
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MicrosoftGraphWebsite type(MicrosoftGraphWebsiteType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public MicrosoftGraphWebsiteType getType() {
    return type;
  }

  public void setType(MicrosoftGraphWebsiteType type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWebsite microsoftGraphWebsite = (MicrosoftGraphWebsite) o;
    return Objects.equals(this.address, microsoftGraphWebsite.address) &&
        Objects.equals(this.displayName, microsoftGraphWebsite.displayName) &&
        Objects.equals(this.type, microsoftGraphWebsite.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, displayName, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWebsite {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
