/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphTeamMessagingSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTeamMessagingSettings {
  @JsonProperty("allowChannelMentions")
  private Boolean allowChannelMentions = null;

  @JsonProperty("allowOwnerDeleteMessages")
  private Boolean allowOwnerDeleteMessages = null;

  @JsonProperty("allowTeamMentions")
  private Boolean allowTeamMentions = null;

  @JsonProperty("allowUserDeleteMessages")
  private Boolean allowUserDeleteMessages = null;

  @JsonProperty("allowUserEditMessages")
  private Boolean allowUserEditMessages = null;

  public MicrosoftGraphTeamMessagingSettings allowChannelMentions(Boolean allowChannelMentions) {
    this.allowChannelMentions = allowChannelMentions;
    return this;
  }

   /**
   * If set to true, @channel mentions are allowed.
   * @return allowChannelMentions
  **/
  public Boolean isAllowChannelMentions() {
    return allowChannelMentions;
  }

  public void setAllowChannelMentions(Boolean allowChannelMentions) {
    this.allowChannelMentions = allowChannelMentions;
  }

  public MicrosoftGraphTeamMessagingSettings allowOwnerDeleteMessages(Boolean allowOwnerDeleteMessages) {
    this.allowOwnerDeleteMessages = allowOwnerDeleteMessages;
    return this;
  }

   /**
   * If set to true, owners can delete any message.
   * @return allowOwnerDeleteMessages
  **/
  public Boolean isAllowOwnerDeleteMessages() {
    return allowOwnerDeleteMessages;
  }

  public void setAllowOwnerDeleteMessages(Boolean allowOwnerDeleteMessages) {
    this.allowOwnerDeleteMessages = allowOwnerDeleteMessages;
  }

  public MicrosoftGraphTeamMessagingSettings allowTeamMentions(Boolean allowTeamMentions) {
    this.allowTeamMentions = allowTeamMentions;
    return this;
  }

   /**
   * If set to true, @team mentions are allowed.
   * @return allowTeamMentions
  **/
  public Boolean isAllowTeamMentions() {
    return allowTeamMentions;
  }

  public void setAllowTeamMentions(Boolean allowTeamMentions) {
    this.allowTeamMentions = allowTeamMentions;
  }

  public MicrosoftGraphTeamMessagingSettings allowUserDeleteMessages(Boolean allowUserDeleteMessages) {
    this.allowUserDeleteMessages = allowUserDeleteMessages;
    return this;
  }

   /**
   * If set to true, users can delete their messages.
   * @return allowUserDeleteMessages
  **/
  public Boolean isAllowUserDeleteMessages() {
    return allowUserDeleteMessages;
  }

  public void setAllowUserDeleteMessages(Boolean allowUserDeleteMessages) {
    this.allowUserDeleteMessages = allowUserDeleteMessages;
  }

  public MicrosoftGraphTeamMessagingSettings allowUserEditMessages(Boolean allowUserEditMessages) {
    this.allowUserEditMessages = allowUserEditMessages;
    return this;
  }

   /**
   * If set to true, users can edit their messages.
   * @return allowUserEditMessages
  **/
  public Boolean isAllowUserEditMessages() {
    return allowUserEditMessages;
  }

  public void setAllowUserEditMessages(Boolean allowUserEditMessages) {
    this.allowUserEditMessages = allowUserEditMessages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTeamMessagingSettings microsoftGraphTeamMessagingSettings = (MicrosoftGraphTeamMessagingSettings) o;
    return Objects.equals(this.allowChannelMentions, microsoftGraphTeamMessagingSettings.allowChannelMentions) &&
        Objects.equals(this.allowOwnerDeleteMessages, microsoftGraphTeamMessagingSettings.allowOwnerDeleteMessages) &&
        Objects.equals(this.allowTeamMentions, microsoftGraphTeamMessagingSettings.allowTeamMentions) &&
        Objects.equals(this.allowUserDeleteMessages, microsoftGraphTeamMessagingSettings.allowUserDeleteMessages) &&
        Objects.equals(this.allowUserEditMessages, microsoftGraphTeamMessagingSettings.allowUserEditMessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowChannelMentions, allowOwnerDeleteMessages, allowTeamMentions, allowUserDeleteMessages, allowUserEditMessages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTeamMessagingSettings {\n");
    
    sb.append("    allowChannelMentions: ").append(toIndentedString(allowChannelMentions)).append("\n");
    sb.append("    allowOwnerDeleteMessages: ").append(toIndentedString(allowOwnerDeleteMessages)).append("\n");
    sb.append("    allowTeamMentions: ").append(toIndentedString(allowTeamMentions)).append("\n");
    sb.append("    allowUserDeleteMessages: ").append(toIndentedString(allowUserDeleteMessages)).append("\n");
    sb.append("    allowUserEditMessages: ").append(toIndentedString(allowUserEditMessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
