/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphCalendar;
import com.microsoft.graph.MicrosoftGraphEntity;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * MicrosoftGraphCalendarGroup
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphCalendarGroup extends MicrosoftGraphEntity {
  @JsonProperty("changeKey")
  private String changeKey = null;

  @JsonProperty("classId")
  private UUID classId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("calendars")
  private List<MicrosoftGraphCalendar> calendars = null;

  public MicrosoftGraphCalendarGroup changeKey(String changeKey) {
    this.changeKey = changeKey;
    return this;
  }

   /**
   * Identifies the version of the calendar group. Every time the calendar group is changed, ChangeKey changes as well. This allows Exchange to apply changes to the correct version of the object. Read-only.
   * @return changeKey
  **/
  public String getChangeKey() {
    return changeKey;
  }

  public void setChangeKey(String changeKey) {
    this.changeKey = changeKey;
  }

  public MicrosoftGraphCalendarGroup classId(UUID classId) {
    this.classId = classId;
    return this;
  }

   /**
   * The class identifier. Read-only.
   * @return classId
  **/
  public UUID getClassId() {
    return classId;
  }

  public void setClassId(UUID classId) {
    this.classId = classId;
  }

  public MicrosoftGraphCalendarGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The group name.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftGraphCalendarGroup calendars(List<MicrosoftGraphCalendar> calendars) {
    this.calendars = calendars;
    return this;
  }

  public MicrosoftGraphCalendarGroup addCalendarsItem(MicrosoftGraphCalendar calendarsItem) {
    if (this.calendars == null) {
      this.calendars = new ArrayList<>();
    }
    this.calendars.add(calendarsItem);
    return this;
  }

   /**
   * The calendars in the calendar group. Navigation property. Read-only. Nullable.
   * @return calendars
  **/
  public List<MicrosoftGraphCalendar> getCalendars() {
    return calendars;
  }

  public void setCalendars(List<MicrosoftGraphCalendar> calendars) {
    this.calendars = calendars;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphCalendarGroup microsoftGraphCalendarGroup = (MicrosoftGraphCalendarGroup) o;
    return Objects.equals(this.changeKey, microsoftGraphCalendarGroup.changeKey) &&
        Objects.equals(this.classId, microsoftGraphCalendarGroup.classId) &&
        Objects.equals(this.name, microsoftGraphCalendarGroup.name) &&
        Objects.equals(this.calendars, microsoftGraphCalendarGroup.calendars) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeKey, classId, name, calendars, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphCalendarGroup {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    changeKey: ").append(toIndentedString(changeKey)).append("\n");
    sb.append("    classId: ").append(toIndentedString(classId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    calendars: ").append(toIndentedString(calendars)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
