/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphTextColumn
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTextColumn {
  @JsonProperty("allowMultipleLines")
  private Boolean allowMultipleLines = null;

  @JsonProperty("appendChangesToExistingText")
  private Boolean appendChangesToExistingText = null;

  @JsonProperty("linesForEditing")
  private Integer linesForEditing = null;

  @JsonProperty("maxLength")
  private Integer maxLength = null;

  @JsonProperty("textType")
  private String textType = null;

  public MicrosoftGraphTextColumn allowMultipleLines(Boolean allowMultipleLines) {
    this.allowMultipleLines = allowMultipleLines;
    return this;
  }

   /**
   * Whether to allow multiple lines of text.
   * @return allowMultipleLines
  **/
  public Boolean isAllowMultipleLines() {
    return allowMultipleLines;
  }

  public void setAllowMultipleLines(Boolean allowMultipleLines) {
    this.allowMultipleLines = allowMultipleLines;
  }

  public MicrosoftGraphTextColumn appendChangesToExistingText(Boolean appendChangesToExistingText) {
    this.appendChangesToExistingText = appendChangesToExistingText;
    return this;
  }

   /**
   * Whether updates to this column should replace existing text, or append to it.
   * @return appendChangesToExistingText
  **/
  public Boolean isAppendChangesToExistingText() {
    return appendChangesToExistingText;
  }

  public void setAppendChangesToExistingText(Boolean appendChangesToExistingText) {
    this.appendChangesToExistingText = appendChangesToExistingText;
  }

  public MicrosoftGraphTextColumn linesForEditing(Integer linesForEditing) {
    this.linesForEditing = linesForEditing;
    return this;
  }

   /**
   * The size of the text box.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return linesForEditing
  **/
  public Integer getLinesForEditing() {
    return linesForEditing;
  }

  public void setLinesForEditing(Integer linesForEditing) {
    this.linesForEditing = linesForEditing;
  }

  public MicrosoftGraphTextColumn maxLength(Integer maxLength) {
    this.maxLength = maxLength;
    return this;
  }

   /**
   * The maximum number of characters for the value.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return maxLength
  **/
  public Integer getMaxLength() {
    return maxLength;
  }

  public void setMaxLength(Integer maxLength) {
    this.maxLength = maxLength;
  }

  public MicrosoftGraphTextColumn textType(String textType) {
    this.textType = textType;
    return this;
  }

   /**
   * The type of text being stored. Must be one of plain or richText
   * @return textType
  **/
  public String getTextType() {
    return textType;
  }

  public void setTextType(String textType) {
    this.textType = textType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTextColumn microsoftGraphTextColumn = (MicrosoftGraphTextColumn) o;
    return Objects.equals(this.allowMultipleLines, microsoftGraphTextColumn.allowMultipleLines) &&
        Objects.equals(this.appendChangesToExistingText, microsoftGraphTextColumn.appendChangesToExistingText) &&
        Objects.equals(this.linesForEditing, microsoftGraphTextColumn.linesForEditing) &&
        Objects.equals(this.maxLength, microsoftGraphTextColumn.maxLength) &&
        Objects.equals(this.textType, microsoftGraphTextColumn.textType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowMultipleLines, appendChangesToExistingText, linesForEditing, maxLength, textType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTextColumn {\n");
    
    sb.append("    allowMultipleLines: ").append(toIndentedString(allowMultipleLines)).append("\n");
    sb.append("    appendChangesToExistingText: ").append(toIndentedString(appendChangesToExistingText)).append("\n");
    sb.append("    linesForEditing: ").append(toIndentedString(linesForEditing)).append("\n");
    sb.append("    maxLength: ").append(toIndentedString(maxLength)).append("\n");
    sb.append("    textType: ").append(toIndentedString(textType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
