/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphFreeBusyError;
import com.microsoft.graph.MicrosoftGraphScheduleItem;
import com.microsoft.graph.MicrosoftGraphWorkingHours;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphScheduleInformation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphScheduleInformation {
  @JsonProperty("availabilityView")
  private String availabilityView = null;

  @JsonProperty("error")
  private MicrosoftGraphFreeBusyError error = null;

  @JsonProperty("scheduleId")
  private String scheduleId = null;

  @JsonProperty("scheduleItems")
  private List<MicrosoftGraphScheduleItem> scheduleItems = null;

  @JsonProperty("workingHours")
  private MicrosoftGraphWorkingHours workingHours = null;

  public MicrosoftGraphScheduleInformation availabilityView(String availabilityView) {
    this.availabilityView = availabilityView;
    return this;
  }

   /**
   * Represents a merged view of availability of all the items in scheduleItems. The view consists of time slots. Availability during each time slot is indicated with: 0&#x3D; free, 1&#x3D; tentative, 2&#x3D; busy, 3&#x3D; out of office, 4&#x3D; working elsewhere.
   * @return availabilityView
  **/
  public String getAvailabilityView() {
    return availabilityView;
  }

  public void setAvailabilityView(String availabilityView) {
    this.availabilityView = availabilityView;
  }

  public MicrosoftGraphScheduleInformation error(MicrosoftGraphFreeBusyError error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  public MicrosoftGraphFreeBusyError getError() {
    return error;
  }

  public void setError(MicrosoftGraphFreeBusyError error) {
    this.error = error;
  }

  public MicrosoftGraphScheduleInformation scheduleId(String scheduleId) {
    this.scheduleId = scheduleId;
    return this;
  }

   /**
   * An SMTP address of the user, distribution list, or resource, identifying an instance of scheduleInformation.
   * @return scheduleId
  **/
  public String getScheduleId() {
    return scheduleId;
  }

  public void setScheduleId(String scheduleId) {
    this.scheduleId = scheduleId;
  }

  public MicrosoftGraphScheduleInformation scheduleItems(List<MicrosoftGraphScheduleItem> scheduleItems) {
    this.scheduleItems = scheduleItems;
    return this;
  }

  public MicrosoftGraphScheduleInformation addScheduleItemsItem(MicrosoftGraphScheduleItem scheduleItemsItem) {
    if (this.scheduleItems == null) {
      this.scheduleItems = new ArrayList<>();
    }
    this.scheduleItems.add(scheduleItemsItem);
    return this;
  }

   /**
   * Contains the items that describe the availability of the user or resource.
   * @return scheduleItems
  **/
  public List<MicrosoftGraphScheduleItem> getScheduleItems() {
    return scheduleItems;
  }

  public void setScheduleItems(List<MicrosoftGraphScheduleItem> scheduleItems) {
    this.scheduleItems = scheduleItems;
  }

  public MicrosoftGraphScheduleInformation workingHours(MicrosoftGraphWorkingHours workingHours) {
    this.workingHours = workingHours;
    return this;
  }

   /**
   * Get workingHours
   * @return workingHours
  **/
  public MicrosoftGraphWorkingHours getWorkingHours() {
    return workingHours;
  }

  public void setWorkingHours(MicrosoftGraphWorkingHours workingHours) {
    this.workingHours = workingHours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphScheduleInformation microsoftGraphScheduleInformation = (MicrosoftGraphScheduleInformation) o;
    return Objects.equals(this.availabilityView, microsoftGraphScheduleInformation.availabilityView) &&
        Objects.equals(this.error, microsoftGraphScheduleInformation.error) &&
        Objects.equals(this.scheduleId, microsoftGraphScheduleInformation.scheduleId) &&
        Objects.equals(this.scheduleItems, microsoftGraphScheduleInformation.scheduleItems) &&
        Objects.equals(this.workingHours, microsoftGraphScheduleInformation.workingHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availabilityView, error, scheduleId, scheduleItems, workingHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphScheduleInformation {\n");
    
    sb.append("    availabilityView: ").append(toIndentedString(availabilityView)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    scheduleId: ").append(toIndentedString(scheduleId)).append("\n");
    sb.append("    scheduleItems: ").append(toIndentedString(scheduleItems)).append("\n");
    sb.append("    workingHours: ").append(toIndentedString(workingHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
