/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphChannelIdentity;
import com.microsoft.graph.MicrosoftGraphChatMessage;
import com.microsoft.graph.MicrosoftGraphChatMessageAttachment;
import com.microsoft.graph.MicrosoftGraphChatMessageFromIdentitySet;
import com.microsoft.graph.MicrosoftGraphChatMessageHostedContent;
import com.microsoft.graph.MicrosoftGraphChatMessageImportance;
import com.microsoft.graph.MicrosoftGraphChatMessageMention;
import com.microsoft.graph.MicrosoftGraphChatMessagePolicyViolation;
import com.microsoft.graph.MicrosoftGraphChatMessageReaction;
import com.microsoft.graph.MicrosoftGraphChatMessageType;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphEventMessageDetail;
import com.microsoft.graph.MicrosoftGraphItemBody;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphChatMessage
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphChatMessage extends MicrosoftGraphEntity {
  @JsonProperty("attachments")
  private List<MicrosoftGraphChatMessageAttachment> attachments = null;

  @JsonProperty("body")
  private MicrosoftGraphItemBody body = null;

  @JsonProperty("channelIdentity")
  private MicrosoftGraphChannelIdentity channelIdentity = null;

  @JsonProperty("chatId")
  private String chatId = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("deletedDateTime")
  private OffsetDateTime deletedDateTime = null;

  @JsonProperty("etag")
  private String etag = null;

  @JsonProperty("eventDetail")
  private MicrosoftGraphEventMessageDetail eventDetail = null;

  @JsonProperty("from")
  private MicrosoftGraphChatMessageFromIdentitySet from = null;

  @JsonProperty("importance")
  private MicrosoftGraphChatMessageImportance importance = null;

  @JsonProperty("lastEditedDateTime")
  private OffsetDateTime lastEditedDateTime = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("mentions")
  private List<MicrosoftGraphChatMessageMention> mentions = null;

  @JsonProperty("messageType")
  private MicrosoftGraphChatMessageType messageType = null;

  @JsonProperty("policyViolation")
  private MicrosoftGraphChatMessagePolicyViolation policyViolation = null;

  @JsonProperty("reactions")
  private List<MicrosoftGraphChatMessageReaction> reactions = null;

  @JsonProperty("replyToId")
  private String replyToId = null;

  @JsonProperty("subject")
  private String subject = null;

  @JsonProperty("summary")
  private String summary = null;

  @JsonProperty("webUrl")
  private String webUrl = null;

  @JsonProperty("hostedContents")
  private List<MicrosoftGraphChatMessageHostedContent> hostedContents = null;

  @JsonProperty("replies")
  private List<MicrosoftGraphChatMessage> replies = null;

  public MicrosoftGraphChatMessage attachments(List<MicrosoftGraphChatMessageAttachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public MicrosoftGraphChatMessage addAttachmentsItem(MicrosoftGraphChatMessageAttachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * References to attached objects like files, tabs, meetings etc.
   * @return attachments
  **/
  public List<MicrosoftGraphChatMessageAttachment> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<MicrosoftGraphChatMessageAttachment> attachments) {
    this.attachments = attachments;
  }

  public MicrosoftGraphChatMessage body(MicrosoftGraphItemBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  public MicrosoftGraphItemBody getBody() {
    return body;
  }

  public void setBody(MicrosoftGraphItemBody body) {
    this.body = body;
  }

  public MicrosoftGraphChatMessage channelIdentity(MicrosoftGraphChannelIdentity channelIdentity) {
    this.channelIdentity = channelIdentity;
    return this;
  }

   /**
   * Get channelIdentity
   * @return channelIdentity
  **/
  public MicrosoftGraphChannelIdentity getChannelIdentity() {
    return channelIdentity;
  }

  public void setChannelIdentity(MicrosoftGraphChannelIdentity channelIdentity) {
    this.channelIdentity = channelIdentity;
  }

  public MicrosoftGraphChatMessage chatId(String chatId) {
    this.chatId = chatId;
    return this;
  }

   /**
   * If the message was sent in a chat, represents the identity of the chat.
   * @return chatId
  **/
  public String getChatId() {
    return chatId;
  }

  public void setChatId(String chatId) {
    this.chatId = chatId;
  }

  public MicrosoftGraphChatMessage createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Timestamp of when the chat message was created.
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphChatMessage deletedDateTime(OffsetDateTime deletedDateTime) {
    this.deletedDateTime = deletedDateTime;
    return this;
  }

   /**
   * Read only. Timestamp at which the chat message was deleted, or null if not deleted.
   * @return deletedDateTime
  **/
  public OffsetDateTime getDeletedDateTime() {
    return deletedDateTime;
  }

  public void setDeletedDateTime(OffsetDateTime deletedDateTime) {
    this.deletedDateTime = deletedDateTime;
  }

  public MicrosoftGraphChatMessage etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * Read-only. Version number of the chat message.
   * @return etag
  **/
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }

  public MicrosoftGraphChatMessage eventDetail(MicrosoftGraphEventMessageDetail eventDetail) {
    this.eventDetail = eventDetail;
    return this;
  }

   /**
   * Get eventDetail
   * @return eventDetail
  **/
  public MicrosoftGraphEventMessageDetail getEventDetail() {
    return eventDetail;
  }

  public void setEventDetail(MicrosoftGraphEventMessageDetail eventDetail) {
    this.eventDetail = eventDetail;
  }

  public MicrosoftGraphChatMessage from(MicrosoftGraphChatMessageFromIdentitySet from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  public MicrosoftGraphChatMessageFromIdentitySet getFrom() {
    return from;
  }

  public void setFrom(MicrosoftGraphChatMessageFromIdentitySet from) {
    this.from = from;
  }

  public MicrosoftGraphChatMessage importance(MicrosoftGraphChatMessageImportance importance) {
    this.importance = importance;
    return this;
  }

   /**
   * Get importance
   * @return importance
  **/
  public MicrosoftGraphChatMessageImportance getImportance() {
    return importance;
  }

  public void setImportance(MicrosoftGraphChatMessageImportance importance) {
    this.importance = importance;
  }

  public MicrosoftGraphChatMessage lastEditedDateTime(OffsetDateTime lastEditedDateTime) {
    this.lastEditedDateTime = lastEditedDateTime;
    return this;
  }

   /**
   * Read only. Timestamp when edits to the chat message were made. Triggers an &#x27;Edited&#x27; flag in the Teams UI. If no edits are made the value is null.
   * @return lastEditedDateTime
  **/
  public OffsetDateTime getLastEditedDateTime() {
    return lastEditedDateTime;
  }

  public void setLastEditedDateTime(OffsetDateTime lastEditedDateTime) {
    this.lastEditedDateTime = lastEditedDateTime;
  }

  public MicrosoftGraphChatMessage lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Read only. Timestamp when the chat message is created (initial setting) or modified, including when a reaction is added or removed.
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public MicrosoftGraphChatMessage locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Locale of the chat message set by the client. Always set to en-us.
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public MicrosoftGraphChatMessage mentions(List<MicrosoftGraphChatMessageMention> mentions) {
    this.mentions = mentions;
    return this;
  }

  public MicrosoftGraphChatMessage addMentionsItem(MicrosoftGraphChatMessageMention mentionsItem) {
    if (this.mentions == null) {
      this.mentions = new ArrayList<>();
    }
    this.mentions.add(mentionsItem);
    return this;
  }

   /**
   * List of entities mentioned in the chat message. Supported entities are: user, bot, team, and channel.
   * @return mentions
  **/
  public List<MicrosoftGraphChatMessageMention> getMentions() {
    return mentions;
  }

  public void setMentions(List<MicrosoftGraphChatMessageMention> mentions) {
    this.mentions = mentions;
  }

  public MicrosoftGraphChatMessage messageType(MicrosoftGraphChatMessageType messageType) {
    this.messageType = messageType;
    return this;
  }

   /**
   * Get messageType
   * @return messageType
  **/
  public MicrosoftGraphChatMessageType getMessageType() {
    return messageType;
  }

  public void setMessageType(MicrosoftGraphChatMessageType messageType) {
    this.messageType = messageType;
  }

  public MicrosoftGraphChatMessage policyViolation(MicrosoftGraphChatMessagePolicyViolation policyViolation) {
    this.policyViolation = policyViolation;
    return this;
  }

   /**
   * Get policyViolation
   * @return policyViolation
  **/
  public MicrosoftGraphChatMessagePolicyViolation getPolicyViolation() {
    return policyViolation;
  }

  public void setPolicyViolation(MicrosoftGraphChatMessagePolicyViolation policyViolation) {
    this.policyViolation = policyViolation;
  }

  public MicrosoftGraphChatMessage reactions(List<MicrosoftGraphChatMessageReaction> reactions) {
    this.reactions = reactions;
    return this;
  }

  public MicrosoftGraphChatMessage addReactionsItem(MicrosoftGraphChatMessageReaction reactionsItem) {
    if (this.reactions == null) {
      this.reactions = new ArrayList<>();
    }
    this.reactions.add(reactionsItem);
    return this;
  }

   /**
   * Reactions for this chat message (for example, Like).
   * @return reactions
  **/
  public List<MicrosoftGraphChatMessageReaction> getReactions() {
    return reactions;
  }

  public void setReactions(List<MicrosoftGraphChatMessageReaction> reactions) {
    this.reactions = reactions;
  }

  public MicrosoftGraphChatMessage replyToId(String replyToId) {
    this.replyToId = replyToId;
    return this;
  }

   /**
   * Read-only. ID of the parent chat message or root chat message of the thread. (Only applies to chat messages in channels, not chats.)
   * @return replyToId
  **/
  public String getReplyToId() {
    return replyToId;
  }

  public void setReplyToId(String replyToId) {
    this.replyToId = replyToId;
  }

  public MicrosoftGraphChatMessage subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * The subject of the chat message, in plaintext.
   * @return subject
  **/
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public MicrosoftGraphChatMessage summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Summary text of the chat message that could be used for push notifications and summary views or fall back views. Only applies to channel chat messages, not chat messages in a chat.
   * @return summary
  **/
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public MicrosoftGraphChatMessage webUrl(String webUrl) {
    this.webUrl = webUrl;
    return this;
  }

   /**
   * Read-only. Link to the message in Microsoft Teams.
   * @return webUrl
  **/
  public String getWebUrl() {
    return webUrl;
  }

  public void setWebUrl(String webUrl) {
    this.webUrl = webUrl;
  }

  public MicrosoftGraphChatMessage hostedContents(List<MicrosoftGraphChatMessageHostedContent> hostedContents) {
    this.hostedContents = hostedContents;
    return this;
  }

  public MicrosoftGraphChatMessage addHostedContentsItem(MicrosoftGraphChatMessageHostedContent hostedContentsItem) {
    if (this.hostedContents == null) {
      this.hostedContents = new ArrayList<>();
    }
    this.hostedContents.add(hostedContentsItem);
    return this;
  }

   /**
   * Content in a message hosted by Microsoft Teams - for example, images or code snippets.
   * @return hostedContents
  **/
  public List<MicrosoftGraphChatMessageHostedContent> getHostedContents() {
    return hostedContents;
  }

  public void setHostedContents(List<MicrosoftGraphChatMessageHostedContent> hostedContents) {
    this.hostedContents = hostedContents;
  }

  public MicrosoftGraphChatMessage replies(List<MicrosoftGraphChatMessage> replies) {
    this.replies = replies;
    return this;
  }

  public MicrosoftGraphChatMessage addRepliesItem(MicrosoftGraphChatMessage repliesItem) {
    if (this.replies == null) {
      this.replies = new ArrayList<>();
    }
    this.replies.add(repliesItem);
    return this;
  }

   /**
   * Replies for a specified message. Supports $expand for channel messages.
   * @return replies
  **/
  public List<MicrosoftGraphChatMessage> getReplies() {
    return replies;
  }

  public void setReplies(List<MicrosoftGraphChatMessage> replies) {
    this.replies = replies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphChatMessage microsoftGraphChatMessage = (MicrosoftGraphChatMessage) o;
    return Objects.equals(this.attachments, microsoftGraphChatMessage.attachments) &&
        Objects.equals(this.body, microsoftGraphChatMessage.body) &&
        Objects.equals(this.channelIdentity, microsoftGraphChatMessage.channelIdentity) &&
        Objects.equals(this.chatId, microsoftGraphChatMessage.chatId) &&
        Objects.equals(this.createdDateTime, microsoftGraphChatMessage.createdDateTime) &&
        Objects.equals(this.deletedDateTime, microsoftGraphChatMessage.deletedDateTime) &&
        Objects.equals(this.etag, microsoftGraphChatMessage.etag) &&
        Objects.equals(this.eventDetail, microsoftGraphChatMessage.eventDetail) &&
        Objects.equals(this.from, microsoftGraphChatMessage.from) &&
        Objects.equals(this.importance, microsoftGraphChatMessage.importance) &&
        Objects.equals(this.lastEditedDateTime, microsoftGraphChatMessage.lastEditedDateTime) &&
        Objects.equals(this.lastModifiedDateTime, microsoftGraphChatMessage.lastModifiedDateTime) &&
        Objects.equals(this.locale, microsoftGraphChatMessage.locale) &&
        Objects.equals(this.mentions, microsoftGraphChatMessage.mentions) &&
        Objects.equals(this.messageType, microsoftGraphChatMessage.messageType) &&
        Objects.equals(this.policyViolation, microsoftGraphChatMessage.policyViolation) &&
        Objects.equals(this.reactions, microsoftGraphChatMessage.reactions) &&
        Objects.equals(this.replyToId, microsoftGraphChatMessage.replyToId) &&
        Objects.equals(this.subject, microsoftGraphChatMessage.subject) &&
        Objects.equals(this.summary, microsoftGraphChatMessage.summary) &&
        Objects.equals(this.webUrl, microsoftGraphChatMessage.webUrl) &&
        Objects.equals(this.hostedContents, microsoftGraphChatMessage.hostedContents) &&
        Objects.equals(this.replies, microsoftGraphChatMessage.replies) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachments, body, channelIdentity, chatId, createdDateTime, deletedDateTime, etag, eventDetail, from, importance, lastEditedDateTime, lastModifiedDateTime, locale, mentions, messageType, policyViolation, reactions, replyToId, subject, summary, webUrl, hostedContents, replies, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphChatMessage {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    channelIdentity: ").append(toIndentedString(channelIdentity)).append("\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    deletedDateTime: ").append(toIndentedString(deletedDateTime)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    eventDetail: ").append(toIndentedString(eventDetail)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    importance: ").append(toIndentedString(importance)).append("\n");
    sb.append("    lastEditedDateTime: ").append(toIndentedString(lastEditedDateTime)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    mentions: ").append(toIndentedString(mentions)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("    policyViolation: ").append(toIndentedString(policyViolation)).append("\n");
    sb.append("    reactions: ").append(toIndentedString(reactions)).append("\n");
    sb.append("    replyToId: ").append(toIndentedString(replyToId)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    webUrl: ").append(toIndentedString(webUrl)).append("\n");
    sb.append("    hostedContents: ").append(toIndentedString(hostedContents)).append("\n");
    sb.append("    replies: ").append(toIndentedString(replies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
