/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Supported platform types for policies.
 */
public enum MicrosoftGraphPolicyPlatformType {
  ANDROID("android"),
  ANDROIDFORWORK("androidForWork"),
  IOS("iOS"),
  MACOS("macOS"),
  WINDOWSPHONE81("windowsPhone81"),
  WINDOWS81ANDLATER("windows81AndLater"),
  WINDOWS10ANDLATER("windows10AndLater"),
  ALL("all");

  private String value;

  MicrosoftGraphPolicyPlatformType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MicrosoftGraphPolicyPlatformType fromValue(String input) {
    for (MicrosoftGraphPolicyPlatformType b : MicrosoftGraphPolicyPlatformType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
