/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphAuthenticationMethod;
import com.microsoft.graph.MicrosoftGraphAuthenticationMethodSignInState;
import com.microsoft.graph.MicrosoftGraphAuthenticationPhoneType;

/**
 * MicrosoftGraphPhoneAuthenticationMethod
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphPhoneAuthenticationMethod extends MicrosoftGraphAuthenticationMethod {
  @JsonProperty("phoneNumber")
  private String phoneNumber = null;

  @JsonProperty("phoneType")
  private MicrosoftGraphAuthenticationPhoneType phoneType = null;

  @JsonProperty("smsSignInState")
  private MicrosoftGraphAuthenticationMethodSignInState smsSignInState = null;

  public MicrosoftGraphPhoneAuthenticationMethod phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * The phone number to text or call for authentication. Phone numbers use the format +{country code} {number}x{extension}, with extension optional. For example, +1 5555551234 or +1 5555551234x123 are valid. Numbers are rejected when creating or updating if they do not match the required format.
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public MicrosoftGraphPhoneAuthenticationMethod phoneType(MicrosoftGraphAuthenticationPhoneType phoneType) {
    this.phoneType = phoneType;
    return this;
  }

   /**
   * Get phoneType
   * @return phoneType
  **/
  public MicrosoftGraphAuthenticationPhoneType getPhoneType() {
    return phoneType;
  }

  public void setPhoneType(MicrosoftGraphAuthenticationPhoneType phoneType) {
    this.phoneType = phoneType;
  }

  public MicrosoftGraphPhoneAuthenticationMethod smsSignInState(MicrosoftGraphAuthenticationMethodSignInState smsSignInState) {
    this.smsSignInState = smsSignInState;
    return this;
  }

   /**
   * Get smsSignInState
   * @return smsSignInState
  **/
  public MicrosoftGraphAuthenticationMethodSignInState getSmsSignInState() {
    return smsSignInState;
  }

  public void setSmsSignInState(MicrosoftGraphAuthenticationMethodSignInState smsSignInState) {
    this.smsSignInState = smsSignInState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphPhoneAuthenticationMethod microsoftGraphPhoneAuthenticationMethod = (MicrosoftGraphPhoneAuthenticationMethod) o;
    return Objects.equals(this.phoneNumber, microsoftGraphPhoneAuthenticationMethod.phoneNumber) &&
        Objects.equals(this.phoneType, microsoftGraphPhoneAuthenticationMethod.phoneType) &&
        Objects.equals(this.smsSignInState, microsoftGraphPhoneAuthenticationMethod.smsSignInState) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneNumber, phoneType, smsSignInState, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphPhoneAuthenticationMethod {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneType: ").append(toIndentedString(phoneType)).append("\n");
    sb.append("    smsSignInState: ").append(toIndentedString(smsSignInState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
