/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphActivityHistoryItem;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphJson;
import com.microsoft.graph.MicrosoftGraphStatus;
import com.microsoft.graph.MicrosoftGraphVisualInfo;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphUserActivity
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphUserActivity extends MicrosoftGraphEntity {
  @JsonProperty("activationUrl")
  private String activationUrl = null;

  @JsonProperty("activitySourceHost")
  private String activitySourceHost = null;

  @JsonProperty("appActivityId")
  private String appActivityId = null;

  @JsonProperty("appDisplayName")
  private String appDisplayName = null;

  @JsonProperty("contentInfo")
  private MicrosoftGraphJson contentInfo = null;

  @JsonProperty("contentUrl")
  private String contentUrl = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("expirationDateTime")
  private OffsetDateTime expirationDateTime = null;

  @JsonProperty("fallbackUrl")
  private String fallbackUrl = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("status")
  private MicrosoftGraphStatus status = null;

  @JsonProperty("userTimezone")
  private String userTimezone = null;

  @JsonProperty("visualElements")
  private MicrosoftGraphVisualInfo visualElements = null;

  @JsonProperty("historyItems")
  private List<MicrosoftGraphActivityHistoryItem> historyItems = null;

  public MicrosoftGraphUserActivity activationUrl(String activationUrl) {
    this.activationUrl = activationUrl;
    return this;
  }

   /**
   * Required. URL used to launch the activity in the best native experience represented by the appId. Might launch a web-based app if no native app exists.
   * @return activationUrl
  **/
  public String getActivationUrl() {
    return activationUrl;
  }

  public void setActivationUrl(String activationUrl) {
    this.activationUrl = activationUrl;
  }

  public MicrosoftGraphUserActivity activitySourceHost(String activitySourceHost) {
    this.activitySourceHost = activitySourceHost;
    return this;
  }

   /**
   * Required. URL for the domain representing the cross-platform identity mapping for the app. Mapping is stored either as a JSON file hosted on the domain or configurable via Windows Dev Center. The JSON file is named cross-platform-app-identifiers and is hosted at root of your HTTPS domain, either at the top level domain or include a sub domain. For example: https://contoso.com or https://myapp.contoso.com but NOT https://myapp.contoso.com/somepath. You must have a unique file and domain (or sub domain) per cross-platform app identity. For example, a separate file and domain is needed for Word vs. PowerPoint.
   * @return activitySourceHost
  **/
  public String getActivitySourceHost() {
    return activitySourceHost;
  }

  public void setActivitySourceHost(String activitySourceHost) {
    this.activitySourceHost = activitySourceHost;
  }

  public MicrosoftGraphUserActivity appActivityId(String appActivityId) {
    this.appActivityId = appActivityId;
    return this;
  }

   /**
   * Required. The unique activity ID in the context of the app - supplied by caller and immutable thereafter.
   * @return appActivityId
  **/
  public String getAppActivityId() {
    return appActivityId;
  }

  public void setAppActivityId(String appActivityId) {
    this.appActivityId = appActivityId;
  }

  public MicrosoftGraphUserActivity appDisplayName(String appDisplayName) {
    this.appDisplayName = appDisplayName;
    return this;
  }

   /**
   * Optional. Short text description of the app used to generate the activity for use in cases when the app is not installed on the user’s local device.
   * @return appDisplayName
  **/
  public String getAppDisplayName() {
    return appDisplayName;
  }

  public void setAppDisplayName(String appDisplayName) {
    this.appDisplayName = appDisplayName;
  }

  public MicrosoftGraphUserActivity contentInfo(MicrosoftGraphJson contentInfo) {
    this.contentInfo = contentInfo;
    return this;
  }

   /**
   * Get contentInfo
   * @return contentInfo
  **/
  public MicrosoftGraphJson getContentInfo() {
    return contentInfo;
  }

  public void setContentInfo(MicrosoftGraphJson contentInfo) {
    this.contentInfo = contentInfo;
  }

  public MicrosoftGraphUserActivity contentUrl(String contentUrl) {
    this.contentUrl = contentUrl;
    return this;
  }

   /**
   * Optional. Used in the event the content can be rendered outside of a native or web-based app experience (for example, a pointer to an item in an RSS feed).
   * @return contentUrl
  **/
  public String getContentUrl() {
    return contentUrl;
  }

  public void setContentUrl(String contentUrl) {
    this.contentUrl = contentUrl;
  }

  public MicrosoftGraphUserActivity createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Set by the server. DateTime in UTC when the object was created on the server.
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphUserActivity expirationDateTime(OffsetDateTime expirationDateTime) {
    this.expirationDateTime = expirationDateTime;
    return this;
  }

   /**
   * Set by the server. DateTime in UTC when the object expired on the server.
   * @return expirationDateTime
  **/
  public OffsetDateTime getExpirationDateTime() {
    return expirationDateTime;
  }

  public void setExpirationDateTime(OffsetDateTime expirationDateTime) {
    this.expirationDateTime = expirationDateTime;
  }

  public MicrosoftGraphUserActivity fallbackUrl(String fallbackUrl) {
    this.fallbackUrl = fallbackUrl;
    return this;
  }

   /**
   * Optional. URL used to launch the activity in a web-based app, if available.
   * @return fallbackUrl
  **/
  public String getFallbackUrl() {
    return fallbackUrl;
  }

  public void setFallbackUrl(String fallbackUrl) {
    this.fallbackUrl = fallbackUrl;
  }

  public MicrosoftGraphUserActivity lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Set by the server. DateTime in UTC when the object was modified on the server.
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public MicrosoftGraphUserActivity status(MicrosoftGraphStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public MicrosoftGraphStatus getStatus() {
    return status;
  }

  public void setStatus(MicrosoftGraphStatus status) {
    this.status = status;
  }

  public MicrosoftGraphUserActivity userTimezone(String userTimezone) {
    this.userTimezone = userTimezone;
    return this;
  }

   /**
   * Optional. The timezone in which the user&#x27;s device used to generate the activity was located at activity creation time; values supplied as Olson IDs in order to support cross-platform representation.
   * @return userTimezone
  **/
  public String getUserTimezone() {
    return userTimezone;
  }

  public void setUserTimezone(String userTimezone) {
    this.userTimezone = userTimezone;
  }

  public MicrosoftGraphUserActivity visualElements(MicrosoftGraphVisualInfo visualElements) {
    this.visualElements = visualElements;
    return this;
  }

   /**
   * Get visualElements
   * @return visualElements
  **/
  public MicrosoftGraphVisualInfo getVisualElements() {
    return visualElements;
  }

  public void setVisualElements(MicrosoftGraphVisualInfo visualElements) {
    this.visualElements = visualElements;
  }

  public MicrosoftGraphUserActivity historyItems(List<MicrosoftGraphActivityHistoryItem> historyItems) {
    this.historyItems = historyItems;
    return this;
  }

  public MicrosoftGraphUserActivity addHistoryItemsItem(MicrosoftGraphActivityHistoryItem historyItemsItem) {
    if (this.historyItems == null) {
      this.historyItems = new ArrayList<>();
    }
    this.historyItems.add(historyItemsItem);
    return this;
  }

   /**
   * Optional. NavigationProperty/Containment; navigation property to the activity&#x27;s historyItems.
   * @return historyItems
  **/
  public List<MicrosoftGraphActivityHistoryItem> getHistoryItems() {
    return historyItems;
  }

  public void setHistoryItems(List<MicrosoftGraphActivityHistoryItem> historyItems) {
    this.historyItems = historyItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphUserActivity microsoftGraphUserActivity = (MicrosoftGraphUserActivity) o;
    return Objects.equals(this.activationUrl, microsoftGraphUserActivity.activationUrl) &&
        Objects.equals(this.activitySourceHost, microsoftGraphUserActivity.activitySourceHost) &&
        Objects.equals(this.appActivityId, microsoftGraphUserActivity.appActivityId) &&
        Objects.equals(this.appDisplayName, microsoftGraphUserActivity.appDisplayName) &&
        Objects.equals(this.contentInfo, microsoftGraphUserActivity.contentInfo) &&
        Objects.equals(this.contentUrl, microsoftGraphUserActivity.contentUrl) &&
        Objects.equals(this.createdDateTime, microsoftGraphUserActivity.createdDateTime) &&
        Objects.equals(this.expirationDateTime, microsoftGraphUserActivity.expirationDateTime) &&
        Objects.equals(this.fallbackUrl, microsoftGraphUserActivity.fallbackUrl) &&
        Objects.equals(this.lastModifiedDateTime, microsoftGraphUserActivity.lastModifiedDateTime) &&
        Objects.equals(this.status, microsoftGraphUserActivity.status) &&
        Objects.equals(this.userTimezone, microsoftGraphUserActivity.userTimezone) &&
        Objects.equals(this.visualElements, microsoftGraphUserActivity.visualElements) &&
        Objects.equals(this.historyItems, microsoftGraphUserActivity.historyItems) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activationUrl, activitySourceHost, appActivityId, appDisplayName, contentInfo, contentUrl, createdDateTime, expirationDateTime, fallbackUrl, lastModifiedDateTime, status, userTimezone, visualElements, historyItems, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphUserActivity {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    activationUrl: ").append(toIndentedString(activationUrl)).append("\n");
    sb.append("    activitySourceHost: ").append(toIndentedString(activitySourceHost)).append("\n");
    sb.append("    appActivityId: ").append(toIndentedString(appActivityId)).append("\n");
    sb.append("    appDisplayName: ").append(toIndentedString(appDisplayName)).append("\n");
    sb.append("    contentInfo: ").append(toIndentedString(contentInfo)).append("\n");
    sb.append("    contentUrl: ").append(toIndentedString(contentUrl)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    expirationDateTime: ").append(toIndentedString(expirationDateTime)).append("\n");
    sb.append("    fallbackUrl: ").append(toIndentedString(fallbackUrl)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userTimezone: ").append(toIndentedString(userTimezone)).append("\n");
    sb.append("    visualElements: ").append(toIndentedString(visualElements)).append("\n");
    sb.append("    historyItems: ").append(toIndentedString(historyItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
