/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphFile;
import com.microsoft.graph.MicrosoftGraphFileSystemInfo;
import com.microsoft.graph.MicrosoftGraphFolder;
import com.microsoft.graph.MicrosoftGraphIdentitySet;
import com.microsoft.graph.MicrosoftGraphImage;
import com.microsoft.graph.MicrosoftGraphItemReference;
import com.microsoft.graph.MicrosoftGraphPackage;
import com.microsoft.graph.MicrosoftGraphShared;
import com.microsoft.graph.MicrosoftGraphSharepointIds;
import com.microsoft.graph.MicrosoftGraphSpecialFolder;
import com.microsoft.graph.MicrosoftGraphVideo;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphRemoteItem
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphRemoteItem {
  @JsonProperty("createdBy")
  private MicrosoftGraphIdentitySet createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("file")
  private MicrosoftGraphFile file = null;

  @JsonProperty("fileSystemInfo")
  private MicrosoftGraphFileSystemInfo fileSystemInfo = null;

  @JsonProperty("folder")
  private MicrosoftGraphFolder folder = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("image")
  private MicrosoftGraphImage image = null;

  @JsonProperty("lastModifiedBy")
  private MicrosoftGraphIdentitySet lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("package")
  private MicrosoftGraphPackage _package = null;

  @JsonProperty("parentReference")
  private MicrosoftGraphItemReference parentReference = null;

  @JsonProperty("shared")
  private MicrosoftGraphShared shared = null;

  @JsonProperty("sharepointIds")
  private MicrosoftGraphSharepointIds sharepointIds = null;

  @JsonProperty("size")
  private Long size = null;

  @JsonProperty("specialFolder")
  private MicrosoftGraphSpecialFolder specialFolder = null;

  @JsonProperty("video")
  private MicrosoftGraphVideo video = null;

  @JsonProperty("webDavUrl")
  private String webDavUrl = null;

  @JsonProperty("webUrl")
  private String webUrl = null;

  public MicrosoftGraphRemoteItem createdBy(MicrosoftGraphIdentitySet createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public MicrosoftGraphIdentitySet getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(MicrosoftGraphIdentitySet createdBy) {
    this.createdBy = createdBy;
  }

  public MicrosoftGraphRemoteItem createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Date and time of item creation. Read-only.
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphRemoteItem file(MicrosoftGraphFile file) {
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  public MicrosoftGraphFile getFile() {
    return file;
  }

  public void setFile(MicrosoftGraphFile file) {
    this.file = file;
  }

  public MicrosoftGraphRemoteItem fileSystemInfo(MicrosoftGraphFileSystemInfo fileSystemInfo) {
    this.fileSystemInfo = fileSystemInfo;
    return this;
  }

   /**
   * Get fileSystemInfo
   * @return fileSystemInfo
  **/
  public MicrosoftGraphFileSystemInfo getFileSystemInfo() {
    return fileSystemInfo;
  }

  public void setFileSystemInfo(MicrosoftGraphFileSystemInfo fileSystemInfo) {
    this.fileSystemInfo = fileSystemInfo;
  }

  public MicrosoftGraphRemoteItem folder(MicrosoftGraphFolder folder) {
    this.folder = folder;
    return this;
  }

   /**
   * Get folder
   * @return folder
  **/
  public MicrosoftGraphFolder getFolder() {
    return folder;
  }

  public void setFolder(MicrosoftGraphFolder folder) {
    this.folder = folder;
  }

  public MicrosoftGraphRemoteItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the remote item in its drive. Read-only.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MicrosoftGraphRemoteItem image(MicrosoftGraphImage image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  public MicrosoftGraphImage getImage() {
    return image;
  }

  public void setImage(MicrosoftGraphImage image) {
    this.image = image;
  }

  public MicrosoftGraphRemoteItem lastModifiedBy(MicrosoftGraphIdentitySet lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public MicrosoftGraphIdentitySet getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(MicrosoftGraphIdentitySet lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public MicrosoftGraphRemoteItem lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Date and time the item was last modified. Read-only.
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public MicrosoftGraphRemoteItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Optional. Filename of the remote item. Read-only.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftGraphRemoteItem _package(MicrosoftGraphPackage _package) {
    this._package = _package;
    return this;
  }

   /**
   * Get _package
   * @return _package
  **/
  public MicrosoftGraphPackage getPackage() {
    return _package;
  }

  public void setPackage(MicrosoftGraphPackage _package) {
    this._package = _package;
  }

  public MicrosoftGraphRemoteItem parentReference(MicrosoftGraphItemReference parentReference) {
    this.parentReference = parentReference;
    return this;
  }

   /**
   * Get parentReference
   * @return parentReference
  **/
  public MicrosoftGraphItemReference getParentReference() {
    return parentReference;
  }

  public void setParentReference(MicrosoftGraphItemReference parentReference) {
    this.parentReference = parentReference;
  }

  public MicrosoftGraphRemoteItem shared(MicrosoftGraphShared shared) {
    this.shared = shared;
    return this;
  }

   /**
   * Get shared
   * @return shared
  **/
  public MicrosoftGraphShared getShared() {
    return shared;
  }

  public void setShared(MicrosoftGraphShared shared) {
    this.shared = shared;
  }

  public MicrosoftGraphRemoteItem sharepointIds(MicrosoftGraphSharepointIds sharepointIds) {
    this.sharepointIds = sharepointIds;
    return this;
  }

   /**
   * Get sharepointIds
   * @return sharepointIds
  **/
  public MicrosoftGraphSharepointIds getSharepointIds() {
    return sharepointIds;
  }

  public void setSharepointIds(MicrosoftGraphSharepointIds sharepointIds) {
    this.sharepointIds = sharepointIds;
  }

  public MicrosoftGraphRemoteItem size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Size of the remote item. Read-only.
   * @return size
  **/
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public MicrosoftGraphRemoteItem specialFolder(MicrosoftGraphSpecialFolder specialFolder) {
    this.specialFolder = specialFolder;
    return this;
  }

   /**
   * Get specialFolder
   * @return specialFolder
  **/
  public MicrosoftGraphSpecialFolder getSpecialFolder() {
    return specialFolder;
  }

  public void setSpecialFolder(MicrosoftGraphSpecialFolder specialFolder) {
    this.specialFolder = specialFolder;
  }

  public MicrosoftGraphRemoteItem video(MicrosoftGraphVideo video) {
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  public MicrosoftGraphVideo getVideo() {
    return video;
  }

  public void setVideo(MicrosoftGraphVideo video) {
    this.video = video;
  }

  public MicrosoftGraphRemoteItem webDavUrl(String webDavUrl) {
    this.webDavUrl = webDavUrl;
    return this;
  }

   /**
   * DAV compatible URL for the item.
   * @return webDavUrl
  **/
  public String getWebDavUrl() {
    return webDavUrl;
  }

  public void setWebDavUrl(String webDavUrl) {
    this.webDavUrl = webDavUrl;
  }

  public MicrosoftGraphRemoteItem webUrl(String webUrl) {
    this.webUrl = webUrl;
    return this;
  }

   /**
   * URL that displays the resource in the browser. Read-only.
   * @return webUrl
  **/
  public String getWebUrl() {
    return webUrl;
  }

  public void setWebUrl(String webUrl) {
    this.webUrl = webUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphRemoteItem microsoftGraphRemoteItem = (MicrosoftGraphRemoteItem) o;
    return Objects.equals(this.createdBy, microsoftGraphRemoteItem.createdBy) &&
        Objects.equals(this.createdDateTime, microsoftGraphRemoteItem.createdDateTime) &&
        Objects.equals(this.file, microsoftGraphRemoteItem.file) &&
        Objects.equals(this.fileSystemInfo, microsoftGraphRemoteItem.fileSystemInfo) &&
        Objects.equals(this.folder, microsoftGraphRemoteItem.folder) &&
        Objects.equals(this.id, microsoftGraphRemoteItem.id) &&
        Objects.equals(this.image, microsoftGraphRemoteItem.image) &&
        Objects.equals(this.lastModifiedBy, microsoftGraphRemoteItem.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, microsoftGraphRemoteItem.lastModifiedDateTime) &&
        Objects.equals(this.name, microsoftGraphRemoteItem.name) &&
        Objects.equals(this._package, microsoftGraphRemoteItem._package) &&
        Objects.equals(this.parentReference, microsoftGraphRemoteItem.parentReference) &&
        Objects.equals(this.shared, microsoftGraphRemoteItem.shared) &&
        Objects.equals(this.sharepointIds, microsoftGraphRemoteItem.sharepointIds) &&
        Objects.equals(this.size, microsoftGraphRemoteItem.size) &&
        Objects.equals(this.specialFolder, microsoftGraphRemoteItem.specialFolder) &&
        Objects.equals(this.video, microsoftGraphRemoteItem.video) &&
        Objects.equals(this.webDavUrl, microsoftGraphRemoteItem.webDavUrl) &&
        Objects.equals(this.webUrl, microsoftGraphRemoteItem.webUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDateTime, file, fileSystemInfo, folder, id, image, lastModifiedBy, lastModifiedDateTime, name, _package, parentReference, shared, sharepointIds, size, specialFolder, video, webDavUrl, webUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphRemoteItem {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    fileSystemInfo: ").append(toIndentedString(fileSystemInfo)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    parentReference: ").append(toIndentedString(parentReference)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    sharepointIds: ").append(toIndentedString(sharepointIds)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    specialFolder: ").append(toIndentedString(specialFolder)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    webDavUrl: ").append(toIndentedString(webDavUrl)).append("\n");
    sb.append("    webUrl: ").append(toIndentedString(webUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
