/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphChannelIdentity
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphChannelIdentity {
  @JsonProperty("channelId")
  private String channelId = null;

  @JsonProperty("teamId")
  private String teamId = null;

  public MicrosoftGraphChannelIdentity channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The identity of the channel in which the message was posted.
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public MicrosoftGraphChannelIdentity teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * The identity of the team in which the message was posted.
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphChannelIdentity microsoftGraphChannelIdentity = (MicrosoftGraphChannelIdentity) o;
    return Objects.equals(this.channelId, microsoftGraphChannelIdentity.channelId) &&
        Objects.equals(this.teamId, microsoftGraphChannelIdentity.teamId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, teamId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphChannelIdentity {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
