/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphTermStoreRelationType;
import com.microsoft.graph.MicrosoftGraphTermStoreSet;
import com.microsoft.graph.MicrosoftGraphTermStoreTerm;

/**
 * MicrosoftGraphTermStoreRelation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTermStoreRelation extends MicrosoftGraphEntity {
  @JsonProperty("relationship")
  private MicrosoftGraphTermStoreRelationType relationship = null;

  @JsonProperty("fromTerm")
  private MicrosoftGraphTermStoreTerm fromTerm = null;

  @JsonProperty("set")
  private MicrosoftGraphTermStoreSet set = null;

  @JsonProperty("toTerm")
  private MicrosoftGraphTermStoreTerm toTerm = null;

  public MicrosoftGraphTermStoreRelation relationship(MicrosoftGraphTermStoreRelationType relationship) {
    this.relationship = relationship;
    return this;
  }

   /**
   * Get relationship
   * @return relationship
  **/
  public MicrosoftGraphTermStoreRelationType getRelationship() {
    return relationship;
  }

  public void setRelationship(MicrosoftGraphTermStoreRelationType relationship) {
    this.relationship = relationship;
  }

  public MicrosoftGraphTermStoreRelation fromTerm(MicrosoftGraphTermStoreTerm fromTerm) {
    this.fromTerm = fromTerm;
    return this;
  }

   /**
   * Get fromTerm
   * @return fromTerm
  **/
  public MicrosoftGraphTermStoreTerm getFromTerm() {
    return fromTerm;
  }

  public void setFromTerm(MicrosoftGraphTermStoreTerm fromTerm) {
    this.fromTerm = fromTerm;
  }

  public MicrosoftGraphTermStoreRelation set(MicrosoftGraphTermStoreSet set) {
    this.set = set;
    return this;
  }

   /**
   * Get set
   * @return set
  **/
  public MicrosoftGraphTermStoreSet getSet() {
    return set;
  }

  public void setSet(MicrosoftGraphTermStoreSet set) {
    this.set = set;
  }

  public MicrosoftGraphTermStoreRelation toTerm(MicrosoftGraphTermStoreTerm toTerm) {
    this.toTerm = toTerm;
    return this;
  }

   /**
   * Get toTerm
   * @return toTerm
  **/
  public MicrosoftGraphTermStoreTerm getToTerm() {
    return toTerm;
  }

  public void setToTerm(MicrosoftGraphTermStoreTerm toTerm) {
    this.toTerm = toTerm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTermStoreRelation microsoftGraphTermStoreRelation = (MicrosoftGraphTermStoreRelation) o;
    return Objects.equals(this.relationship, microsoftGraphTermStoreRelation.relationship) &&
        Objects.equals(this.fromTerm, microsoftGraphTermStoreRelation.fromTerm) &&
        Objects.equals(this.set, microsoftGraphTermStoreRelation.set) &&
        Objects.equals(this.toTerm, microsoftGraphTermStoreRelation.toTerm) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relationship, fromTerm, set, toTerm, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTermStoreRelation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    relationship: ").append(toIndentedString(relationship)).append("\n");
    sb.append("    fromTerm: ").append(toIndentedString(fromTerm)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("    toTerm: ").append(toIndentedString(toTerm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
