/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphPhysicalAddress
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphPhysicalAddress {
  @JsonProperty("city")
  private String city = null;

  @JsonProperty("countryOrRegion")
  private String countryOrRegion = null;

  @JsonProperty("postalCode")
  private String postalCode = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("street")
  private String street = null;

  public MicrosoftGraphPhysicalAddress city(String city) {
    this.city = city;
    return this;
  }

   /**
   * The city.
   * @return city
  **/
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public MicrosoftGraphPhysicalAddress countryOrRegion(String countryOrRegion) {
    this.countryOrRegion = countryOrRegion;
    return this;
  }

   /**
   * The country or region. It&#x27;s a free-format string value, for example, &#x27;United States&#x27;.
   * @return countryOrRegion
  **/
  public String getCountryOrRegion() {
    return countryOrRegion;
  }

  public void setCountryOrRegion(String countryOrRegion) {
    this.countryOrRegion = countryOrRegion;
  }

  public MicrosoftGraphPhysicalAddress postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The postal code.
   * @return postalCode
  **/
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public MicrosoftGraphPhysicalAddress state(String state) {
    this.state = state;
    return this;
  }

   /**
   * The state.
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public MicrosoftGraphPhysicalAddress street(String street) {
    this.street = street;
    return this;
  }

   /**
   * The street.
   * @return street
  **/
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphPhysicalAddress microsoftGraphPhysicalAddress = (MicrosoftGraphPhysicalAddress) o;
    return Objects.equals(this.city, microsoftGraphPhysicalAddress.city) &&
        Objects.equals(this.countryOrRegion, microsoftGraphPhysicalAddress.countryOrRegion) &&
        Objects.equals(this.postalCode, microsoftGraphPhysicalAddress.postalCode) &&
        Objects.equals(this.state, microsoftGraphPhysicalAddress.state) &&
        Objects.equals(this.street, microsoftGraphPhysicalAddress.street);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, countryOrRegion, postalCode, state, street);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphPhysicalAddress {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    countryOrRegion: ").append(toIndentedString(countryOrRegion)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
