/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphWorkbookChartFill;
import com.microsoft.graph.MicrosoftGraphWorkbookChartLineFormat;

/**
 * MicrosoftGraphWorkbookChartSeriesFormat
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkbookChartSeriesFormat extends MicrosoftGraphEntity {
  @JsonProperty("fill")
  private MicrosoftGraphWorkbookChartFill fill = null;

  @JsonProperty("line")
  private MicrosoftGraphWorkbookChartLineFormat line = null;

  public MicrosoftGraphWorkbookChartSeriesFormat fill(MicrosoftGraphWorkbookChartFill fill) {
    this.fill = fill;
    return this;
  }

   /**
   * Get fill
   * @return fill
  **/
  public MicrosoftGraphWorkbookChartFill getFill() {
    return fill;
  }

  public void setFill(MicrosoftGraphWorkbookChartFill fill) {
    this.fill = fill;
  }

  public MicrosoftGraphWorkbookChartSeriesFormat line(MicrosoftGraphWorkbookChartLineFormat line) {
    this.line = line;
    return this;
  }

   /**
   * Get line
   * @return line
  **/
  public MicrosoftGraphWorkbookChartLineFormat getLine() {
    return line;
  }

  public void setLine(MicrosoftGraphWorkbookChartLineFormat line) {
    this.line = line;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkbookChartSeriesFormat microsoftGraphWorkbookChartSeriesFormat = (MicrosoftGraphWorkbookChartSeriesFormat) o;
    return Objects.equals(this.fill, microsoftGraphWorkbookChartSeriesFormat.fill) &&
        Objects.equals(this.line, microsoftGraphWorkbookChartSeriesFormat.line) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fill, line, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkbookChartSeriesFormat {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    fill: ").append(toIndentedString(fill)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
