/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphFileSystemInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphFileSystemInfo {
  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("lastAccessedDateTime")
  private OffsetDateTime lastAccessedDateTime = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  public MicrosoftGraphFileSystemInfo createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * The UTC date and time the file was created on a client.
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphFileSystemInfo lastAccessedDateTime(OffsetDateTime lastAccessedDateTime) {
    this.lastAccessedDateTime = lastAccessedDateTime;
    return this;
  }

   /**
   * The UTC date and time the file was last accessed. Available for the recent file list only.
   * @return lastAccessedDateTime
  **/
  public OffsetDateTime getLastAccessedDateTime() {
    return lastAccessedDateTime;
  }

  public void setLastAccessedDateTime(OffsetDateTime lastAccessedDateTime) {
    this.lastAccessedDateTime = lastAccessedDateTime;
  }

  public MicrosoftGraphFileSystemInfo lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * The UTC date and time the file was last modified on a client.
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphFileSystemInfo microsoftGraphFileSystemInfo = (MicrosoftGraphFileSystemInfo) o;
    return Objects.equals(this.createdDateTime, microsoftGraphFileSystemInfo.createdDateTime) &&
        Objects.equals(this.lastAccessedDateTime, microsoftGraphFileSystemInfo.lastAccessedDateTime) &&
        Objects.equals(this.lastModifiedDateTime, microsoftGraphFileSystemInfo.lastModifiedDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdDateTime, lastAccessedDateTime, lastModifiedDateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphFileSystemInfo {\n");
    
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    lastAccessedDateTime: ").append(toIndentedString(lastAccessedDateTime)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
