/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphTeamSummary
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTeamSummary {
  @JsonProperty("guestsCount")
  private Integer guestsCount = null;

  @JsonProperty("membersCount")
  private Integer membersCount = null;

  @JsonProperty("ownersCount")
  private Integer ownersCount = null;

  public MicrosoftGraphTeamSummary guestsCount(Integer guestsCount) {
    this.guestsCount = guestsCount;
    return this;
  }

   /**
   * Get guestsCount
   * minimum: -2147483648
   * maximum: 2147483647
   * @return guestsCount
  **/
  public Integer getGuestsCount() {
    return guestsCount;
  }

  public void setGuestsCount(Integer guestsCount) {
    this.guestsCount = guestsCount;
  }

  public MicrosoftGraphTeamSummary membersCount(Integer membersCount) {
    this.membersCount = membersCount;
    return this;
  }

   /**
   * Get membersCount
   * minimum: -2147483648
   * maximum: 2147483647
   * @return membersCount
  **/
  public Integer getMembersCount() {
    return membersCount;
  }

  public void setMembersCount(Integer membersCount) {
    this.membersCount = membersCount;
  }

  public MicrosoftGraphTeamSummary ownersCount(Integer ownersCount) {
    this.ownersCount = ownersCount;
    return this;
  }

   /**
   * Get ownersCount
   * minimum: -2147483648
   * maximum: 2147483647
   * @return ownersCount
  **/
  public Integer getOwnersCount() {
    return ownersCount;
  }

  public void setOwnersCount(Integer ownersCount) {
    this.ownersCount = ownersCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTeamSummary microsoftGraphTeamSummary = (MicrosoftGraphTeamSummary) o;
    return Objects.equals(this.guestsCount, microsoftGraphTeamSummary.guestsCount) &&
        Objects.equals(this.membersCount, microsoftGraphTeamSummary.membersCount) &&
        Objects.equals(this.ownersCount, microsoftGraphTeamSummary.ownersCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guestsCount, membersCount, ownersCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTeamSummary {\n");
    
    sb.append("    guestsCount: ").append(toIndentedString(guestsCount)).append("\n");
    sb.append("    membersCount: ").append(toIndentedString(membersCount)).append("\n");
    sb.append("    ownersCount: ").append(toIndentedString(ownersCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
