/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;

/**
 * MicrosoftGraphOAuth2PermissionGrant
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphOAuth2PermissionGrant extends MicrosoftGraphEntity {
  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("consentType")
  private String consentType = null;

  @JsonProperty("principalId")
  private String principalId = null;

  @JsonProperty("resourceId")
  private String resourceId = null;

  @JsonProperty("scope")
  private String scope = null;

  public MicrosoftGraphOAuth2PermissionGrant clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * The id of the client service principal for the application which is authorized to act on behalf of a signed-in user when accessing an API. Required. Supports $filter (eq only).
   * @return clientId
  **/
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public MicrosoftGraphOAuth2PermissionGrant consentType(String consentType) {
    this.consentType = consentType;
    return this;
  }

   /**
   * Indicates if authorization is granted for the client application to impersonate all users or only a specific user. AllPrincipals indicates authorization to impersonate all users. Principal indicates authorization to impersonate a specific user. Consent on behalf of all users can be granted by an administrator. Non-admin users may be authorized to consent on behalf of themselves in some cases, for some delegated permissions. Required. Supports $filter (eq only).
   * @return consentType
  **/
  public String getConsentType() {
    return consentType;
  }

  public void setConsentType(String consentType) {
    this.consentType = consentType;
  }

  public MicrosoftGraphOAuth2PermissionGrant principalId(String principalId) {
    this.principalId = principalId;
    return this;
  }

   /**
   * The id of the user on behalf of whom the client is authorized to access the resource, when consentType is Principal. If consentType is AllPrincipals this value is null. Required when consentType is Principal. Supports $filter (eq only).
   * @return principalId
  **/
  public String getPrincipalId() {
    return principalId;
  }

  public void setPrincipalId(String principalId) {
    this.principalId = principalId;
  }

  public MicrosoftGraphOAuth2PermissionGrant resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * The id of the resource service principal to which access is authorized. This identifies the API which the client is authorized to attempt to call on behalf of a signed-in user. Supports $filter (eq only).
   * @return resourceId
  **/
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  public MicrosoftGraphOAuth2PermissionGrant scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * A space-separated list of the claim values for delegated permissions which should be included in access tokens for the resource application (the API). For example, openid User.Read GroupMember.Read.All. Each claim value should match the value field of one of the delegated permissions defined by the API, listed in the oauth2PermissionScopes property of the resource service principal. Must not exceed 3850 characters in length.
   * @return scope
  **/
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphOAuth2PermissionGrant microsoftGraphOAuth2PermissionGrant = (MicrosoftGraphOAuth2PermissionGrant) o;
    return Objects.equals(this.clientId, microsoftGraphOAuth2PermissionGrant.clientId) &&
        Objects.equals(this.consentType, microsoftGraphOAuth2PermissionGrant.consentType) &&
        Objects.equals(this.principalId, microsoftGraphOAuth2PermissionGrant.principalId) &&
        Objects.equals(this.resourceId, microsoftGraphOAuth2PermissionGrant.resourceId) &&
        Objects.equals(this.scope, microsoftGraphOAuth2PermissionGrant.scope) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, consentType, principalId, resourceId, scope, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphOAuth2PermissionGrant {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    consentType: ").append(toIndentedString(consentType)).append("\n");
    sb.append("    principalId: ").append(toIndentedString(principalId)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
