/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphODataErrorsErrorDetails;
import com.microsoft.graph.MicrosoftGraphODataErrorsInnerError;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphODataErrorsMainError
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphODataErrorsMainError {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("target")
  private String target = null;

  @JsonProperty("details")
  private List<MicrosoftGraphODataErrorsErrorDetails> details = null;

  @JsonProperty("innererror")
  private MicrosoftGraphODataErrorsInnerError innererror = null;

  public MicrosoftGraphODataErrorsMainError code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public MicrosoftGraphODataErrorsMainError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public MicrosoftGraphODataErrorsMainError target(String target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }

  public MicrosoftGraphODataErrorsMainError details(List<MicrosoftGraphODataErrorsErrorDetails> details) {
    this.details = details;
    return this;
  }

  public MicrosoftGraphODataErrorsMainError addDetailsItem(MicrosoftGraphODataErrorsErrorDetails detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  public List<MicrosoftGraphODataErrorsErrorDetails> getDetails() {
    return details;
  }

  public void setDetails(List<MicrosoftGraphODataErrorsErrorDetails> details) {
    this.details = details;
  }

  public MicrosoftGraphODataErrorsMainError innererror(MicrosoftGraphODataErrorsInnerError innererror) {
    this.innererror = innererror;
    return this;
  }

   /**
   * Get innererror
   * @return innererror
  **/
  public MicrosoftGraphODataErrorsInnerError getInnererror() {
    return innererror;
  }

  public void setInnererror(MicrosoftGraphODataErrorsInnerError innererror) {
    this.innererror = innererror;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphODataErrorsMainError microsoftGraphODataErrorsMainError = (MicrosoftGraphODataErrorsMainError) o;
    return Objects.equals(this.code, microsoftGraphODataErrorsMainError.code) &&
        Objects.equals(this.message, microsoftGraphODataErrorsMainError.message) &&
        Objects.equals(this.target, microsoftGraphODataErrorsMainError.target) &&
        Objects.equals(this.details, microsoftGraphODataErrorsMainError.details) &&
        Objects.equals(this.innererror, microsoftGraphODataErrorsMainError.innererror);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, target, details, innererror);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphODataErrorsMainError {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    innererror: ").append(toIndentedString(innererror)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
