/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphTermStoreLocalizedLabel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTermStoreLocalizedLabel {
  @JsonProperty("isDefault")
  private Boolean isDefault = null;

  @JsonProperty("languageTag")
  private String languageTag = null;

  @JsonProperty("name")
  private String name = null;

  public MicrosoftGraphTermStoreLocalizedLabel isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Indicates whether the label is the default label.
   * @return isDefault
  **/
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public MicrosoftGraphTermStoreLocalizedLabel languageTag(String languageTag) {
    this.languageTag = languageTag;
    return this;
  }

   /**
   * The language tag for the label.
   * @return languageTag
  **/
  public String getLanguageTag() {
    return languageTag;
  }

  public void setLanguageTag(String languageTag) {
    this.languageTag = languageTag;
  }

  public MicrosoftGraphTermStoreLocalizedLabel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the label.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTermStoreLocalizedLabel microsoftGraphTermStoreLocalizedLabel = (MicrosoftGraphTermStoreLocalizedLabel) o;
    return Objects.equals(this.isDefault, microsoftGraphTermStoreLocalizedLabel.isDefault) &&
        Objects.equals(this.languageTag, microsoftGraphTermStoreLocalizedLabel.languageTag) &&
        Objects.equals(this.name, microsoftGraphTermStoreLocalizedLabel.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isDefault, languageTag, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTermStoreLocalizedLabel {\n");
    
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    languageTag: ").append(toIndentedString(languageTag)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
