/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphAutomaticRepliesSetting;
import com.microsoft.graph.MicrosoftGraphDelegateMeetingMessageDeliveryOptions;
import com.microsoft.graph.MicrosoftGraphLocaleInfo;
import com.microsoft.graph.MicrosoftGraphUserPurpose;
import com.microsoft.graph.MicrosoftGraphWorkingHours;

/**
 * MicrosoftGraphMailboxSettings
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphMailboxSettings {
  @JsonProperty("archiveFolder")
  private String archiveFolder = null;

  @JsonProperty("automaticRepliesSetting")
  private MicrosoftGraphAutomaticRepliesSetting automaticRepliesSetting = null;

  @JsonProperty("dateFormat")
  private String dateFormat = null;

  @JsonProperty("delegateMeetingMessageDeliveryOptions")
  private MicrosoftGraphDelegateMeetingMessageDeliveryOptions delegateMeetingMessageDeliveryOptions = null;

  @JsonProperty("language")
  private MicrosoftGraphLocaleInfo language = null;

  @JsonProperty("timeFormat")
  private String timeFormat = null;

  @JsonProperty("timeZone")
  private String timeZone = null;

  @JsonProperty("userPurpose")
  private MicrosoftGraphUserPurpose userPurpose = null;

  @JsonProperty("workingHours")
  private MicrosoftGraphWorkingHours workingHours = null;

  public MicrosoftGraphMailboxSettings archiveFolder(String archiveFolder) {
    this.archiveFolder = archiveFolder;
    return this;
  }

   /**
   * Folder ID of an archive folder for the user.
   * @return archiveFolder
  **/
  public String getArchiveFolder() {
    return archiveFolder;
  }

  public void setArchiveFolder(String archiveFolder) {
    this.archiveFolder = archiveFolder;
  }

  public MicrosoftGraphMailboxSettings automaticRepliesSetting(MicrosoftGraphAutomaticRepliesSetting automaticRepliesSetting) {
    this.automaticRepliesSetting = automaticRepliesSetting;
    return this;
  }

   /**
   * Get automaticRepliesSetting
   * @return automaticRepliesSetting
  **/
  public MicrosoftGraphAutomaticRepliesSetting getAutomaticRepliesSetting() {
    return automaticRepliesSetting;
  }

  public void setAutomaticRepliesSetting(MicrosoftGraphAutomaticRepliesSetting automaticRepliesSetting) {
    this.automaticRepliesSetting = automaticRepliesSetting;
  }

  public MicrosoftGraphMailboxSettings dateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * The date format for the user&#x27;s mailbox.
   * @return dateFormat
  **/
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }

  public MicrosoftGraphMailboxSettings delegateMeetingMessageDeliveryOptions(MicrosoftGraphDelegateMeetingMessageDeliveryOptions delegateMeetingMessageDeliveryOptions) {
    this.delegateMeetingMessageDeliveryOptions = delegateMeetingMessageDeliveryOptions;
    return this;
  }

   /**
   * Get delegateMeetingMessageDeliveryOptions
   * @return delegateMeetingMessageDeliveryOptions
  **/
  public MicrosoftGraphDelegateMeetingMessageDeliveryOptions getDelegateMeetingMessageDeliveryOptions() {
    return delegateMeetingMessageDeliveryOptions;
  }

  public void setDelegateMeetingMessageDeliveryOptions(MicrosoftGraphDelegateMeetingMessageDeliveryOptions delegateMeetingMessageDeliveryOptions) {
    this.delegateMeetingMessageDeliveryOptions = delegateMeetingMessageDeliveryOptions;
  }

  public MicrosoftGraphMailboxSettings language(MicrosoftGraphLocaleInfo language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  public MicrosoftGraphLocaleInfo getLanguage() {
    return language;
  }

  public void setLanguage(MicrosoftGraphLocaleInfo language) {
    this.language = language;
  }

  public MicrosoftGraphMailboxSettings timeFormat(String timeFormat) {
    this.timeFormat = timeFormat;
    return this;
  }

   /**
   * The time format for the user&#x27;s mailbox.
   * @return timeFormat
  **/
  public String getTimeFormat() {
    return timeFormat;
  }

  public void setTimeFormat(String timeFormat) {
    this.timeFormat = timeFormat;
  }

  public MicrosoftGraphMailboxSettings timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * The default time zone for the user&#x27;s mailbox.
   * @return timeZone
  **/
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public MicrosoftGraphMailboxSettings userPurpose(MicrosoftGraphUserPurpose userPurpose) {
    this.userPurpose = userPurpose;
    return this;
  }

   /**
   * Get userPurpose
   * @return userPurpose
  **/
  public MicrosoftGraphUserPurpose getUserPurpose() {
    return userPurpose;
  }

  public void setUserPurpose(MicrosoftGraphUserPurpose userPurpose) {
    this.userPurpose = userPurpose;
  }

  public MicrosoftGraphMailboxSettings workingHours(MicrosoftGraphWorkingHours workingHours) {
    this.workingHours = workingHours;
    return this;
  }

   /**
   * Get workingHours
   * @return workingHours
  **/
  public MicrosoftGraphWorkingHours getWorkingHours() {
    return workingHours;
  }

  public void setWorkingHours(MicrosoftGraphWorkingHours workingHours) {
    this.workingHours = workingHours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphMailboxSettings microsoftGraphMailboxSettings = (MicrosoftGraphMailboxSettings) o;
    return Objects.equals(this.archiveFolder, microsoftGraphMailboxSettings.archiveFolder) &&
        Objects.equals(this.automaticRepliesSetting, microsoftGraphMailboxSettings.automaticRepliesSetting) &&
        Objects.equals(this.dateFormat, microsoftGraphMailboxSettings.dateFormat) &&
        Objects.equals(this.delegateMeetingMessageDeliveryOptions, microsoftGraphMailboxSettings.delegateMeetingMessageDeliveryOptions) &&
        Objects.equals(this.language, microsoftGraphMailboxSettings.language) &&
        Objects.equals(this.timeFormat, microsoftGraphMailboxSettings.timeFormat) &&
        Objects.equals(this.timeZone, microsoftGraphMailboxSettings.timeZone) &&
        Objects.equals(this.userPurpose, microsoftGraphMailboxSettings.userPurpose) &&
        Objects.equals(this.workingHours, microsoftGraphMailboxSettings.workingHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archiveFolder, automaticRepliesSetting, dateFormat, delegateMeetingMessageDeliveryOptions, language, timeFormat, timeZone, userPurpose, workingHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphMailboxSettings {\n");
    
    sb.append("    archiveFolder: ").append(toIndentedString(archiveFolder)).append("\n");
    sb.append("    automaticRepliesSetting: ").append(toIndentedString(automaticRepliesSetting)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    delegateMeetingMessageDeliveryOptions: ").append(toIndentedString(delegateMeetingMessageDeliveryOptions)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    timeFormat: ").append(toIndentedString(timeFormat)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    userPurpose: ").append(toIndentedString(userPurpose)).append("\n");
    sb.append("    workingHours: ").append(toIndentedString(workingHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
