/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphIdentitySet;
import com.microsoft.graph.MicrosoftGraphNotebookLinks;
import com.microsoft.graph.MicrosoftGraphOnenoteEntityHierarchyModel;
import com.microsoft.graph.MicrosoftGraphOnenoteSection;
import com.microsoft.graph.MicrosoftGraphOnenoteUserRole;
import com.microsoft.graph.MicrosoftGraphSectionGroup;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphNotebook
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphNotebook extends MicrosoftGraphOnenoteEntityHierarchyModel {
  @JsonProperty("isDefault")
  private Boolean isDefault = null;

  @JsonProperty("isShared")
  private Boolean isShared = null;

  @JsonProperty("links")
  private MicrosoftGraphNotebookLinks links = null;

  @JsonProperty("sectionGroupsUrl")
  private String sectionGroupsUrl = null;

  @JsonProperty("sectionsUrl")
  private String sectionsUrl = null;

  @JsonProperty("userRole")
  private MicrosoftGraphOnenoteUserRole userRole = null;

  @JsonProperty("sectionGroups")
  private List<MicrosoftGraphSectionGroup> sectionGroups = null;

  @JsonProperty("sections")
  private List<MicrosoftGraphOnenoteSection> sections = null;

  public MicrosoftGraphNotebook isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Indicates whether this is the user&#x27;s default notebook. Read-only.
   * @return isDefault
  **/
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public MicrosoftGraphNotebook isShared(Boolean isShared) {
    this.isShared = isShared;
    return this;
  }

   /**
   * Indicates whether the notebook is shared. If true, the contents of the notebook can be seen by people other than the owner. Read-only.
   * @return isShared
  **/
  public Boolean isIsShared() {
    return isShared;
  }

  public void setIsShared(Boolean isShared) {
    this.isShared = isShared;
  }

  public MicrosoftGraphNotebook links(MicrosoftGraphNotebookLinks links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  public MicrosoftGraphNotebookLinks getLinks() {
    return links;
  }

  public void setLinks(MicrosoftGraphNotebookLinks links) {
    this.links = links;
  }

  public MicrosoftGraphNotebook sectionGroupsUrl(String sectionGroupsUrl) {
    this.sectionGroupsUrl = sectionGroupsUrl;
    return this;
  }

   /**
   * The URL for the sectionGroups navigation property, which returns all the section groups in the notebook. Read-only.
   * @return sectionGroupsUrl
  **/
  public String getSectionGroupsUrl() {
    return sectionGroupsUrl;
  }

  public void setSectionGroupsUrl(String sectionGroupsUrl) {
    this.sectionGroupsUrl = sectionGroupsUrl;
  }

  public MicrosoftGraphNotebook sectionsUrl(String sectionsUrl) {
    this.sectionsUrl = sectionsUrl;
    return this;
  }

   /**
   * The URL for the sections navigation property, which returns all the sections in the notebook. Read-only.
   * @return sectionsUrl
  **/
  public String getSectionsUrl() {
    return sectionsUrl;
  }

  public void setSectionsUrl(String sectionsUrl) {
    this.sectionsUrl = sectionsUrl;
  }

  public MicrosoftGraphNotebook userRole(MicrosoftGraphOnenoteUserRole userRole) {
    this.userRole = userRole;
    return this;
  }

   /**
   * Get userRole
   * @return userRole
  **/
  public MicrosoftGraphOnenoteUserRole getUserRole() {
    return userRole;
  }

  public void setUserRole(MicrosoftGraphOnenoteUserRole userRole) {
    this.userRole = userRole;
  }

  public MicrosoftGraphNotebook sectionGroups(List<MicrosoftGraphSectionGroup> sectionGroups) {
    this.sectionGroups = sectionGroups;
    return this;
  }

  public MicrosoftGraphNotebook addSectionGroupsItem(MicrosoftGraphSectionGroup sectionGroupsItem) {
    if (this.sectionGroups == null) {
      this.sectionGroups = new ArrayList<>();
    }
    this.sectionGroups.add(sectionGroupsItem);
    return this;
  }

   /**
   * The section groups in the notebook. Read-only. Nullable.
   * @return sectionGroups
  **/
  public List<MicrosoftGraphSectionGroup> getSectionGroups() {
    return sectionGroups;
  }

  public void setSectionGroups(List<MicrosoftGraphSectionGroup> sectionGroups) {
    this.sectionGroups = sectionGroups;
  }

  public MicrosoftGraphNotebook sections(List<MicrosoftGraphOnenoteSection> sections) {
    this.sections = sections;
    return this;
  }

  public MicrosoftGraphNotebook addSectionsItem(MicrosoftGraphOnenoteSection sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

   /**
   * The sections in the notebook. Read-only. Nullable.
   * @return sections
  **/
  public List<MicrosoftGraphOnenoteSection> getSections() {
    return sections;
  }

  public void setSections(List<MicrosoftGraphOnenoteSection> sections) {
    this.sections = sections;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphNotebook microsoftGraphNotebook = (MicrosoftGraphNotebook) o;
    return Objects.equals(this.isDefault, microsoftGraphNotebook.isDefault) &&
        Objects.equals(this.isShared, microsoftGraphNotebook.isShared) &&
        Objects.equals(this.links, microsoftGraphNotebook.links) &&
        Objects.equals(this.sectionGroupsUrl, microsoftGraphNotebook.sectionGroupsUrl) &&
        Objects.equals(this.sectionsUrl, microsoftGraphNotebook.sectionsUrl) &&
        Objects.equals(this.userRole, microsoftGraphNotebook.userRole) &&
        Objects.equals(this.sectionGroups, microsoftGraphNotebook.sectionGroups) &&
        Objects.equals(this.sections, microsoftGraphNotebook.sections) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isDefault, isShared, links, sectionGroupsUrl, sectionsUrl, userRole, sectionGroups, sections, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphNotebook {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    isShared: ").append(toIndentedString(isShared)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    sectionGroupsUrl: ").append(toIndentedString(sectionGroupsUrl)).append("\n");
    sb.append("    sectionsUrl: ").append(toIndentedString(sectionsUrl)).append("\n");
    sb.append("    userRole: ").append(toIndentedString(userRole)).append("\n");
    sb.append("    sectionGroups: ").append(toIndentedString(sectionGroups)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
