/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphItemActivityStat;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphItemAnalytics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphItemAnalytics extends MicrosoftGraphEntity {
  @JsonProperty("allTime")
  private MicrosoftGraphItemActivityStat allTime = null;

  @JsonProperty("itemActivityStats")
  private List<MicrosoftGraphItemActivityStat> itemActivityStats = null;

  @JsonProperty("lastSevenDays")
  private MicrosoftGraphItemActivityStat lastSevenDays = null;

  public MicrosoftGraphItemAnalytics allTime(MicrosoftGraphItemActivityStat allTime) {
    this.allTime = allTime;
    return this;
  }

   /**
   * Get allTime
   * @return allTime
  **/
  public MicrosoftGraphItemActivityStat getAllTime() {
    return allTime;
  }

  public void setAllTime(MicrosoftGraphItemActivityStat allTime) {
    this.allTime = allTime;
  }

  public MicrosoftGraphItemAnalytics itemActivityStats(List<MicrosoftGraphItemActivityStat> itemActivityStats) {
    this.itemActivityStats = itemActivityStats;
    return this;
  }

  public MicrosoftGraphItemAnalytics addItemActivityStatsItem(MicrosoftGraphItemActivityStat itemActivityStatsItem) {
    if (this.itemActivityStats == null) {
      this.itemActivityStats = new ArrayList<>();
    }
    this.itemActivityStats.add(itemActivityStatsItem);
    return this;
  }

   /**
   * Get itemActivityStats
   * @return itemActivityStats
  **/
  public List<MicrosoftGraphItemActivityStat> getItemActivityStats() {
    return itemActivityStats;
  }

  public void setItemActivityStats(List<MicrosoftGraphItemActivityStat> itemActivityStats) {
    this.itemActivityStats = itemActivityStats;
  }

  public MicrosoftGraphItemAnalytics lastSevenDays(MicrosoftGraphItemActivityStat lastSevenDays) {
    this.lastSevenDays = lastSevenDays;
    return this;
  }

   /**
   * Get lastSevenDays
   * @return lastSevenDays
  **/
  public MicrosoftGraphItemActivityStat getLastSevenDays() {
    return lastSevenDays;
  }

  public void setLastSevenDays(MicrosoftGraphItemActivityStat lastSevenDays) {
    this.lastSevenDays = lastSevenDays;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphItemAnalytics microsoftGraphItemAnalytics = (MicrosoftGraphItemAnalytics) o;
    return Objects.equals(this.allTime, microsoftGraphItemAnalytics.allTime) &&
        Objects.equals(this.itemActivityStats, microsoftGraphItemAnalytics.itemActivityStats) &&
        Objects.equals(this.lastSevenDays, microsoftGraphItemAnalytics.lastSevenDays) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allTime, itemActivityStats, lastSevenDays, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphItemAnalytics {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    allTime: ").append(toIndentedString(allTime)).append("\n");
    sb.append("    itemActivityStats: ").append(toIndentedString(itemActivityStats)).append("\n");
    sb.append("    lastSevenDays: ").append(toIndentedString(lastSevenDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
