/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphExtension;
import com.microsoft.graph.MicrosoftGraphTodoTask;
import com.microsoft.graph.MicrosoftGraphWellknownListName;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphTodoTaskList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTodoTaskList extends MicrosoftGraphEntity {
  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("isOwner")
  private Boolean isOwner = null;

  @JsonProperty("isShared")
  private Boolean isShared = null;

  @JsonProperty("wellknownListName")
  private MicrosoftGraphWellknownListName wellknownListName = null;

  @JsonProperty("extensions")
  private List<MicrosoftGraphExtension> extensions = null;

  @JsonProperty("tasks")
  private List<MicrosoftGraphTodoTask> tasks = null;

  public MicrosoftGraphTodoTaskList displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The name of the task list.
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MicrosoftGraphTodoTaskList isOwner(Boolean isOwner) {
    this.isOwner = isOwner;
    return this;
  }

   /**
   * True if the user is owner of the given task list.
   * @return isOwner
  **/
  public Boolean isIsOwner() {
    return isOwner;
  }

  public void setIsOwner(Boolean isOwner) {
    this.isOwner = isOwner;
  }

  public MicrosoftGraphTodoTaskList isShared(Boolean isShared) {
    this.isShared = isShared;
    return this;
  }

   /**
   * True if the task list is shared with other users
   * @return isShared
  **/
  public Boolean isIsShared() {
    return isShared;
  }

  public void setIsShared(Boolean isShared) {
    this.isShared = isShared;
  }

  public MicrosoftGraphTodoTaskList wellknownListName(MicrosoftGraphWellknownListName wellknownListName) {
    this.wellknownListName = wellknownListName;
    return this;
  }

   /**
   * Get wellknownListName
   * @return wellknownListName
  **/
  public MicrosoftGraphWellknownListName getWellknownListName() {
    return wellknownListName;
  }

  public void setWellknownListName(MicrosoftGraphWellknownListName wellknownListName) {
    this.wellknownListName = wellknownListName;
  }

  public MicrosoftGraphTodoTaskList extensions(List<MicrosoftGraphExtension> extensions) {
    this.extensions = extensions;
    return this;
  }

  public MicrosoftGraphTodoTaskList addExtensionsItem(MicrosoftGraphExtension extensionsItem) {
    if (this.extensions == null) {
      this.extensions = new ArrayList<>();
    }
    this.extensions.add(extensionsItem);
    return this;
  }

   /**
   * The collection of open extensions defined for the task list. Nullable.
   * @return extensions
  **/
  public List<MicrosoftGraphExtension> getExtensions() {
    return extensions;
  }

  public void setExtensions(List<MicrosoftGraphExtension> extensions) {
    this.extensions = extensions;
  }

  public MicrosoftGraphTodoTaskList tasks(List<MicrosoftGraphTodoTask> tasks) {
    this.tasks = tasks;
    return this;
  }

  public MicrosoftGraphTodoTaskList addTasksItem(MicrosoftGraphTodoTask tasksItem) {
    if (this.tasks == null) {
      this.tasks = new ArrayList<>();
    }
    this.tasks.add(tasksItem);
    return this;
  }

   /**
   * The tasks in this task list. Read-only. Nullable.
   * @return tasks
  **/
  public List<MicrosoftGraphTodoTask> getTasks() {
    return tasks;
  }

  public void setTasks(List<MicrosoftGraphTodoTask> tasks) {
    this.tasks = tasks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTodoTaskList microsoftGraphTodoTaskList = (MicrosoftGraphTodoTaskList) o;
    return Objects.equals(this.displayName, microsoftGraphTodoTaskList.displayName) &&
        Objects.equals(this.isOwner, microsoftGraphTodoTaskList.isOwner) &&
        Objects.equals(this.isShared, microsoftGraphTodoTaskList.isShared) &&
        Objects.equals(this.wellknownListName, microsoftGraphTodoTaskList.wellknownListName) &&
        Objects.equals(this.extensions, microsoftGraphTodoTaskList.extensions) &&
        Objects.equals(this.tasks, microsoftGraphTodoTaskList.tasks) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, isOwner, isShared, wellknownListName, extensions, tasks, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTodoTaskList {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    isOwner: ").append(toIndentedString(isOwner)).append("\n");
    sb.append("    isShared: ").append(toIndentedString(isShared)).append("\n");
    sb.append("    wellknownListName: ").append(toIndentedString(wellknownListName)).append("\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
