/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphWorkbookChart;
import com.microsoft.graph.MicrosoftGraphWorkbookNamedItem;
import com.microsoft.graph.MicrosoftGraphWorkbookPivotTable;
import com.microsoft.graph.MicrosoftGraphWorkbookTable;
import com.microsoft.graph.MicrosoftGraphWorkbookWorksheetProtection;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphWorkbookWorksheet
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkbookWorksheet extends MicrosoftGraphEntity {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("position")
  private Integer position = null;

  @JsonProperty("visibility")
  private String visibility = null;

  @JsonProperty("charts")
  private List<MicrosoftGraphWorkbookChart> charts = null;

  @JsonProperty("names")
  private List<MicrosoftGraphWorkbookNamedItem> names = null;

  @JsonProperty("pivotTables")
  private List<MicrosoftGraphWorkbookPivotTable> pivotTables = null;

  @JsonProperty("protection")
  private MicrosoftGraphWorkbookWorksheetProtection protection = null;

  @JsonProperty("tables")
  private List<MicrosoftGraphWorkbookTable> tables = null;

  public MicrosoftGraphWorkbookWorksheet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The display name of the worksheet.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftGraphWorkbookWorksheet position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * The zero-based position of the worksheet within the workbook.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return position
  **/
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public MicrosoftGraphWorkbookWorksheet visibility(String visibility) {
    this.visibility = visibility;
    return this;
  }

   /**
   * The Visibility of the worksheet. The possible values are: Visible, Hidden, VeryHidden.
   * @return visibility
  **/
  public String getVisibility() {
    return visibility;
  }

  public void setVisibility(String visibility) {
    this.visibility = visibility;
  }

  public MicrosoftGraphWorkbookWorksheet charts(List<MicrosoftGraphWorkbookChart> charts) {
    this.charts = charts;
    return this;
  }

  public MicrosoftGraphWorkbookWorksheet addChartsItem(MicrosoftGraphWorkbookChart chartsItem) {
    if (this.charts == null) {
      this.charts = new ArrayList<>();
    }
    this.charts.add(chartsItem);
    return this;
  }

   /**
   * Returns collection of charts that are part of the worksheet. Read-only.
   * @return charts
  **/
  public List<MicrosoftGraphWorkbookChart> getCharts() {
    return charts;
  }

  public void setCharts(List<MicrosoftGraphWorkbookChart> charts) {
    this.charts = charts;
  }

  public MicrosoftGraphWorkbookWorksheet names(List<MicrosoftGraphWorkbookNamedItem> names) {
    this.names = names;
    return this;
  }

  public MicrosoftGraphWorkbookWorksheet addNamesItem(MicrosoftGraphWorkbookNamedItem namesItem) {
    if (this.names == null) {
      this.names = new ArrayList<>();
    }
    this.names.add(namesItem);
    return this;
  }

   /**
   * Returns collection of names that are associated with the worksheet. Read-only.
   * @return names
  **/
  public List<MicrosoftGraphWorkbookNamedItem> getNames() {
    return names;
  }

  public void setNames(List<MicrosoftGraphWorkbookNamedItem> names) {
    this.names = names;
  }

  public MicrosoftGraphWorkbookWorksheet pivotTables(List<MicrosoftGraphWorkbookPivotTable> pivotTables) {
    this.pivotTables = pivotTables;
    return this;
  }

  public MicrosoftGraphWorkbookWorksheet addPivotTablesItem(MicrosoftGraphWorkbookPivotTable pivotTablesItem) {
    if (this.pivotTables == null) {
      this.pivotTables = new ArrayList<>();
    }
    this.pivotTables.add(pivotTablesItem);
    return this;
  }

   /**
   * Collection of PivotTables that are part of the worksheet.
   * @return pivotTables
  **/
  public List<MicrosoftGraphWorkbookPivotTable> getPivotTables() {
    return pivotTables;
  }

  public void setPivotTables(List<MicrosoftGraphWorkbookPivotTable> pivotTables) {
    this.pivotTables = pivotTables;
  }

  public MicrosoftGraphWorkbookWorksheet protection(MicrosoftGraphWorkbookWorksheetProtection protection) {
    this.protection = protection;
    return this;
  }

   /**
   * Get protection
   * @return protection
  **/
  public MicrosoftGraphWorkbookWorksheetProtection getProtection() {
    return protection;
  }

  public void setProtection(MicrosoftGraphWorkbookWorksheetProtection protection) {
    this.protection = protection;
  }

  public MicrosoftGraphWorkbookWorksheet tables(List<MicrosoftGraphWorkbookTable> tables) {
    this.tables = tables;
    return this;
  }

  public MicrosoftGraphWorkbookWorksheet addTablesItem(MicrosoftGraphWorkbookTable tablesItem) {
    if (this.tables == null) {
      this.tables = new ArrayList<>();
    }
    this.tables.add(tablesItem);
    return this;
  }

   /**
   * Collection of tables that are part of the worksheet. Read-only.
   * @return tables
  **/
  public List<MicrosoftGraphWorkbookTable> getTables() {
    return tables;
  }

  public void setTables(List<MicrosoftGraphWorkbookTable> tables) {
    this.tables = tables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkbookWorksheet microsoftGraphWorkbookWorksheet = (MicrosoftGraphWorkbookWorksheet) o;
    return Objects.equals(this.name, microsoftGraphWorkbookWorksheet.name) &&
        Objects.equals(this.position, microsoftGraphWorkbookWorksheet.position) &&
        Objects.equals(this.visibility, microsoftGraphWorkbookWorksheet.visibility) &&
        Objects.equals(this.charts, microsoftGraphWorkbookWorksheet.charts) &&
        Objects.equals(this.names, microsoftGraphWorkbookWorksheet.names) &&
        Objects.equals(this.pivotTables, microsoftGraphWorkbookWorksheet.pivotTables) &&
        Objects.equals(this.protection, microsoftGraphWorkbookWorksheet.protection) &&
        Objects.equals(this.tables, microsoftGraphWorkbookWorksheet.tables) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, position, visibility, charts, names, pivotTables, protection, tables, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkbookWorksheet {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    charts: ").append(toIndentedString(charts)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    pivotTables: ").append(toIndentedString(pivotTables)).append("\n");
    sb.append("    protection: ").append(toIndentedString(protection)).append("\n");
    sb.append("    tables: ").append(toIndentedString(tables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
