/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphLookupColumn
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphLookupColumn {
  @JsonProperty("allowMultipleValues")
  private Boolean allowMultipleValues = null;

  @JsonProperty("allowUnlimitedLength")
  private Boolean allowUnlimitedLength = null;

  @JsonProperty("columnName")
  private String columnName = null;

  @JsonProperty("listId")
  private String listId = null;

  @JsonProperty("primaryLookupColumnId")
  private String primaryLookupColumnId = null;

  public MicrosoftGraphLookupColumn allowMultipleValues(Boolean allowMultipleValues) {
    this.allowMultipleValues = allowMultipleValues;
    return this;
  }

   /**
   * Indicates whether multiple values can be selected from the source.
   * @return allowMultipleValues
  **/
  public Boolean isAllowMultipleValues() {
    return allowMultipleValues;
  }

  public void setAllowMultipleValues(Boolean allowMultipleValues) {
    this.allowMultipleValues = allowMultipleValues;
  }

  public MicrosoftGraphLookupColumn allowUnlimitedLength(Boolean allowUnlimitedLength) {
    this.allowUnlimitedLength = allowUnlimitedLength;
    return this;
  }

   /**
   * Indicates whether values in the column should be able to exceed the standard limit of 255 characters.
   * @return allowUnlimitedLength
  **/
  public Boolean isAllowUnlimitedLength() {
    return allowUnlimitedLength;
  }

  public void setAllowUnlimitedLength(Boolean allowUnlimitedLength) {
    this.allowUnlimitedLength = allowUnlimitedLength;
  }

  public MicrosoftGraphLookupColumn columnName(String columnName) {
    this.columnName = columnName;
    return this;
  }

   /**
   * The name of the lookup source column.
   * @return columnName
  **/
  public String getColumnName() {
    return columnName;
  }

  public void setColumnName(String columnName) {
    this.columnName = columnName;
  }

  public MicrosoftGraphLookupColumn listId(String listId) {
    this.listId = listId;
    return this;
  }

   /**
   * The unique identifier of the lookup source list.
   * @return listId
  **/
  public String getListId() {
    return listId;
  }

  public void setListId(String listId) {
    this.listId = listId;
  }

  public MicrosoftGraphLookupColumn primaryLookupColumnId(String primaryLookupColumnId) {
    this.primaryLookupColumnId = primaryLookupColumnId;
    return this;
  }

   /**
   * If specified, this column is a secondary lookup, pulling an additional field from the list item looked up by the primary lookup. Use the list item looked up by the primary as the source for the column named here.
   * @return primaryLookupColumnId
  **/
  public String getPrimaryLookupColumnId() {
    return primaryLookupColumnId;
  }

  public void setPrimaryLookupColumnId(String primaryLookupColumnId) {
    this.primaryLookupColumnId = primaryLookupColumnId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphLookupColumn microsoftGraphLookupColumn = (MicrosoftGraphLookupColumn) o;
    return Objects.equals(this.allowMultipleValues, microsoftGraphLookupColumn.allowMultipleValues) &&
        Objects.equals(this.allowUnlimitedLength, microsoftGraphLookupColumn.allowUnlimitedLength) &&
        Objects.equals(this.columnName, microsoftGraphLookupColumn.columnName) &&
        Objects.equals(this.listId, microsoftGraphLookupColumn.listId) &&
        Objects.equals(this.primaryLookupColumnId, microsoftGraphLookupColumn.primaryLookupColumnId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowMultipleValues, allowUnlimitedLength, columnName, listId, primaryLookupColumnId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphLookupColumn {\n");
    
    sb.append("    allowMultipleValues: ").append(toIndentedString(allowMultipleValues)).append("\n");
    sb.append("    allowUnlimitedLength: ").append(toIndentedString(allowUnlimitedLength)).append("\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    listId: ").append(toIndentedString(listId)).append("\n");
    sb.append("    primaryLookupColumnId: ").append(toIndentedString(primaryLookupColumnId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
