/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphWorkbookChartDataLabelFormat;

/**
 * MicrosoftGraphWorkbookChartDataLabels
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkbookChartDataLabels extends MicrosoftGraphEntity {
  @JsonProperty("position")
  private String position = null;

  @JsonProperty("separator")
  private String separator = null;

  @JsonProperty("showBubbleSize")
  private Boolean showBubbleSize = null;

  @JsonProperty("showCategoryName")
  private Boolean showCategoryName = null;

  @JsonProperty("showLegendKey")
  private Boolean showLegendKey = null;

  @JsonProperty("showPercentage")
  private Boolean showPercentage = null;

  @JsonProperty("showSeriesName")
  private Boolean showSeriesName = null;

  @JsonProperty("showValue")
  private Boolean showValue = null;

  @JsonProperty("format")
  private MicrosoftGraphWorkbookChartDataLabelFormat format = null;

  public MicrosoftGraphWorkbookChartDataLabels position(String position) {
    this.position = position;
    return this;
  }

   /**
   * DataLabelPosition value that represents the position of the data label. The possible values are: None, Center, InsideEnd, InsideBase, OutsideEnd, Left, Right, Top, Bottom, BestFit, Callout.
   * @return position
  **/
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public MicrosoftGraphWorkbookChartDataLabels separator(String separator) {
    this.separator = separator;
    return this;
  }

   /**
   * String representing the separator used for the data labels on a chart.
   * @return separator
  **/
  public String getSeparator() {
    return separator;
  }

  public void setSeparator(String separator) {
    this.separator = separator;
  }

  public MicrosoftGraphWorkbookChartDataLabels showBubbleSize(Boolean showBubbleSize) {
    this.showBubbleSize = showBubbleSize;
    return this;
  }

   /**
   * Boolean value representing if the data label bubble size is visible or not.
   * @return showBubbleSize
  **/
  public Boolean isShowBubbleSize() {
    return showBubbleSize;
  }

  public void setShowBubbleSize(Boolean showBubbleSize) {
    this.showBubbleSize = showBubbleSize;
  }

  public MicrosoftGraphWorkbookChartDataLabels showCategoryName(Boolean showCategoryName) {
    this.showCategoryName = showCategoryName;
    return this;
  }

   /**
   * Boolean value representing if the data label category name is visible or not.
   * @return showCategoryName
  **/
  public Boolean isShowCategoryName() {
    return showCategoryName;
  }

  public void setShowCategoryName(Boolean showCategoryName) {
    this.showCategoryName = showCategoryName;
  }

  public MicrosoftGraphWorkbookChartDataLabels showLegendKey(Boolean showLegendKey) {
    this.showLegendKey = showLegendKey;
    return this;
  }

   /**
   * Boolean value representing if the data label legend key is visible or not.
   * @return showLegendKey
  **/
  public Boolean isShowLegendKey() {
    return showLegendKey;
  }

  public void setShowLegendKey(Boolean showLegendKey) {
    this.showLegendKey = showLegendKey;
  }

  public MicrosoftGraphWorkbookChartDataLabels showPercentage(Boolean showPercentage) {
    this.showPercentage = showPercentage;
    return this;
  }

   /**
   * Boolean value representing if the data label percentage is visible or not.
   * @return showPercentage
  **/
  public Boolean isShowPercentage() {
    return showPercentage;
  }

  public void setShowPercentage(Boolean showPercentage) {
    this.showPercentage = showPercentage;
  }

  public MicrosoftGraphWorkbookChartDataLabels showSeriesName(Boolean showSeriesName) {
    this.showSeriesName = showSeriesName;
    return this;
  }

   /**
   * Boolean value representing if the data label series name is visible or not.
   * @return showSeriesName
  **/
  public Boolean isShowSeriesName() {
    return showSeriesName;
  }

  public void setShowSeriesName(Boolean showSeriesName) {
    this.showSeriesName = showSeriesName;
  }

  public MicrosoftGraphWorkbookChartDataLabels showValue(Boolean showValue) {
    this.showValue = showValue;
    return this;
  }

   /**
   * Boolean value representing if the data label value is visible or not.
   * @return showValue
  **/
  public Boolean isShowValue() {
    return showValue;
  }

  public void setShowValue(Boolean showValue) {
    this.showValue = showValue;
  }

  public MicrosoftGraphWorkbookChartDataLabels format(MicrosoftGraphWorkbookChartDataLabelFormat format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  public MicrosoftGraphWorkbookChartDataLabelFormat getFormat() {
    return format;
  }

  public void setFormat(MicrosoftGraphWorkbookChartDataLabelFormat format) {
    this.format = format;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkbookChartDataLabels microsoftGraphWorkbookChartDataLabels = (MicrosoftGraphWorkbookChartDataLabels) o;
    return Objects.equals(this.position, microsoftGraphWorkbookChartDataLabels.position) &&
        Objects.equals(this.separator, microsoftGraphWorkbookChartDataLabels.separator) &&
        Objects.equals(this.showBubbleSize, microsoftGraphWorkbookChartDataLabels.showBubbleSize) &&
        Objects.equals(this.showCategoryName, microsoftGraphWorkbookChartDataLabels.showCategoryName) &&
        Objects.equals(this.showLegendKey, microsoftGraphWorkbookChartDataLabels.showLegendKey) &&
        Objects.equals(this.showPercentage, microsoftGraphWorkbookChartDataLabels.showPercentage) &&
        Objects.equals(this.showSeriesName, microsoftGraphWorkbookChartDataLabels.showSeriesName) &&
        Objects.equals(this.showValue, microsoftGraphWorkbookChartDataLabels.showValue) &&
        Objects.equals(this.format, microsoftGraphWorkbookChartDataLabels.format) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(position, separator, showBubbleSize, showCategoryName, showLegendKey, showPercentage, showSeriesName, showValue, format, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkbookChartDataLabels {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    separator: ").append(toIndentedString(separator)).append("\n");
    sb.append("    showBubbleSize: ").append(toIndentedString(showBubbleSize)).append("\n");
    sb.append("    showCategoryName: ").append(toIndentedString(showCategoryName)).append("\n");
    sb.append("    showLegendKey: ").append(toIndentedString(showLegendKey)).append("\n");
    sb.append("    showPercentage: ").append(toIndentedString(showPercentage)).append("\n");
    sb.append("    showSeriesName: ").append(toIndentedString(showSeriesName)).append("\n");
    sb.append("    showValue: ").append(toIndentedString(showValue)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
