/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphWorkbookChartAreaFormat;
import com.microsoft.graph.MicrosoftGraphWorkbookChartAxes;
import com.microsoft.graph.MicrosoftGraphWorkbookChartDataLabels;
import com.microsoft.graph.MicrosoftGraphWorkbookChartLegend;
import com.microsoft.graph.MicrosoftGraphWorkbookChartSeries;
import com.microsoft.graph.MicrosoftGraphWorkbookChartTitle;
import com.microsoft.graph.MicrosoftGraphWorkbookWorksheet;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphWorkbookChart
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkbookChart extends MicrosoftGraphEntity {
  @JsonProperty("height")
  private Double height = null;

  @JsonProperty("left")
  private Double left = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("top")
  private Double top = null;

  @JsonProperty("width")
  private Double width = null;

  @JsonProperty("axes")
  private MicrosoftGraphWorkbookChartAxes axes = null;

  @JsonProperty("dataLabels")
  private MicrosoftGraphWorkbookChartDataLabels dataLabels = null;

  @JsonProperty("format")
  private MicrosoftGraphWorkbookChartAreaFormat format = null;

  @JsonProperty("legend")
  private MicrosoftGraphWorkbookChartLegend legend = null;

  @JsonProperty("series")
  private List<MicrosoftGraphWorkbookChartSeries> series = null;

  @JsonProperty("title")
  private MicrosoftGraphWorkbookChartTitle title = null;

  @JsonProperty("worksheet")
  private MicrosoftGraphWorkbookWorksheet worksheet = null;

  public MicrosoftGraphWorkbookChart height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * Represents the height, in points, of the chart object.
   * @return height
  **/
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public MicrosoftGraphWorkbookChart left(Double left) {
    this.left = left;
    return this;
  }

   /**
   * The distance, in points, from the left side of the chart to the worksheet origin.
   * @return left
  **/
  public Double getLeft() {
    return left;
  }

  public void setLeft(Double left) {
    this.left = left;
  }

  public MicrosoftGraphWorkbookChart name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Represents the name of a chart object.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftGraphWorkbookChart top(Double top) {
    this.top = top;
    return this;
  }

   /**
   * Represents the distance, in points, from the top edge of the object to the top of row 1 (on a worksheet) or the top of the chart area (on a chart).
   * @return top
  **/
  public Double getTop() {
    return top;
  }

  public void setTop(Double top) {
    this.top = top;
  }

  public MicrosoftGraphWorkbookChart width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * Represents the width, in points, of the chart object.
   * @return width
  **/
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }

  public MicrosoftGraphWorkbookChart axes(MicrosoftGraphWorkbookChartAxes axes) {
    this.axes = axes;
    return this;
  }

   /**
   * Get axes
   * @return axes
  **/
  public MicrosoftGraphWorkbookChartAxes getAxes() {
    return axes;
  }

  public void setAxes(MicrosoftGraphWorkbookChartAxes axes) {
    this.axes = axes;
  }

  public MicrosoftGraphWorkbookChart dataLabels(MicrosoftGraphWorkbookChartDataLabels dataLabels) {
    this.dataLabels = dataLabels;
    return this;
  }

   /**
   * Get dataLabels
   * @return dataLabels
  **/
  public MicrosoftGraphWorkbookChartDataLabels getDataLabels() {
    return dataLabels;
  }

  public void setDataLabels(MicrosoftGraphWorkbookChartDataLabels dataLabels) {
    this.dataLabels = dataLabels;
  }

  public MicrosoftGraphWorkbookChart format(MicrosoftGraphWorkbookChartAreaFormat format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  public MicrosoftGraphWorkbookChartAreaFormat getFormat() {
    return format;
  }

  public void setFormat(MicrosoftGraphWorkbookChartAreaFormat format) {
    this.format = format;
  }

  public MicrosoftGraphWorkbookChart legend(MicrosoftGraphWorkbookChartLegend legend) {
    this.legend = legend;
    return this;
  }

   /**
   * Get legend
   * @return legend
  **/
  public MicrosoftGraphWorkbookChartLegend getLegend() {
    return legend;
  }

  public void setLegend(MicrosoftGraphWorkbookChartLegend legend) {
    this.legend = legend;
  }

  public MicrosoftGraphWorkbookChart series(List<MicrosoftGraphWorkbookChartSeries> series) {
    this.series = series;
    return this;
  }

  public MicrosoftGraphWorkbookChart addSeriesItem(MicrosoftGraphWorkbookChartSeries seriesItem) {
    if (this.series == null) {
      this.series = new ArrayList<>();
    }
    this.series.add(seriesItem);
    return this;
  }

   /**
   * Represents either a single series or collection of series in the chart. Read-only.
   * @return series
  **/
  public List<MicrosoftGraphWorkbookChartSeries> getSeries() {
    return series;
  }

  public void setSeries(List<MicrosoftGraphWorkbookChartSeries> series) {
    this.series = series;
  }

  public MicrosoftGraphWorkbookChart title(MicrosoftGraphWorkbookChartTitle title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public MicrosoftGraphWorkbookChartTitle getTitle() {
    return title;
  }

  public void setTitle(MicrosoftGraphWorkbookChartTitle title) {
    this.title = title;
  }

  public MicrosoftGraphWorkbookChart worksheet(MicrosoftGraphWorkbookWorksheet worksheet) {
    this.worksheet = worksheet;
    return this;
  }

   /**
   * Get worksheet
   * @return worksheet
  **/
  public MicrosoftGraphWorkbookWorksheet getWorksheet() {
    return worksheet;
  }

  public void setWorksheet(MicrosoftGraphWorkbookWorksheet worksheet) {
    this.worksheet = worksheet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkbookChart microsoftGraphWorkbookChart = (MicrosoftGraphWorkbookChart) o;
    return Objects.equals(this.height, microsoftGraphWorkbookChart.height) &&
        Objects.equals(this.left, microsoftGraphWorkbookChart.left) &&
        Objects.equals(this.name, microsoftGraphWorkbookChart.name) &&
        Objects.equals(this.top, microsoftGraphWorkbookChart.top) &&
        Objects.equals(this.width, microsoftGraphWorkbookChart.width) &&
        Objects.equals(this.axes, microsoftGraphWorkbookChart.axes) &&
        Objects.equals(this.dataLabels, microsoftGraphWorkbookChart.dataLabels) &&
        Objects.equals(this.format, microsoftGraphWorkbookChart.format) &&
        Objects.equals(this.legend, microsoftGraphWorkbookChart.legend) &&
        Objects.equals(this.series, microsoftGraphWorkbookChart.series) &&
        Objects.equals(this.title, microsoftGraphWorkbookChart.title) &&
        Objects.equals(this.worksheet, microsoftGraphWorkbookChart.worksheet) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, left, name, top, width, axes, dataLabels, format, legend, series, title, worksheet, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkbookChart {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    axes: ").append(toIndentedString(axes)).append("\n");
    sb.append("    dataLabels: ").append(toIndentedString(dataLabels)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    legend: ").append(toIndentedString(legend)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    worksheet: ").append(toIndentedString(worksheet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
