/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphSharepointIds;

/**
 * MicrosoftGraphItemReference
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphItemReference {
  @JsonProperty("driveId")
  private String driveId = null;

  @JsonProperty("driveType")
  private String driveType = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("path")
  private String path = null;

  @JsonProperty("shareId")
  private String shareId = null;

  @JsonProperty("sharepointIds")
  private MicrosoftGraphSharepointIds sharepointIds = null;

  @JsonProperty("siteId")
  private String siteId = null;

  public MicrosoftGraphItemReference driveId(String driveId) {
    this.driveId = driveId;
    return this;
  }

   /**
   * Unique identifier of the drive instance that contains the item. Read-only.
   * @return driveId
  **/
  public String getDriveId() {
    return driveId;
  }

  public void setDriveId(String driveId) {
    this.driveId = driveId;
  }

  public MicrosoftGraphItemReference driveType(String driveType) {
    this.driveType = driveType;
    return this;
  }

   /**
   * Identifies the type of drive. See [drive][] resource for values.
   * @return driveType
  **/
  public String getDriveType() {
    return driveType;
  }

  public void setDriveType(String driveType) {
    this.driveType = driveType;
  }

  public MicrosoftGraphItemReference id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the item in the drive. Read-only.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MicrosoftGraphItemReference name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the item being referenced. Read-only.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftGraphItemReference path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Path that can be used to navigate to the item. Read-only.
   * @return path
  **/
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public MicrosoftGraphItemReference shareId(String shareId) {
    this.shareId = shareId;
    return this;
  }

   /**
   * A unique identifier for a shared resource that can be accessed via the [Shares][] API.
   * @return shareId
  **/
  public String getShareId() {
    return shareId;
  }

  public void setShareId(String shareId) {
    this.shareId = shareId;
  }

  public MicrosoftGraphItemReference sharepointIds(MicrosoftGraphSharepointIds sharepointIds) {
    this.sharepointIds = sharepointIds;
    return this;
  }

   /**
   * Get sharepointIds
   * @return sharepointIds
  **/
  public MicrosoftGraphSharepointIds getSharepointIds() {
    return sharepointIds;
  }

  public void setSharepointIds(MicrosoftGraphSharepointIds sharepointIds) {
    this.sharepointIds = sharepointIds;
  }

  public MicrosoftGraphItemReference siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

   /**
   * For OneDrive for Business and SharePoint, this property represents the ID of the site that contains the parent document library of the driveItem resource. The value is the same as the id property of that [site][] resource. It is an opaque string that consists of three identifiers of the site. For OneDrive, this property is not populated.
   * @return siteId
  **/
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphItemReference microsoftGraphItemReference = (MicrosoftGraphItemReference) o;
    return Objects.equals(this.driveId, microsoftGraphItemReference.driveId) &&
        Objects.equals(this.driveType, microsoftGraphItemReference.driveType) &&
        Objects.equals(this.id, microsoftGraphItemReference.id) &&
        Objects.equals(this.name, microsoftGraphItemReference.name) &&
        Objects.equals(this.path, microsoftGraphItemReference.path) &&
        Objects.equals(this.shareId, microsoftGraphItemReference.shareId) &&
        Objects.equals(this.sharepointIds, microsoftGraphItemReference.sharepointIds) &&
        Objects.equals(this.siteId, microsoftGraphItemReference.siteId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(driveId, driveType, id, name, path, shareId, sharepointIds, siteId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphItemReference {\n");
    
    sb.append("    driveId: ").append(toIndentedString(driveId)).append("\n");
    sb.append("    driveType: ").append(toIndentedString(driveType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    shareId: ").append(toIndentedString(shareId)).append("\n");
    sb.append("    sharepointIds: ").append(toIndentedString(sharepointIds)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
