/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;

/**
 * MicrosoftGraphWorkbookApplication
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkbookApplication extends MicrosoftGraphEntity {
  @JsonProperty("calculationMode")
  private String calculationMode = null;

  public MicrosoftGraphWorkbookApplication calculationMode(String calculationMode) {
    this.calculationMode = calculationMode;
    return this;
  }

   /**
   * Returns the calculation mode used in the workbook. Possible values are: Automatic, AutomaticExceptTables, Manual.
   * @return calculationMode
  **/
  public String getCalculationMode() {
    return calculationMode;
  }

  public void setCalculationMode(String calculationMode) {
    this.calculationMode = calculationMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkbookApplication microsoftGraphWorkbookApplication = (MicrosoftGraphWorkbookApplication) o;
    return Objects.equals(this.calculationMode, microsoftGraphWorkbookApplication.calculationMode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calculationMode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkbookApplication {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    calculationMode: ").append(toIndentedString(calculationMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
