/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphBooleanColumn;
import com.microsoft.graph.MicrosoftGraphCalculatedColumn;
import com.microsoft.graph.MicrosoftGraphChoiceColumn;
import com.microsoft.graph.MicrosoftGraphColumnDefinition;
import com.microsoft.graph.MicrosoftGraphColumnTypes;
import com.microsoft.graph.MicrosoftGraphColumnValidation;
import com.microsoft.graph.MicrosoftGraphContentApprovalStatusColumn;
import com.microsoft.graph.MicrosoftGraphContentTypeInfo;
import com.microsoft.graph.MicrosoftGraphCurrencyColumn;
import com.microsoft.graph.MicrosoftGraphDateTimeColumn;
import com.microsoft.graph.MicrosoftGraphDefaultColumnValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphGeolocationColumn;
import com.microsoft.graph.MicrosoftGraphHyperlinkOrPictureColumn;
import com.microsoft.graph.MicrosoftGraphLookupColumn;
import com.microsoft.graph.MicrosoftGraphNumberColumn;
import com.microsoft.graph.MicrosoftGraphPersonOrGroupColumn;
import com.microsoft.graph.MicrosoftGraphTermColumn;
import com.microsoft.graph.MicrosoftGraphTextColumn;
import com.microsoft.graph.MicrosoftGraphThumbnailColumn;

/**
 * MicrosoftGraphColumnDefinition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphColumnDefinition extends MicrosoftGraphEntity {
  @JsonProperty("boolean")
  private MicrosoftGraphBooleanColumn _boolean = null;

  @JsonProperty("calculated")
  private MicrosoftGraphCalculatedColumn calculated = null;

  @JsonProperty("choice")
  private MicrosoftGraphChoiceColumn choice = null;

  @JsonProperty("columnGroup")
  private String columnGroup = null;

  @JsonProperty("contentApprovalStatus")
  private MicrosoftGraphContentApprovalStatusColumn contentApprovalStatus = null;

  @JsonProperty("currency")
  private MicrosoftGraphCurrencyColumn currency = null;

  @JsonProperty("dateTime")
  private MicrosoftGraphDateTimeColumn dateTime = null;

  @JsonProperty("defaultValue")
  private MicrosoftGraphDefaultColumnValue defaultValue = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("enforceUniqueValues")
  private Boolean enforceUniqueValues = null;

  @JsonProperty("geolocation")
  private MicrosoftGraphGeolocationColumn geolocation = null;

  @JsonProperty("hidden")
  private Boolean hidden = null;

  @JsonProperty("hyperlinkOrPicture")
  private MicrosoftGraphHyperlinkOrPictureColumn hyperlinkOrPicture = null;

  @JsonProperty("indexed")
  private Boolean indexed = null;

  @JsonProperty("isDeletable")
  private Boolean isDeletable = null;

  @JsonProperty("isReorderable")
  private Boolean isReorderable = null;

  @JsonProperty("isSealed")
  private Boolean isSealed = null;

  @JsonProperty("lookup")
  private MicrosoftGraphLookupColumn lookup = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("number")
  private MicrosoftGraphNumberColumn number = null;

  @JsonProperty("personOrGroup")
  private MicrosoftGraphPersonOrGroupColumn personOrGroup = null;

  @JsonProperty("propagateChanges")
  private Boolean propagateChanges = null;

  @JsonProperty("readOnly")
  private Boolean readOnly = null;

  @JsonProperty("required")
  private Boolean required = null;

  @JsonProperty("sourceContentType")
  private MicrosoftGraphContentTypeInfo sourceContentType = null;

  @JsonProperty("term")
  private MicrosoftGraphTermColumn term = null;

  @JsonProperty("text")
  private MicrosoftGraphTextColumn text = null;

  @JsonProperty("thumbnail")
  private MicrosoftGraphThumbnailColumn thumbnail = null;

  @JsonProperty("type")
  private MicrosoftGraphColumnTypes type = null;

  @JsonProperty("validation")
  private MicrosoftGraphColumnValidation validation = null;

  @JsonProperty("sourceColumn")
  private MicrosoftGraphColumnDefinition sourceColumn = null;

  public MicrosoftGraphColumnDefinition _boolean(MicrosoftGraphBooleanColumn _boolean) {
    this._boolean = _boolean;
    return this;
  }

   /**
   * Get _boolean
   * @return _boolean
  **/
  public MicrosoftGraphBooleanColumn getBoolean() {
    return _boolean;
  }

  public void setBoolean(MicrosoftGraphBooleanColumn _boolean) {
    this._boolean = _boolean;
  }

  public MicrosoftGraphColumnDefinition calculated(MicrosoftGraphCalculatedColumn calculated) {
    this.calculated = calculated;
    return this;
  }

   /**
   * Get calculated
   * @return calculated
  **/
  public MicrosoftGraphCalculatedColumn getCalculated() {
    return calculated;
  }

  public void setCalculated(MicrosoftGraphCalculatedColumn calculated) {
    this.calculated = calculated;
  }

  public MicrosoftGraphColumnDefinition choice(MicrosoftGraphChoiceColumn choice) {
    this.choice = choice;
    return this;
  }

   /**
   * Get choice
   * @return choice
  **/
  public MicrosoftGraphChoiceColumn getChoice() {
    return choice;
  }

  public void setChoice(MicrosoftGraphChoiceColumn choice) {
    this.choice = choice;
  }

  public MicrosoftGraphColumnDefinition columnGroup(String columnGroup) {
    this.columnGroup = columnGroup;
    return this;
  }

   /**
   * For site columns, the name of the group this column belongs to. Helps organize related columns.
   * @return columnGroup
  **/
  public String getColumnGroup() {
    return columnGroup;
  }

  public void setColumnGroup(String columnGroup) {
    this.columnGroup = columnGroup;
  }

  public MicrosoftGraphColumnDefinition contentApprovalStatus(MicrosoftGraphContentApprovalStatusColumn contentApprovalStatus) {
    this.contentApprovalStatus = contentApprovalStatus;
    return this;
  }

   /**
   * Get contentApprovalStatus
   * @return contentApprovalStatus
  **/
  public MicrosoftGraphContentApprovalStatusColumn getContentApprovalStatus() {
    return contentApprovalStatus;
  }

  public void setContentApprovalStatus(MicrosoftGraphContentApprovalStatusColumn contentApprovalStatus) {
    this.contentApprovalStatus = contentApprovalStatus;
  }

  public MicrosoftGraphColumnDefinition currency(MicrosoftGraphCurrencyColumn currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public MicrosoftGraphCurrencyColumn getCurrency() {
    return currency;
  }

  public void setCurrency(MicrosoftGraphCurrencyColumn currency) {
    this.currency = currency;
  }

  public MicrosoftGraphColumnDefinition dateTime(MicrosoftGraphDateTimeColumn dateTime) {
    this.dateTime = dateTime;
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  public MicrosoftGraphDateTimeColumn getDateTime() {
    return dateTime;
  }

  public void setDateTime(MicrosoftGraphDateTimeColumn dateTime) {
    this.dateTime = dateTime;
  }

  public MicrosoftGraphColumnDefinition defaultValue(MicrosoftGraphDefaultColumnValue defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  public MicrosoftGraphDefaultColumnValue getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(MicrosoftGraphDefaultColumnValue defaultValue) {
    this.defaultValue = defaultValue;
  }

  public MicrosoftGraphColumnDefinition description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The user-facing description of the column.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MicrosoftGraphColumnDefinition displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The user-facing name of the column.
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MicrosoftGraphColumnDefinition enforceUniqueValues(Boolean enforceUniqueValues) {
    this.enforceUniqueValues = enforceUniqueValues;
    return this;
  }

   /**
   * If true, no two list items may have the same value for this column.
   * @return enforceUniqueValues
  **/
  public Boolean isEnforceUniqueValues() {
    return enforceUniqueValues;
  }

  public void setEnforceUniqueValues(Boolean enforceUniqueValues) {
    this.enforceUniqueValues = enforceUniqueValues;
  }

  public MicrosoftGraphColumnDefinition geolocation(MicrosoftGraphGeolocationColumn geolocation) {
    this.geolocation = geolocation;
    return this;
  }

   /**
   * Get geolocation
   * @return geolocation
  **/
  public MicrosoftGraphGeolocationColumn getGeolocation() {
    return geolocation;
  }

  public void setGeolocation(MicrosoftGraphGeolocationColumn geolocation) {
    this.geolocation = geolocation;
  }

  public MicrosoftGraphColumnDefinition hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * Specifies whether the column is displayed in the user interface.
   * @return hidden
  **/
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public MicrosoftGraphColumnDefinition hyperlinkOrPicture(MicrosoftGraphHyperlinkOrPictureColumn hyperlinkOrPicture) {
    this.hyperlinkOrPicture = hyperlinkOrPicture;
    return this;
  }

   /**
   * Get hyperlinkOrPicture
   * @return hyperlinkOrPicture
  **/
  public MicrosoftGraphHyperlinkOrPictureColumn getHyperlinkOrPicture() {
    return hyperlinkOrPicture;
  }

  public void setHyperlinkOrPicture(MicrosoftGraphHyperlinkOrPictureColumn hyperlinkOrPicture) {
    this.hyperlinkOrPicture = hyperlinkOrPicture;
  }

  public MicrosoftGraphColumnDefinition indexed(Boolean indexed) {
    this.indexed = indexed;
    return this;
  }

   /**
   * Specifies whether the column values can be used for sorting and searching.
   * @return indexed
  **/
  public Boolean isIndexed() {
    return indexed;
  }

  public void setIndexed(Boolean indexed) {
    this.indexed = indexed;
  }

  public MicrosoftGraphColumnDefinition isDeletable(Boolean isDeletable) {
    this.isDeletable = isDeletable;
    return this;
  }

   /**
   * Indicates whether this column can be deleted.
   * @return isDeletable
  **/
  public Boolean isIsDeletable() {
    return isDeletable;
  }

  public void setIsDeletable(Boolean isDeletable) {
    this.isDeletable = isDeletable;
  }

  public MicrosoftGraphColumnDefinition isReorderable(Boolean isReorderable) {
    this.isReorderable = isReorderable;
    return this;
  }

   /**
   * Indicates whether values in the column can be reordered. Read-only.
   * @return isReorderable
  **/
  public Boolean isIsReorderable() {
    return isReorderable;
  }

  public void setIsReorderable(Boolean isReorderable) {
    this.isReorderable = isReorderable;
  }

  public MicrosoftGraphColumnDefinition isSealed(Boolean isSealed) {
    this.isSealed = isSealed;
    return this;
  }

   /**
   * Specifies whether the column can be changed.
   * @return isSealed
  **/
  public Boolean isIsSealed() {
    return isSealed;
  }

  public void setIsSealed(Boolean isSealed) {
    this.isSealed = isSealed;
  }

  public MicrosoftGraphColumnDefinition lookup(MicrosoftGraphLookupColumn lookup) {
    this.lookup = lookup;
    return this;
  }

   /**
   * Get lookup
   * @return lookup
  **/
  public MicrosoftGraphLookupColumn getLookup() {
    return lookup;
  }

  public void setLookup(MicrosoftGraphLookupColumn lookup) {
    this.lookup = lookup;
  }

  public MicrosoftGraphColumnDefinition name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The API-facing name of the column as it appears in the [fields][] on a [listItem][]. For the user-facing name, see displayName.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftGraphColumnDefinition number(MicrosoftGraphNumberColumn number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public MicrosoftGraphNumberColumn getNumber() {
    return number;
  }

  public void setNumber(MicrosoftGraphNumberColumn number) {
    this.number = number;
  }

  public MicrosoftGraphColumnDefinition personOrGroup(MicrosoftGraphPersonOrGroupColumn personOrGroup) {
    this.personOrGroup = personOrGroup;
    return this;
  }

   /**
   * Get personOrGroup
   * @return personOrGroup
  **/
  public MicrosoftGraphPersonOrGroupColumn getPersonOrGroup() {
    return personOrGroup;
  }

  public void setPersonOrGroup(MicrosoftGraphPersonOrGroupColumn personOrGroup) {
    this.personOrGroup = personOrGroup;
  }

  public MicrosoftGraphColumnDefinition propagateChanges(Boolean propagateChanges) {
    this.propagateChanges = propagateChanges;
    return this;
  }

   /**
   * If &#x27;true&#x27;, changes to this column will be propagated to lists that implement the column.
   * @return propagateChanges
  **/
  public Boolean isPropagateChanges() {
    return propagateChanges;
  }

  public void setPropagateChanges(Boolean propagateChanges) {
    this.propagateChanges = propagateChanges;
  }

  public MicrosoftGraphColumnDefinition readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Specifies whether the column values can be modified.
   * @return readOnly
  **/
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public MicrosoftGraphColumnDefinition required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Specifies whether the column value isn&#x27;t optional.
   * @return required
  **/
  public Boolean isRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }

  public MicrosoftGraphColumnDefinition sourceContentType(MicrosoftGraphContentTypeInfo sourceContentType) {
    this.sourceContentType = sourceContentType;
    return this;
  }

   /**
   * Get sourceContentType
   * @return sourceContentType
  **/
  public MicrosoftGraphContentTypeInfo getSourceContentType() {
    return sourceContentType;
  }

  public void setSourceContentType(MicrosoftGraphContentTypeInfo sourceContentType) {
    this.sourceContentType = sourceContentType;
  }

  public MicrosoftGraphColumnDefinition term(MicrosoftGraphTermColumn term) {
    this.term = term;
    return this;
  }

   /**
   * Get term
   * @return term
  **/
  public MicrosoftGraphTermColumn getTerm() {
    return term;
  }

  public void setTerm(MicrosoftGraphTermColumn term) {
    this.term = term;
  }

  public MicrosoftGraphColumnDefinition text(MicrosoftGraphTextColumn text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public MicrosoftGraphTextColumn getText() {
    return text;
  }

  public void setText(MicrosoftGraphTextColumn text) {
    this.text = text;
  }

  public MicrosoftGraphColumnDefinition thumbnail(MicrosoftGraphThumbnailColumn thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  public MicrosoftGraphThumbnailColumn getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(MicrosoftGraphThumbnailColumn thumbnail) {
    this.thumbnail = thumbnail;
  }

  public MicrosoftGraphColumnDefinition type(MicrosoftGraphColumnTypes type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public MicrosoftGraphColumnTypes getType() {
    return type;
  }

  public void setType(MicrosoftGraphColumnTypes type) {
    this.type = type;
  }

  public MicrosoftGraphColumnDefinition validation(MicrosoftGraphColumnValidation validation) {
    this.validation = validation;
    return this;
  }

   /**
   * Get validation
   * @return validation
  **/
  public MicrosoftGraphColumnValidation getValidation() {
    return validation;
  }

  public void setValidation(MicrosoftGraphColumnValidation validation) {
    this.validation = validation;
  }

  public MicrosoftGraphColumnDefinition sourceColumn(MicrosoftGraphColumnDefinition sourceColumn) {
    this.sourceColumn = sourceColumn;
    return this;
  }

   /**
   * Get sourceColumn
   * @return sourceColumn
  **/
  public MicrosoftGraphColumnDefinition getSourceColumn() {
    return sourceColumn;
  }

  public void setSourceColumn(MicrosoftGraphColumnDefinition sourceColumn) {
    this.sourceColumn = sourceColumn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphColumnDefinition microsoftGraphColumnDefinition = (MicrosoftGraphColumnDefinition) o;
    return Objects.equals(this._boolean, microsoftGraphColumnDefinition._boolean) &&
        Objects.equals(this.calculated, microsoftGraphColumnDefinition.calculated) &&
        Objects.equals(this.choice, microsoftGraphColumnDefinition.choice) &&
        Objects.equals(this.columnGroup, microsoftGraphColumnDefinition.columnGroup) &&
        Objects.equals(this.contentApprovalStatus, microsoftGraphColumnDefinition.contentApprovalStatus) &&
        Objects.equals(this.currency, microsoftGraphColumnDefinition.currency) &&
        Objects.equals(this.dateTime, microsoftGraphColumnDefinition.dateTime) &&
        Objects.equals(this.defaultValue, microsoftGraphColumnDefinition.defaultValue) &&
        Objects.equals(this.description, microsoftGraphColumnDefinition.description) &&
        Objects.equals(this.displayName, microsoftGraphColumnDefinition.displayName) &&
        Objects.equals(this.enforceUniqueValues, microsoftGraphColumnDefinition.enforceUniqueValues) &&
        Objects.equals(this.geolocation, microsoftGraphColumnDefinition.geolocation) &&
        Objects.equals(this.hidden, microsoftGraphColumnDefinition.hidden) &&
        Objects.equals(this.hyperlinkOrPicture, microsoftGraphColumnDefinition.hyperlinkOrPicture) &&
        Objects.equals(this.indexed, microsoftGraphColumnDefinition.indexed) &&
        Objects.equals(this.isDeletable, microsoftGraphColumnDefinition.isDeletable) &&
        Objects.equals(this.isReorderable, microsoftGraphColumnDefinition.isReorderable) &&
        Objects.equals(this.isSealed, microsoftGraphColumnDefinition.isSealed) &&
        Objects.equals(this.lookup, microsoftGraphColumnDefinition.lookup) &&
        Objects.equals(this.name, microsoftGraphColumnDefinition.name) &&
        Objects.equals(this.number, microsoftGraphColumnDefinition.number) &&
        Objects.equals(this.personOrGroup, microsoftGraphColumnDefinition.personOrGroup) &&
        Objects.equals(this.propagateChanges, microsoftGraphColumnDefinition.propagateChanges) &&
        Objects.equals(this.readOnly, microsoftGraphColumnDefinition.readOnly) &&
        Objects.equals(this.required, microsoftGraphColumnDefinition.required) &&
        Objects.equals(this.sourceContentType, microsoftGraphColumnDefinition.sourceContentType) &&
        Objects.equals(this.term, microsoftGraphColumnDefinition.term) &&
        Objects.equals(this.text, microsoftGraphColumnDefinition.text) &&
        Objects.equals(this.thumbnail, microsoftGraphColumnDefinition.thumbnail) &&
        Objects.equals(this.type, microsoftGraphColumnDefinition.type) &&
        Objects.equals(this.validation, microsoftGraphColumnDefinition.validation) &&
        Objects.equals(this.sourceColumn, microsoftGraphColumnDefinition.sourceColumn) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_boolean, calculated, choice, columnGroup, contentApprovalStatus, currency, dateTime, defaultValue, description, displayName, enforceUniqueValues, geolocation, hidden, hyperlinkOrPicture, indexed, isDeletable, isReorderable, isSealed, lookup, name, number, personOrGroup, propagateChanges, readOnly, required, sourceContentType, term, text, thumbnail, type, validation, sourceColumn, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphColumnDefinition {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    _boolean: ").append(toIndentedString(_boolean)).append("\n");
    sb.append("    calculated: ").append(toIndentedString(calculated)).append("\n");
    sb.append("    choice: ").append(toIndentedString(choice)).append("\n");
    sb.append("    columnGroup: ").append(toIndentedString(columnGroup)).append("\n");
    sb.append("    contentApprovalStatus: ").append(toIndentedString(contentApprovalStatus)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    enforceUniqueValues: ").append(toIndentedString(enforceUniqueValues)).append("\n");
    sb.append("    geolocation: ").append(toIndentedString(geolocation)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    hyperlinkOrPicture: ").append(toIndentedString(hyperlinkOrPicture)).append("\n");
    sb.append("    indexed: ").append(toIndentedString(indexed)).append("\n");
    sb.append("    isDeletable: ").append(toIndentedString(isDeletable)).append("\n");
    sb.append("    isReorderable: ").append(toIndentedString(isReorderable)).append("\n");
    sb.append("    isSealed: ").append(toIndentedString(isSealed)).append("\n");
    sb.append("    lookup: ").append(toIndentedString(lookup)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    personOrGroup: ").append(toIndentedString(personOrGroup)).append("\n");
    sb.append("    propagateChanges: ").append(toIndentedString(propagateChanges)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    sourceContentType: ").append(toIndentedString(sourceContentType)).append("\n");
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    validation: ").append(toIndentedString(validation)).append("\n");
    sb.append("    sourceColumn: ").append(toIndentedString(sourceColumn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
