/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphChangeTrackedEntity;
import com.microsoft.graph.MicrosoftGraphIdentitySet;
import com.microsoft.graph.MicrosoftGraphShiftItem;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphShift
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphShift extends MicrosoftGraphChangeTrackedEntity {
  @JsonProperty("draftShift")
  private MicrosoftGraphShiftItem draftShift = null;

  @JsonProperty("schedulingGroupId")
  private String schedulingGroupId = null;

  @JsonProperty("sharedShift")
  private MicrosoftGraphShiftItem sharedShift = null;

  @JsonProperty("userId")
  private String userId = null;

  public MicrosoftGraphShift draftShift(MicrosoftGraphShiftItem draftShift) {
    this.draftShift = draftShift;
    return this;
  }

   /**
   * Get draftShift
   * @return draftShift
  **/
  public MicrosoftGraphShiftItem getDraftShift() {
    return draftShift;
  }

  public void setDraftShift(MicrosoftGraphShiftItem draftShift) {
    this.draftShift = draftShift;
  }

  public MicrosoftGraphShift schedulingGroupId(String schedulingGroupId) {
    this.schedulingGroupId = schedulingGroupId;
    return this;
  }

   /**
   * ID of the scheduling group the shift is part of. Required.
   * @return schedulingGroupId
  **/
  public String getSchedulingGroupId() {
    return schedulingGroupId;
  }

  public void setSchedulingGroupId(String schedulingGroupId) {
    this.schedulingGroupId = schedulingGroupId;
  }

  public MicrosoftGraphShift sharedShift(MicrosoftGraphShiftItem sharedShift) {
    this.sharedShift = sharedShift;
    return this;
  }

   /**
   * Get sharedShift
   * @return sharedShift
  **/
  public MicrosoftGraphShiftItem getSharedShift() {
    return sharedShift;
  }

  public void setSharedShift(MicrosoftGraphShiftItem sharedShift) {
    this.sharedShift = sharedShift;
  }

  public MicrosoftGraphShift userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * ID of the user assigned to the shift. Required.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphShift microsoftGraphShift = (MicrosoftGraphShift) o;
    return Objects.equals(this.draftShift, microsoftGraphShift.draftShift) &&
        Objects.equals(this.schedulingGroupId, microsoftGraphShift.schedulingGroupId) &&
        Objects.equals(this.sharedShift, microsoftGraphShift.sharedShift) &&
        Objects.equals(this.userId, microsoftGraphShift.userId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(draftShift, schedulingGroupId, sharedShift, userId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphShift {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    draftShift: ").append(toIndentedString(draftShift)).append("\n");
    sb.append("    schedulingGroupId: ").append(toIndentedString(schedulingGroupId)).append("\n");
    sb.append("    sharedShift: ").append(toIndentedString(sharedShift)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
