/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphConversationMember;
import com.microsoft.graph.MicrosoftGraphTeam;
import com.microsoft.graph.MicrosoftGraphTeamInfo;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphSharedWithChannelTeamInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphSharedWithChannelTeamInfo extends MicrosoftGraphTeamInfo {
  @JsonProperty("isHostTeam")
  private Boolean isHostTeam = null;

  @JsonProperty("allowedMembers")
  private List<MicrosoftGraphConversationMember> allowedMembers = null;

  public MicrosoftGraphSharedWithChannelTeamInfo isHostTeam(Boolean isHostTeam) {
    this.isHostTeam = isHostTeam;
    return this;
  }

   /**
   * Indicates whether the team is the host of the channel.
   * @return isHostTeam
  **/
  public Boolean isIsHostTeam() {
    return isHostTeam;
  }

  public void setIsHostTeam(Boolean isHostTeam) {
    this.isHostTeam = isHostTeam;
  }

  public MicrosoftGraphSharedWithChannelTeamInfo allowedMembers(List<MicrosoftGraphConversationMember> allowedMembers) {
    this.allowedMembers = allowedMembers;
    return this;
  }

  public MicrosoftGraphSharedWithChannelTeamInfo addAllowedMembersItem(MicrosoftGraphConversationMember allowedMembersItem) {
    if (this.allowedMembers == null) {
      this.allowedMembers = new ArrayList<>();
    }
    this.allowedMembers.add(allowedMembersItem);
    return this;
  }

   /**
   * A collection of team members who have access to the shared channel.
   * @return allowedMembers
  **/
  public List<MicrosoftGraphConversationMember> getAllowedMembers() {
    return allowedMembers;
  }

  public void setAllowedMembers(List<MicrosoftGraphConversationMember> allowedMembers) {
    this.allowedMembers = allowedMembers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphSharedWithChannelTeamInfo microsoftGraphSharedWithChannelTeamInfo = (MicrosoftGraphSharedWithChannelTeamInfo) o;
    return Objects.equals(this.isHostTeam, microsoftGraphSharedWithChannelTeamInfo.isHostTeam) &&
        Objects.equals(this.allowedMembers, microsoftGraphSharedWithChannelTeamInfo.allowedMembers) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isHostTeam, allowedMembers, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphSharedWithChannelTeamInfo {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    isHostTeam: ").append(toIndentedString(isHostTeam)).append("\n");
    sb.append("    allowedMembers: ").append(toIndentedString(allowedMembers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
