/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphChatViewpoint
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphChatViewpoint {
  @JsonProperty("isHidden")
  private Boolean isHidden = null;

  @JsonProperty("lastMessageReadDateTime")
  private OffsetDateTime lastMessageReadDateTime = null;

  public MicrosoftGraphChatViewpoint isHidden(Boolean isHidden) {
    this.isHidden = isHidden;
    return this;
  }

   /**
   * Indicates whether the chat is hidden for the current user.
   * @return isHidden
  **/
  public Boolean isIsHidden() {
    return isHidden;
  }

  public void setIsHidden(Boolean isHidden) {
    this.isHidden = isHidden;
  }

  public MicrosoftGraphChatViewpoint lastMessageReadDateTime(OffsetDateTime lastMessageReadDateTime) {
    this.lastMessageReadDateTime = lastMessageReadDateTime;
    return this;
  }

   /**
   * Represents the dateTime up until which the current user has read chatMessages in a specific chat.
   * @return lastMessageReadDateTime
  **/
  public OffsetDateTime getLastMessageReadDateTime() {
    return lastMessageReadDateTime;
  }

  public void setLastMessageReadDateTime(OffsetDateTime lastMessageReadDateTime) {
    this.lastMessageReadDateTime = lastMessageReadDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphChatViewpoint microsoftGraphChatViewpoint = (MicrosoftGraphChatViewpoint) o;
    return Objects.equals(this.isHidden, microsoftGraphChatViewpoint.isHidden) &&
        Objects.equals(this.lastMessageReadDateTime, microsoftGraphChatViewpoint.lastMessageReadDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isHidden, lastMessageReadDateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphChatViewpoint {\n");
    
    sb.append("    isHidden: ").append(toIndentedString(isHidden)).append("\n");
    sb.append("    lastMessageReadDateTime: ").append(toIndentedString(lastMessageReadDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
