/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphAttendeeBase;
import com.microsoft.graph.MicrosoftGraphAttendeeType;
import com.microsoft.graph.MicrosoftGraphResponseStatus;
import com.microsoft.graph.MicrosoftGraphTimeSlot;

/**
 * MicrosoftGraphAttendee
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphAttendee extends MicrosoftGraphAttendeeBase {
  @JsonProperty("proposedNewTime")
  private MicrosoftGraphTimeSlot proposedNewTime = null;

  @JsonProperty("status")
  private MicrosoftGraphResponseStatus status = null;

  public MicrosoftGraphAttendee proposedNewTime(MicrosoftGraphTimeSlot proposedNewTime) {
    this.proposedNewTime = proposedNewTime;
    return this;
  }

   /**
   * Get proposedNewTime
   * @return proposedNewTime
  **/
  public MicrosoftGraphTimeSlot getProposedNewTime() {
    return proposedNewTime;
  }

  public void setProposedNewTime(MicrosoftGraphTimeSlot proposedNewTime) {
    this.proposedNewTime = proposedNewTime;
  }

  public MicrosoftGraphAttendee status(MicrosoftGraphResponseStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public MicrosoftGraphResponseStatus getStatus() {
    return status;
  }

  public void setStatus(MicrosoftGraphResponseStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphAttendee microsoftGraphAttendee = (MicrosoftGraphAttendee) o;
    return Objects.equals(this.proposedNewTime, microsoftGraphAttendee.proposedNewTime) &&
        Objects.equals(this.status, microsoftGraphAttendee.status) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proposedNewTime, status, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphAttendee {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    proposedNewTime: ").append(toIndentedString(proposedNewTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
