/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphDayOfWeek;
import com.microsoft.graph.MicrosoftGraphTimeZoneBase;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphWorkingHours
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkingHours {
  @JsonProperty("daysOfWeek")
  private List<MicrosoftGraphDayOfWeek> daysOfWeek = null;

  @JsonProperty("endTime")
  private String endTime = null;

  @JsonProperty("startTime")
  private String startTime = null;

  @JsonProperty("timeZone")
  private MicrosoftGraphTimeZoneBase timeZone = null;

  public MicrosoftGraphWorkingHours daysOfWeek(List<MicrosoftGraphDayOfWeek> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
    return this;
  }

  public MicrosoftGraphWorkingHours addDaysOfWeekItem(MicrosoftGraphDayOfWeek daysOfWeekItem) {
    if (this.daysOfWeek == null) {
      this.daysOfWeek = new ArrayList<>();
    }
    this.daysOfWeek.add(daysOfWeekItem);
    return this;
  }

   /**
   * The days of the week on which the user works.
   * @return daysOfWeek
  **/
  public List<MicrosoftGraphDayOfWeek> getDaysOfWeek() {
    return daysOfWeek;
  }

  public void setDaysOfWeek(List<MicrosoftGraphDayOfWeek> daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
  }

  public MicrosoftGraphWorkingHours endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * The time of the day that the user stops working.
   * @return endTime
  **/
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public MicrosoftGraphWorkingHours startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * The time of the day that the user starts working.
   * @return startTime
  **/
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public MicrosoftGraphWorkingHours timeZone(MicrosoftGraphTimeZoneBase timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  public MicrosoftGraphTimeZoneBase getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(MicrosoftGraphTimeZoneBase timeZone) {
    this.timeZone = timeZone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkingHours microsoftGraphWorkingHours = (MicrosoftGraphWorkingHours) o;
    return Objects.equals(this.daysOfWeek, microsoftGraphWorkingHours.daysOfWeek) &&
        Objects.equals(this.endTime, microsoftGraphWorkingHours.endTime) &&
        Objects.equals(this.startTime, microsoftGraphWorkingHours.startTime) &&
        Objects.equals(this.timeZone, microsoftGraphWorkingHours.timeZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daysOfWeek, endTime, startTime, timeZone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkingHours {\n");
    
    sb.append("    daysOfWeek: ").append(toIndentedString(daysOfWeek)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
