/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphAudioConferencing
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphAudioConferencing {
  @JsonProperty("conferenceId")
  private String conferenceId = null;

  @JsonProperty("dialinUrl")
  private String dialinUrl = null;

  @JsonProperty("tollFreeNumber")
  private String tollFreeNumber = null;

  @JsonProperty("tollFreeNumbers")
  private List<String> tollFreeNumbers = null;

  @JsonProperty("tollNumber")
  private String tollNumber = null;

  @JsonProperty("tollNumbers")
  private List<String> tollNumbers = null;

  public MicrosoftGraphAudioConferencing conferenceId(String conferenceId) {
    this.conferenceId = conferenceId;
    return this;
  }

   /**
   * The conference id of the online meeting.
   * @return conferenceId
  **/
  public String getConferenceId() {
    return conferenceId;
  }

  public void setConferenceId(String conferenceId) {
    this.conferenceId = conferenceId;
  }

  public MicrosoftGraphAudioConferencing dialinUrl(String dialinUrl) {
    this.dialinUrl = dialinUrl;
    return this;
  }

   /**
   * A URL to the externally-accessible web page that contains dial-in information.
   * @return dialinUrl
  **/
  public String getDialinUrl() {
    return dialinUrl;
  }

  public void setDialinUrl(String dialinUrl) {
    this.dialinUrl = dialinUrl;
  }

  public MicrosoftGraphAudioConferencing tollFreeNumber(String tollFreeNumber) {
    this.tollFreeNumber = tollFreeNumber;
    return this;
  }

   /**
   * Get tollFreeNumber
   * @return tollFreeNumber
  **/
  public String getTollFreeNumber() {
    return tollFreeNumber;
  }

  public void setTollFreeNumber(String tollFreeNumber) {
    this.tollFreeNumber = tollFreeNumber;
  }

  public MicrosoftGraphAudioConferencing tollFreeNumbers(List<String> tollFreeNumbers) {
    this.tollFreeNumbers = tollFreeNumbers;
    return this;
  }

  public MicrosoftGraphAudioConferencing addTollFreeNumbersItem(String tollFreeNumbersItem) {
    if (this.tollFreeNumbers == null) {
      this.tollFreeNumbers = new ArrayList<>();
    }
    this.tollFreeNumbers.add(tollFreeNumbersItem);
    return this;
  }

   /**
   * List of toll-free numbers that are displayed in the meeting invite.
   * @return tollFreeNumbers
  **/
  public List<String> getTollFreeNumbers() {
    return tollFreeNumbers;
  }

  public void setTollFreeNumbers(List<String> tollFreeNumbers) {
    this.tollFreeNumbers = tollFreeNumbers;
  }

  public MicrosoftGraphAudioConferencing tollNumber(String tollNumber) {
    this.tollNumber = tollNumber;
    return this;
  }

   /**
   * Get tollNumber
   * @return tollNumber
  **/
  public String getTollNumber() {
    return tollNumber;
  }

  public void setTollNumber(String tollNumber) {
    this.tollNumber = tollNumber;
  }

  public MicrosoftGraphAudioConferencing tollNumbers(List<String> tollNumbers) {
    this.tollNumbers = tollNumbers;
    return this;
  }

  public MicrosoftGraphAudioConferencing addTollNumbersItem(String tollNumbersItem) {
    if (this.tollNumbers == null) {
      this.tollNumbers = new ArrayList<>();
    }
    this.tollNumbers.add(tollNumbersItem);
    return this;
  }

   /**
   * List of toll numbers that are displayed in the meeting invite.
   * @return tollNumbers
  **/
  public List<String> getTollNumbers() {
    return tollNumbers;
  }

  public void setTollNumbers(List<String> tollNumbers) {
    this.tollNumbers = tollNumbers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphAudioConferencing microsoftGraphAudioConferencing = (MicrosoftGraphAudioConferencing) o;
    return Objects.equals(this.conferenceId, microsoftGraphAudioConferencing.conferenceId) &&
        Objects.equals(this.dialinUrl, microsoftGraphAudioConferencing.dialinUrl) &&
        Objects.equals(this.tollFreeNumber, microsoftGraphAudioConferencing.tollFreeNumber) &&
        Objects.equals(this.tollFreeNumbers, microsoftGraphAudioConferencing.tollFreeNumbers) &&
        Objects.equals(this.tollNumber, microsoftGraphAudioConferencing.tollNumber) &&
        Objects.equals(this.tollNumbers, microsoftGraphAudioConferencing.tollNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conferenceId, dialinUrl, tollFreeNumber, tollFreeNumbers, tollNumber, tollNumbers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphAudioConferencing {\n");
    
    sb.append("    conferenceId: ").append(toIndentedString(conferenceId)).append("\n");
    sb.append("    dialinUrl: ").append(toIndentedString(dialinUrl)).append("\n");
    sb.append("    tollFreeNumber: ").append(toIndentedString(tollFreeNumber)).append("\n");
    sb.append("    tollFreeNumbers: ").append(toIndentedString(tollFreeNumbers)).append("\n");
    sb.append("    tollNumber: ").append(toIndentedString(tollNumber)).append("\n");
    sb.append("    tollNumbers: ").append(toIndentedString(tollNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
