/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets microsoft.graph.authenticationMethodSignInState
 */
public enum MicrosoftGraphAuthenticationMethodSignInState {
  NOTSUPPORTED("notSupported"),
  NOTALLOWEDBYPOLICY("notAllowedByPolicy"),
  NOTENABLED("notEnabled"),
  PHONENUMBERNOTUNIQUE("phoneNumberNotUnique"),
  READY("ready"),
  NOTCONFIGURED("notConfigured"),
  UNKNOWNFUTUREVALUE("unknownFutureValue");

  private String value;

  MicrosoftGraphAuthenticationMethodSignInState(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MicrosoftGraphAuthenticationMethodSignInState fromValue(String input) {
    for (MicrosoftGraphAuthenticationMethodSignInState b : MicrosoftGraphAuthenticationMethodSignInState.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
