/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphChecklistItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphChecklistItem extends MicrosoftGraphEntity {
  @JsonProperty("checkedDateTime")
  private OffsetDateTime checkedDateTime = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("isChecked")
  private Boolean isChecked = null;

  public MicrosoftGraphChecklistItem checkedDateTime(OffsetDateTime checkedDateTime) {
    this.checkedDateTime = checkedDateTime;
    return this;
  }

   /**
   * The date and time when the checklistItem was finished.
   * @return checkedDateTime
  **/
  public OffsetDateTime getCheckedDateTime() {
    return checkedDateTime;
  }

  public void setCheckedDateTime(OffsetDateTime checkedDateTime) {
    this.checkedDateTime = checkedDateTime;
  }

  public MicrosoftGraphChecklistItem createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * The date and time when the checklistItem was created.
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphChecklistItem displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Field indicating the title of checklistItem.
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MicrosoftGraphChecklistItem isChecked(Boolean isChecked) {
    this.isChecked = isChecked;
    return this;
  }

   /**
   * State indicating whether the item is checked off or not.
   * @return isChecked
  **/
  public Boolean isIsChecked() {
    return isChecked;
  }

  public void setIsChecked(Boolean isChecked) {
    this.isChecked = isChecked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphChecklistItem microsoftGraphChecklistItem = (MicrosoftGraphChecklistItem) o;
    return Objects.equals(this.checkedDateTime, microsoftGraphChecklistItem.checkedDateTime) &&
        Objects.equals(this.createdDateTime, microsoftGraphChecklistItem.createdDateTime) &&
        Objects.equals(this.displayName, microsoftGraphChecklistItem.displayName) &&
        Objects.equals(this.isChecked, microsoftGraphChecklistItem.isChecked) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkedDateTime, createdDateTime, displayName, isChecked, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphChecklistItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    checkedDateTime: ").append(toIndentedString(checkedDateTime)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    isChecked: ").append(toIndentedString(isChecked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
