/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphAttendanceInterval;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphIdentity;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphAttendanceRecord
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphAttendanceRecord extends MicrosoftGraphEntity {
  @JsonProperty("attendanceIntervals")
  private List<MicrosoftGraphAttendanceInterval> attendanceIntervals = null;

  @JsonProperty("emailAddress")
  private String emailAddress = null;

  @JsonProperty("identity")
  private MicrosoftGraphIdentity identity = null;

  @JsonProperty("role")
  private String role = null;

  @JsonProperty("totalAttendanceInSeconds")
  private Integer totalAttendanceInSeconds = null;

  public MicrosoftGraphAttendanceRecord attendanceIntervals(List<MicrosoftGraphAttendanceInterval> attendanceIntervals) {
    this.attendanceIntervals = attendanceIntervals;
    return this;
  }

  public MicrosoftGraphAttendanceRecord addAttendanceIntervalsItem(MicrosoftGraphAttendanceInterval attendanceIntervalsItem) {
    if (this.attendanceIntervals == null) {
      this.attendanceIntervals = new ArrayList<>();
    }
    this.attendanceIntervals.add(attendanceIntervalsItem);
    return this;
  }

   /**
   * List of time periods between joining and leaving a meeting.
   * @return attendanceIntervals
  **/
  public List<MicrosoftGraphAttendanceInterval> getAttendanceIntervals() {
    return attendanceIntervals;
  }

  public void setAttendanceIntervals(List<MicrosoftGraphAttendanceInterval> attendanceIntervals) {
    this.attendanceIntervals = attendanceIntervals;
  }

  public MicrosoftGraphAttendanceRecord emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Email address of the user associated with this atttendance record.
   * @return emailAddress
  **/
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public MicrosoftGraphAttendanceRecord identity(MicrosoftGraphIdentity identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Get identity
   * @return identity
  **/
  public MicrosoftGraphIdentity getIdentity() {
    return identity;
  }

  public void setIdentity(MicrosoftGraphIdentity identity) {
    this.identity = identity;
  }

  public MicrosoftGraphAttendanceRecord role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Role of the attendee. Possible values are: None, Attendee, Presenter, and Organizer.
   * @return role
  **/
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public MicrosoftGraphAttendanceRecord totalAttendanceInSeconds(Integer totalAttendanceInSeconds) {
    this.totalAttendanceInSeconds = totalAttendanceInSeconds;
    return this;
  }

   /**
   * Total duration of the attendances in seconds.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return totalAttendanceInSeconds
  **/
  public Integer getTotalAttendanceInSeconds() {
    return totalAttendanceInSeconds;
  }

  public void setTotalAttendanceInSeconds(Integer totalAttendanceInSeconds) {
    this.totalAttendanceInSeconds = totalAttendanceInSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphAttendanceRecord microsoftGraphAttendanceRecord = (MicrosoftGraphAttendanceRecord) o;
    return Objects.equals(this.attendanceIntervals, microsoftGraphAttendanceRecord.attendanceIntervals) &&
        Objects.equals(this.emailAddress, microsoftGraphAttendanceRecord.emailAddress) &&
        Objects.equals(this.identity, microsoftGraphAttendanceRecord.identity) &&
        Objects.equals(this.role, microsoftGraphAttendanceRecord.role) &&
        Objects.equals(this.totalAttendanceInSeconds, microsoftGraphAttendanceRecord.totalAttendanceInSeconds) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attendanceIntervals, emailAddress, identity, role, totalAttendanceInSeconds, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphAttendanceRecord {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    attendanceIntervals: ").append(toIndentedString(attendanceIntervals)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    totalAttendanceInSeconds: ").append(toIndentedString(totalAttendanceInSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
