/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphPublicationFacet
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphPublicationFacet {
  @JsonProperty("level")
  private String level = null;

  @JsonProperty("versionId")
  private String versionId = null;

  public MicrosoftGraphPublicationFacet level(String level) {
    this.level = level;
    return this;
  }

   /**
   * The state of publication for this document. Either published or checkout. Read-only.
   * @return level
  **/
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public MicrosoftGraphPublicationFacet versionId(String versionId) {
    this.versionId = versionId;
    return this;
  }

   /**
   * The unique identifier for the version that is visible to the current caller. Read-only.
   * @return versionId
  **/
  public String getVersionId() {
    return versionId;
  }

  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphPublicationFacet microsoftGraphPublicationFacet = (MicrosoftGraphPublicationFacet) o;
    return Objects.equals(this.level, microsoftGraphPublicationFacet.level) &&
        Objects.equals(this.versionId, microsoftGraphPublicationFacet.versionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level, versionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphPublicationFacet {\n");
    
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
