/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphAgreementAcceptanceState;
import com.microsoft.graph.MicrosoftGraphEntity;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphAgreementAcceptance
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphAgreementAcceptance extends MicrosoftGraphEntity {
  @JsonProperty("agreementFileId")
  private String agreementFileId = null;

  @JsonProperty("agreementId")
  private String agreementId = null;

  @JsonProperty("deviceDisplayName")
  private String deviceDisplayName = null;

  @JsonProperty("deviceId")
  private String deviceId = null;

  @JsonProperty("deviceOSType")
  private String deviceOSType = null;

  @JsonProperty("deviceOSVersion")
  private String deviceOSVersion = null;

  @JsonProperty("expirationDateTime")
  private OffsetDateTime expirationDateTime = null;

  @JsonProperty("recordedDateTime")
  private OffsetDateTime recordedDateTime = null;

  @JsonProperty("state")
  private MicrosoftGraphAgreementAcceptanceState state = null;

  @JsonProperty("userDisplayName")
  private String userDisplayName = null;

  @JsonProperty("userEmail")
  private String userEmail = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("userPrincipalName")
  private String userPrincipalName = null;

  public MicrosoftGraphAgreementAcceptance agreementFileId(String agreementFileId) {
    this.agreementFileId = agreementFileId;
    return this;
  }

   /**
   * The identifier of the agreement file accepted by the user.
   * @return agreementFileId
  **/
  public String getAgreementFileId() {
    return agreementFileId;
  }

  public void setAgreementFileId(String agreementFileId) {
    this.agreementFileId = agreementFileId;
  }

  public MicrosoftGraphAgreementAcceptance agreementId(String agreementId) {
    this.agreementId = agreementId;
    return this;
  }

   /**
   * The identifier of the agreement.
   * @return agreementId
  **/
  public String getAgreementId() {
    return agreementId;
  }

  public void setAgreementId(String agreementId) {
    this.agreementId = agreementId;
  }

  public MicrosoftGraphAgreementAcceptance deviceDisplayName(String deviceDisplayName) {
    this.deviceDisplayName = deviceDisplayName;
    return this;
  }

   /**
   * The display name of the device used for accepting the agreement.
   * @return deviceDisplayName
  **/
  public String getDeviceDisplayName() {
    return deviceDisplayName;
  }

  public void setDeviceDisplayName(String deviceDisplayName) {
    this.deviceDisplayName = deviceDisplayName;
  }

  public MicrosoftGraphAgreementAcceptance deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * The unique identifier of the device used for accepting the agreement. Supports $filter (eq) and eq for null values.
   * @return deviceId
  **/
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public MicrosoftGraphAgreementAcceptance deviceOSType(String deviceOSType) {
    this.deviceOSType = deviceOSType;
    return this;
  }

   /**
   * The operating system used to accept the agreement.
   * @return deviceOSType
  **/
  public String getDeviceOSType() {
    return deviceOSType;
  }

  public void setDeviceOSType(String deviceOSType) {
    this.deviceOSType = deviceOSType;
  }

  public MicrosoftGraphAgreementAcceptance deviceOSVersion(String deviceOSVersion) {
    this.deviceOSVersion = deviceOSVersion;
    return this;
  }

   /**
   * The operating system version of the device used to accept the agreement.
   * @return deviceOSVersion
  **/
  public String getDeviceOSVersion() {
    return deviceOSVersion;
  }

  public void setDeviceOSVersion(String deviceOSVersion) {
    this.deviceOSVersion = deviceOSVersion;
  }

  public MicrosoftGraphAgreementAcceptance expirationDateTime(OffsetDateTime expirationDateTime) {
    this.expirationDateTime = expirationDateTime;
    return this;
  }

   /**
   * The expiration date time of the acceptance. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Supports $filter (eq, ge, le) and eq for null values.
   * @return expirationDateTime
  **/
  public OffsetDateTime getExpirationDateTime() {
    return expirationDateTime;
  }

  public void setExpirationDateTime(OffsetDateTime expirationDateTime) {
    this.expirationDateTime = expirationDateTime;
  }

  public MicrosoftGraphAgreementAcceptance recordedDateTime(OffsetDateTime recordedDateTime) {
    this.recordedDateTime = recordedDateTime;
    return this;
  }

   /**
   * The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.
   * @return recordedDateTime
  **/
  public OffsetDateTime getRecordedDateTime() {
    return recordedDateTime;
  }

  public void setRecordedDateTime(OffsetDateTime recordedDateTime) {
    this.recordedDateTime = recordedDateTime;
  }

  public MicrosoftGraphAgreementAcceptance state(MicrosoftGraphAgreementAcceptanceState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public MicrosoftGraphAgreementAcceptanceState getState() {
    return state;
  }

  public void setState(MicrosoftGraphAgreementAcceptanceState state) {
    this.state = state;
  }

  public MicrosoftGraphAgreementAcceptance userDisplayName(String userDisplayName) {
    this.userDisplayName = userDisplayName;
    return this;
  }

   /**
   * Display name of the user when the acceptance was recorded.
   * @return userDisplayName
  **/
  public String getUserDisplayName() {
    return userDisplayName;
  }

  public void setUserDisplayName(String userDisplayName) {
    this.userDisplayName = userDisplayName;
  }

  public MicrosoftGraphAgreementAcceptance userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Email of the user when the acceptance was recorded.
   * @return userEmail
  **/
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public MicrosoftGraphAgreementAcceptance userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The identifier of the user who accepted the agreement. Supports $filter (eq).
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public MicrosoftGraphAgreementAcceptance userPrincipalName(String userPrincipalName) {
    this.userPrincipalName = userPrincipalName;
    return this;
  }

   /**
   * UPN of the user when the acceptance was recorded.
   * @return userPrincipalName
  **/
  public String getUserPrincipalName() {
    return userPrincipalName;
  }

  public void setUserPrincipalName(String userPrincipalName) {
    this.userPrincipalName = userPrincipalName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphAgreementAcceptance microsoftGraphAgreementAcceptance = (MicrosoftGraphAgreementAcceptance) o;
    return Objects.equals(this.agreementFileId, microsoftGraphAgreementAcceptance.agreementFileId) &&
        Objects.equals(this.agreementId, microsoftGraphAgreementAcceptance.agreementId) &&
        Objects.equals(this.deviceDisplayName, microsoftGraphAgreementAcceptance.deviceDisplayName) &&
        Objects.equals(this.deviceId, microsoftGraphAgreementAcceptance.deviceId) &&
        Objects.equals(this.deviceOSType, microsoftGraphAgreementAcceptance.deviceOSType) &&
        Objects.equals(this.deviceOSVersion, microsoftGraphAgreementAcceptance.deviceOSVersion) &&
        Objects.equals(this.expirationDateTime, microsoftGraphAgreementAcceptance.expirationDateTime) &&
        Objects.equals(this.recordedDateTime, microsoftGraphAgreementAcceptance.recordedDateTime) &&
        Objects.equals(this.state, microsoftGraphAgreementAcceptance.state) &&
        Objects.equals(this.userDisplayName, microsoftGraphAgreementAcceptance.userDisplayName) &&
        Objects.equals(this.userEmail, microsoftGraphAgreementAcceptance.userEmail) &&
        Objects.equals(this.userId, microsoftGraphAgreementAcceptance.userId) &&
        Objects.equals(this.userPrincipalName, microsoftGraphAgreementAcceptance.userPrincipalName) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreementFileId, agreementId, deviceDisplayName, deviceId, deviceOSType, deviceOSVersion, expirationDateTime, recordedDateTime, state, userDisplayName, userEmail, userId, userPrincipalName, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphAgreementAcceptance {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    agreementFileId: ").append(toIndentedString(agreementFileId)).append("\n");
    sb.append("    agreementId: ").append(toIndentedString(agreementId)).append("\n");
    sb.append("    deviceDisplayName: ").append(toIndentedString(deviceDisplayName)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    deviceOSType: ").append(toIndentedString(deviceOSType)).append("\n");
    sb.append("    deviceOSVersion: ").append(toIndentedString(deviceOSVersion)).append("\n");
    sb.append("    expirationDateTime: ").append(toIndentedString(expirationDateTime)).append("\n");
    sb.append("    recordedDateTime: ").append(toIndentedString(recordedDateTime)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    userDisplayName: ").append(toIndentedString(userDisplayName)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userPrincipalName: ").append(toIndentedString(userPrincipalName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
