/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphGiphyRatingType;

/**
 * MicrosoftGraphTeamFunSettings
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTeamFunSettings {
  @JsonProperty("allowCustomMemes")
  private Boolean allowCustomMemes = null;

  @JsonProperty("allowGiphy")
  private Boolean allowGiphy = null;

  @JsonProperty("allowStickersAndMemes")
  private Boolean allowStickersAndMemes = null;

  @JsonProperty("giphyContentRating")
  private MicrosoftGraphGiphyRatingType giphyContentRating = null;

  public MicrosoftGraphTeamFunSettings allowCustomMemes(Boolean allowCustomMemes) {
    this.allowCustomMemes = allowCustomMemes;
    return this;
  }

   /**
   * If set to true, enables users to include custom memes.
   * @return allowCustomMemes
  **/
  public Boolean isAllowCustomMemes() {
    return allowCustomMemes;
  }

  public void setAllowCustomMemes(Boolean allowCustomMemes) {
    this.allowCustomMemes = allowCustomMemes;
  }

  public MicrosoftGraphTeamFunSettings allowGiphy(Boolean allowGiphy) {
    this.allowGiphy = allowGiphy;
    return this;
  }

   /**
   * If set to true, enables Giphy use.
   * @return allowGiphy
  **/
  public Boolean isAllowGiphy() {
    return allowGiphy;
  }

  public void setAllowGiphy(Boolean allowGiphy) {
    this.allowGiphy = allowGiphy;
  }

  public MicrosoftGraphTeamFunSettings allowStickersAndMemes(Boolean allowStickersAndMemes) {
    this.allowStickersAndMemes = allowStickersAndMemes;
    return this;
  }

   /**
   * If set to true, enables users to include stickers and memes.
   * @return allowStickersAndMemes
  **/
  public Boolean isAllowStickersAndMemes() {
    return allowStickersAndMemes;
  }

  public void setAllowStickersAndMemes(Boolean allowStickersAndMemes) {
    this.allowStickersAndMemes = allowStickersAndMemes;
  }

  public MicrosoftGraphTeamFunSettings giphyContentRating(MicrosoftGraphGiphyRatingType giphyContentRating) {
    this.giphyContentRating = giphyContentRating;
    return this;
  }

   /**
   * Get giphyContentRating
   * @return giphyContentRating
  **/
  public MicrosoftGraphGiphyRatingType getGiphyContentRating() {
    return giphyContentRating;
  }

  public void setGiphyContentRating(MicrosoftGraphGiphyRatingType giphyContentRating) {
    this.giphyContentRating = giphyContentRating;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTeamFunSettings microsoftGraphTeamFunSettings = (MicrosoftGraphTeamFunSettings) o;
    return Objects.equals(this.allowCustomMemes, microsoftGraphTeamFunSettings.allowCustomMemes) &&
        Objects.equals(this.allowGiphy, microsoftGraphTeamFunSettings.allowGiphy) &&
        Objects.equals(this.allowStickersAndMemes, microsoftGraphTeamFunSettings.allowStickersAndMemes) &&
        Objects.equals(this.giphyContentRating, microsoftGraphTeamFunSettings.giphyContentRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowCustomMemes, allowGiphy, allowStickersAndMemes, giphyContentRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTeamFunSettings {\n");
    
    sb.append("    allowCustomMemes: ").append(toIndentedString(allowCustomMemes)).append("\n");
    sb.append("    allowGiphy: ").append(toIndentedString(allowGiphy)).append("\n");
    sb.append("    allowStickersAndMemes: ").append(toIndentedString(allowStickersAndMemes)).append("\n");
    sb.append("    giphyContentRating: ").append(toIndentedString(giphyContentRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
