/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphChatMessageFromIdentitySet;
import com.microsoft.graph.MicrosoftGraphChatMessageType;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphEventMessageDetail;
import com.microsoft.graph.MicrosoftGraphItemBody;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphChatMessageInfo
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphChatMessageInfo extends MicrosoftGraphEntity {
  @JsonProperty("body")
  private MicrosoftGraphItemBody body = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("eventDetail")
  private MicrosoftGraphEventMessageDetail eventDetail = null;

  @JsonProperty("from")
  private MicrosoftGraphChatMessageFromIdentitySet from = null;

  @JsonProperty("isDeleted")
  private Boolean isDeleted = null;

  @JsonProperty("messageType")
  private MicrosoftGraphChatMessageType messageType = null;

  public MicrosoftGraphChatMessageInfo body(MicrosoftGraphItemBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  public MicrosoftGraphItemBody getBody() {
    return body;
  }

  public void setBody(MicrosoftGraphItemBody body) {
    this.body = body;
  }

  public MicrosoftGraphChatMessageInfo createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Date time object representing the time at which message was created.
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphChatMessageInfo eventDetail(MicrosoftGraphEventMessageDetail eventDetail) {
    this.eventDetail = eventDetail;
    return this;
  }

   /**
   * Get eventDetail
   * @return eventDetail
  **/
  public MicrosoftGraphEventMessageDetail getEventDetail() {
    return eventDetail;
  }

  public void setEventDetail(MicrosoftGraphEventMessageDetail eventDetail) {
    this.eventDetail = eventDetail;
  }

  public MicrosoftGraphChatMessageInfo from(MicrosoftGraphChatMessageFromIdentitySet from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  public MicrosoftGraphChatMessageFromIdentitySet getFrom() {
    return from;
  }

  public void setFrom(MicrosoftGraphChatMessageFromIdentitySet from) {
    this.from = from;
  }

  public MicrosoftGraphChatMessageInfo isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * If set to true, the original message has been deleted.
   * @return isDeleted
  **/
  public Boolean isIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public MicrosoftGraphChatMessageInfo messageType(MicrosoftGraphChatMessageType messageType) {
    this.messageType = messageType;
    return this;
  }

   /**
   * Get messageType
   * @return messageType
  **/
  public MicrosoftGraphChatMessageType getMessageType() {
    return messageType;
  }

  public void setMessageType(MicrosoftGraphChatMessageType messageType) {
    this.messageType = messageType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphChatMessageInfo microsoftGraphChatMessageInfo = (MicrosoftGraphChatMessageInfo) o;
    return Objects.equals(this.body, microsoftGraphChatMessageInfo.body) &&
        Objects.equals(this.createdDateTime, microsoftGraphChatMessageInfo.createdDateTime) &&
        Objects.equals(this.eventDetail, microsoftGraphChatMessageInfo.eventDetail) &&
        Objects.equals(this.from, microsoftGraphChatMessageInfo.from) &&
        Objects.equals(this.isDeleted, microsoftGraphChatMessageInfo.isDeleted) &&
        Objects.equals(this.messageType, microsoftGraphChatMessageInfo.messageType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, createdDateTime, eventDetail, from, isDeleted, messageType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphChatMessageInfo {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    eventDetail: ").append(toIndentedString(eventDetail)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
