/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphTeamMemberSettings
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphTeamMemberSettings {
  @JsonProperty("allowAddRemoveApps")
  private Boolean allowAddRemoveApps = null;

  @JsonProperty("allowCreatePrivateChannels")
  private Boolean allowCreatePrivateChannels = null;

  @JsonProperty("allowCreateUpdateChannels")
  private Boolean allowCreateUpdateChannels = null;

  @JsonProperty("allowCreateUpdateRemoveConnectors")
  private Boolean allowCreateUpdateRemoveConnectors = null;

  @JsonProperty("allowCreateUpdateRemoveTabs")
  private Boolean allowCreateUpdateRemoveTabs = null;

  @JsonProperty("allowDeleteChannels")
  private Boolean allowDeleteChannels = null;

  public MicrosoftGraphTeamMemberSettings allowAddRemoveApps(Boolean allowAddRemoveApps) {
    this.allowAddRemoveApps = allowAddRemoveApps;
    return this;
  }

   /**
   * If set to true, members can add and remove apps.
   * @return allowAddRemoveApps
  **/
  public Boolean isAllowAddRemoveApps() {
    return allowAddRemoveApps;
  }

  public void setAllowAddRemoveApps(Boolean allowAddRemoveApps) {
    this.allowAddRemoveApps = allowAddRemoveApps;
  }

  public MicrosoftGraphTeamMemberSettings allowCreatePrivateChannels(Boolean allowCreatePrivateChannels) {
    this.allowCreatePrivateChannels = allowCreatePrivateChannels;
    return this;
  }

   /**
   * If set to true, members can add and update private channels.
   * @return allowCreatePrivateChannels
  **/
  public Boolean isAllowCreatePrivateChannels() {
    return allowCreatePrivateChannels;
  }

  public void setAllowCreatePrivateChannels(Boolean allowCreatePrivateChannels) {
    this.allowCreatePrivateChannels = allowCreatePrivateChannels;
  }

  public MicrosoftGraphTeamMemberSettings allowCreateUpdateChannels(Boolean allowCreateUpdateChannels) {
    this.allowCreateUpdateChannels = allowCreateUpdateChannels;
    return this;
  }

   /**
   * If set to true, members can add and update channels.
   * @return allowCreateUpdateChannels
  **/
  public Boolean isAllowCreateUpdateChannels() {
    return allowCreateUpdateChannels;
  }

  public void setAllowCreateUpdateChannels(Boolean allowCreateUpdateChannels) {
    this.allowCreateUpdateChannels = allowCreateUpdateChannels;
  }

  public MicrosoftGraphTeamMemberSettings allowCreateUpdateRemoveConnectors(Boolean allowCreateUpdateRemoveConnectors) {
    this.allowCreateUpdateRemoveConnectors = allowCreateUpdateRemoveConnectors;
    return this;
  }

   /**
   * If set to true, members can add, update, and remove connectors.
   * @return allowCreateUpdateRemoveConnectors
  **/
  public Boolean isAllowCreateUpdateRemoveConnectors() {
    return allowCreateUpdateRemoveConnectors;
  }

  public void setAllowCreateUpdateRemoveConnectors(Boolean allowCreateUpdateRemoveConnectors) {
    this.allowCreateUpdateRemoveConnectors = allowCreateUpdateRemoveConnectors;
  }

  public MicrosoftGraphTeamMemberSettings allowCreateUpdateRemoveTabs(Boolean allowCreateUpdateRemoveTabs) {
    this.allowCreateUpdateRemoveTabs = allowCreateUpdateRemoveTabs;
    return this;
  }

   /**
   * If set to true, members can add, update, and remove tabs.
   * @return allowCreateUpdateRemoveTabs
  **/
  public Boolean isAllowCreateUpdateRemoveTabs() {
    return allowCreateUpdateRemoveTabs;
  }

  public void setAllowCreateUpdateRemoveTabs(Boolean allowCreateUpdateRemoveTabs) {
    this.allowCreateUpdateRemoveTabs = allowCreateUpdateRemoveTabs;
  }

  public MicrosoftGraphTeamMemberSettings allowDeleteChannels(Boolean allowDeleteChannels) {
    this.allowDeleteChannels = allowDeleteChannels;
    return this;
  }

   /**
   * If set to true, members can delete channels.
   * @return allowDeleteChannels
  **/
  public Boolean isAllowDeleteChannels() {
    return allowDeleteChannels;
  }

  public void setAllowDeleteChannels(Boolean allowDeleteChannels) {
    this.allowDeleteChannels = allowDeleteChannels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphTeamMemberSettings microsoftGraphTeamMemberSettings = (MicrosoftGraphTeamMemberSettings) o;
    return Objects.equals(this.allowAddRemoveApps, microsoftGraphTeamMemberSettings.allowAddRemoveApps) &&
        Objects.equals(this.allowCreatePrivateChannels, microsoftGraphTeamMemberSettings.allowCreatePrivateChannels) &&
        Objects.equals(this.allowCreateUpdateChannels, microsoftGraphTeamMemberSettings.allowCreateUpdateChannels) &&
        Objects.equals(this.allowCreateUpdateRemoveConnectors, microsoftGraphTeamMemberSettings.allowCreateUpdateRemoveConnectors) &&
        Objects.equals(this.allowCreateUpdateRemoveTabs, microsoftGraphTeamMemberSettings.allowCreateUpdateRemoveTabs) &&
        Objects.equals(this.allowDeleteChannels, microsoftGraphTeamMemberSettings.allowDeleteChannels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowAddRemoveApps, allowCreatePrivateChannels, allowCreateUpdateChannels, allowCreateUpdateRemoveConnectors, allowCreateUpdateRemoveTabs, allowDeleteChannels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphTeamMemberSettings {\n");
    
    sb.append("    allowAddRemoveApps: ").append(toIndentedString(allowAddRemoveApps)).append("\n");
    sb.append("    allowCreatePrivateChannels: ").append(toIndentedString(allowCreatePrivateChannels)).append("\n");
    sb.append("    allowCreateUpdateChannels: ").append(toIndentedString(allowCreateUpdateChannels)).append("\n");
    sb.append("    allowCreateUpdateRemoveConnectors: ").append(toIndentedString(allowCreateUpdateRemoveConnectors)).append("\n");
    sb.append("    allowCreateUpdateRemoveTabs: ").append(toIndentedString(allowCreateUpdateRemoveTabs)).append("\n");
    sb.append("    allowDeleteChannels: ").append(toIndentedString(allowDeleteChannels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
