/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphInsightIdentity;
import com.microsoft.graph.MicrosoftGraphResourceReference;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphSharingDetail
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphSharingDetail {
  @JsonProperty("sharedBy")
  private MicrosoftGraphInsightIdentity sharedBy = null;

  @JsonProperty("sharedDateTime")
  private OffsetDateTime sharedDateTime = null;

  @JsonProperty("sharingReference")
  private MicrosoftGraphResourceReference sharingReference = null;

  @JsonProperty("sharingSubject")
  private String sharingSubject = null;

  @JsonProperty("sharingType")
  private String sharingType = null;

  public MicrosoftGraphSharingDetail sharedBy(MicrosoftGraphInsightIdentity sharedBy) {
    this.sharedBy = sharedBy;
    return this;
  }

   /**
   * Get sharedBy
   * @return sharedBy
  **/
  public MicrosoftGraphInsightIdentity getSharedBy() {
    return sharedBy;
  }

  public void setSharedBy(MicrosoftGraphInsightIdentity sharedBy) {
    this.sharedBy = sharedBy;
  }

  public MicrosoftGraphSharingDetail sharedDateTime(OffsetDateTime sharedDateTime) {
    this.sharedDateTime = sharedDateTime;
    return this;
  }

   /**
   * The date and time the file was last shared. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.
   * @return sharedDateTime
  **/
  public OffsetDateTime getSharedDateTime() {
    return sharedDateTime;
  }

  public void setSharedDateTime(OffsetDateTime sharedDateTime) {
    this.sharedDateTime = sharedDateTime;
  }

  public MicrosoftGraphSharingDetail sharingReference(MicrosoftGraphResourceReference sharingReference) {
    this.sharingReference = sharingReference;
    return this;
  }

   /**
   * Get sharingReference
   * @return sharingReference
  **/
  public MicrosoftGraphResourceReference getSharingReference() {
    return sharingReference;
  }

  public void setSharingReference(MicrosoftGraphResourceReference sharingReference) {
    this.sharingReference = sharingReference;
  }

  public MicrosoftGraphSharingDetail sharingSubject(String sharingSubject) {
    this.sharingSubject = sharingSubject;
    return this;
  }

   /**
   * The subject with which the document was shared.
   * @return sharingSubject
  **/
  public String getSharingSubject() {
    return sharingSubject;
  }

  public void setSharingSubject(String sharingSubject) {
    this.sharingSubject = sharingSubject;
  }

  public MicrosoftGraphSharingDetail sharingType(String sharingType) {
    this.sharingType = sharingType;
    return this;
  }

   /**
   * Determines the way the document was shared, can be by a &#x27;Link&#x27;, &#x27;Attachment&#x27;, &#x27;Group&#x27;, &#x27;Site&#x27;.
   * @return sharingType
  **/
  public String getSharingType() {
    return sharingType;
  }

  public void setSharingType(String sharingType) {
    this.sharingType = sharingType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphSharingDetail microsoftGraphSharingDetail = (MicrosoftGraphSharingDetail) o;
    return Objects.equals(this.sharedBy, microsoftGraphSharingDetail.sharedBy) &&
        Objects.equals(this.sharedDateTime, microsoftGraphSharingDetail.sharedDateTime) &&
        Objects.equals(this.sharingReference, microsoftGraphSharingDetail.sharingReference) &&
        Objects.equals(this.sharingSubject, microsoftGraphSharingDetail.sharingSubject) &&
        Objects.equals(this.sharingType, microsoftGraphSharingDetail.sharingType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sharedBy, sharedDateTime, sharingReference, sharingSubject, sharingType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphSharingDetail {\n");
    
    sb.append("    sharedBy: ").append(toIndentedString(sharedBy)).append("\n");
    sb.append("    sharedDateTime: ").append(toIndentedString(sharedDateTime)).append("\n");
    sb.append("    sharingReference: ").append(toIndentedString(sharingReference)).append("\n");
    sb.append("    sharingSubject: ").append(toIndentedString(sharingSubject)).append("\n");
    sb.append("    sharingType: ").append(toIndentedString(sharingType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
