/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MicrosoftGraphDriveRecipient
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphDriveRecipient {
  @JsonProperty("alias")
  private String alias = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("objectId")
  private String objectId = null;

  public MicrosoftGraphDriveRecipient alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * The alias of the domain object, for cases where an email address is unavailable (e.g. security groups).
   * @return alias
  **/
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public MicrosoftGraphDriveRecipient email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address for the recipient, if the recipient has an associated email address.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public MicrosoftGraphDriveRecipient objectId(String objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * The unique identifier for the recipient in the directory.
   * @return objectId
  **/
  public String getObjectId() {
    return objectId;
  }

  public void setObjectId(String objectId) {
    this.objectId = objectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphDriveRecipient microsoftGraphDriveRecipient = (MicrosoftGraphDriveRecipient) o;
    return Objects.equals(this.alias, microsoftGraphDriveRecipient.alias) &&
        Objects.equals(this.email, microsoftGraphDriveRecipient.email) &&
        Objects.equals(this.objectId, microsoftGraphDriveRecipient.objectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alias, email, objectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphDriveRecipient {\n");
    
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
