/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphHashes;

/**
 * MicrosoftGraphFile
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphFile {
  @JsonProperty("hashes")
  private MicrosoftGraphHashes hashes = null;

  @JsonProperty("mimeType")
  private String mimeType = null;

  @JsonProperty("processingMetadata")
  private Boolean processingMetadata = null;

  public MicrosoftGraphFile hashes(MicrosoftGraphHashes hashes) {
    this.hashes = hashes;
    return this;
  }

   /**
   * Get hashes
   * @return hashes
  **/
  public MicrosoftGraphHashes getHashes() {
    return hashes;
  }

  public void setHashes(MicrosoftGraphHashes hashes) {
    this.hashes = hashes;
  }

  public MicrosoftGraphFile mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * The MIME type for the file. This is determined by logic on the server and might not be the value provided when the file was uploaded. Read-only.
   * @return mimeType
  **/
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public MicrosoftGraphFile processingMetadata(Boolean processingMetadata) {
    this.processingMetadata = processingMetadata;
    return this;
  }

   /**
   * Get processingMetadata
   * @return processingMetadata
  **/
  public Boolean isProcessingMetadata() {
    return processingMetadata;
  }

  public void setProcessingMetadata(Boolean processingMetadata) {
    this.processingMetadata = processingMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphFile microsoftGraphFile = (MicrosoftGraphFile) o;
    return Objects.equals(this.hashes, microsoftGraphFile.hashes) &&
        Objects.equals(this.mimeType, microsoftGraphFile.mimeType) &&
        Objects.equals(this.processingMetadata, microsoftGraphFile.processingMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashes, mimeType, processingMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphFile {\n");
    
    sb.append("    hashes: ").append(toIndentedString(hashes)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    processingMetadata: ").append(toIndentedString(processingMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
