/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphIdentitySet;
import com.microsoft.graph.MicrosoftGraphOnlineMeetingRole;

/**
 * MicrosoftGraphMeetingParticipantInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphMeetingParticipantInfo {
  @JsonProperty("identity")
  private MicrosoftGraphIdentitySet identity = null;

  @JsonProperty("role")
  private MicrosoftGraphOnlineMeetingRole role = null;

  @JsonProperty("upn")
  private String upn = null;

  public MicrosoftGraphMeetingParticipantInfo identity(MicrosoftGraphIdentitySet identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Get identity
   * @return identity
  **/
  public MicrosoftGraphIdentitySet getIdentity() {
    return identity;
  }

  public void setIdentity(MicrosoftGraphIdentitySet identity) {
    this.identity = identity;
  }

  public MicrosoftGraphMeetingParticipantInfo role(MicrosoftGraphOnlineMeetingRole role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  public MicrosoftGraphOnlineMeetingRole getRole() {
    return role;
  }

  public void setRole(MicrosoftGraphOnlineMeetingRole role) {
    this.role = role;
  }

  public MicrosoftGraphMeetingParticipantInfo upn(String upn) {
    this.upn = upn;
    return this;
  }

   /**
   * User principal name of the participant.
   * @return upn
  **/
  public String getUpn() {
    return upn;
  }

  public void setUpn(String upn) {
    this.upn = upn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphMeetingParticipantInfo microsoftGraphMeetingParticipantInfo = (MicrosoftGraphMeetingParticipantInfo) o;
    return Objects.equals(this.identity, microsoftGraphMeetingParticipantInfo.identity) &&
        Objects.equals(this.role, microsoftGraphMeetingParticipantInfo.role) &&
        Objects.equals(this.upn, microsoftGraphMeetingParticipantInfo.upn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identity, role, upn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphMeetingParticipantInfo {\n");
    
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    upn: ").append(toIndentedString(upn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
