/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphJson;
import com.microsoft.graph.MicrosoftGraphWorkbookChartPointFormat;

/**
 * MicrosoftGraphWorkbookChartPoint
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkbookChartPoint extends MicrosoftGraphEntity {
  @JsonProperty("value")
  private MicrosoftGraphJson value = null;

  @JsonProperty("format")
  private MicrosoftGraphWorkbookChartPointFormat format = null;

  public MicrosoftGraphWorkbookChartPoint value(MicrosoftGraphJson value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public MicrosoftGraphJson getValue() {
    return value;
  }

  public void setValue(MicrosoftGraphJson value) {
    this.value = value;
  }

  public MicrosoftGraphWorkbookChartPoint format(MicrosoftGraphWorkbookChartPointFormat format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  public MicrosoftGraphWorkbookChartPointFormat getFormat() {
    return format;
  }

  public void setFormat(MicrosoftGraphWorkbookChartPointFormat format) {
    this.format = format;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkbookChartPoint microsoftGraphWorkbookChartPoint = (MicrosoftGraphWorkbookChartPoint) o;
    return Objects.equals(this.value, microsoftGraphWorkbookChartPoint.value) &&
        Objects.equals(this.format, microsoftGraphWorkbookChartPoint.format) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, format, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkbookChartPoint {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
