/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphIdentitySet;
import com.microsoft.graph.MicrosoftGraphPlannerAppliedCategories;
import com.microsoft.graph.MicrosoftGraphPlannerAssignedToTaskBoardTaskFormat;
import com.microsoft.graph.MicrosoftGraphPlannerAssignments;
import com.microsoft.graph.MicrosoftGraphPlannerBucketTaskBoardTaskFormat;
import com.microsoft.graph.MicrosoftGraphPlannerPreviewType;
import com.microsoft.graph.MicrosoftGraphPlannerProgressTaskBoardTaskFormat;
import com.microsoft.graph.MicrosoftGraphPlannerTaskDetails;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphPlannerTask
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphPlannerTask extends MicrosoftGraphEntity {
  @JsonProperty("activeChecklistItemCount")
  private Integer activeChecklistItemCount = null;

  @JsonProperty("appliedCategories")
  private MicrosoftGraphPlannerAppliedCategories appliedCategories = null;

  @JsonProperty("assigneePriority")
  private String assigneePriority = null;

  @JsonProperty("assignments")
  private MicrosoftGraphPlannerAssignments assignments = null;

  @JsonProperty("bucketId")
  private String bucketId = null;

  @JsonProperty("checklistItemCount")
  private Integer checklistItemCount = null;

  @JsonProperty("completedBy")
  private MicrosoftGraphIdentitySet completedBy = null;

  @JsonProperty("completedDateTime")
  private OffsetDateTime completedDateTime = null;

  @JsonProperty("conversationThreadId")
  private String conversationThreadId = null;

  @JsonProperty("createdBy")
  private MicrosoftGraphIdentitySet createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("dueDateTime")
  private OffsetDateTime dueDateTime = null;

  @JsonProperty("hasDescription")
  private Boolean hasDescription = null;

  @JsonProperty("orderHint")
  private String orderHint = null;

  @JsonProperty("percentComplete")
  private Integer percentComplete = null;

  @JsonProperty("planId")
  private String planId = null;

  @JsonProperty("previewType")
  private MicrosoftGraphPlannerPreviewType previewType = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("referenceCount")
  private Integer referenceCount = null;

  @JsonProperty("startDateTime")
  private OffsetDateTime startDateTime = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("assignedToTaskBoardFormat")
  private MicrosoftGraphPlannerAssignedToTaskBoardTaskFormat assignedToTaskBoardFormat = null;

  @JsonProperty("bucketTaskBoardFormat")
  private MicrosoftGraphPlannerBucketTaskBoardTaskFormat bucketTaskBoardFormat = null;

  @JsonProperty("details")
  private MicrosoftGraphPlannerTaskDetails details = null;

  @JsonProperty("progressTaskBoardFormat")
  private MicrosoftGraphPlannerProgressTaskBoardTaskFormat progressTaskBoardFormat = null;

  public MicrosoftGraphPlannerTask activeChecklistItemCount(Integer activeChecklistItemCount) {
    this.activeChecklistItemCount = activeChecklistItemCount;
    return this;
  }

   /**
   * Number of checklist items with value set to false, representing incomplete items.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return activeChecklistItemCount
  **/
  public Integer getActiveChecklistItemCount() {
    return activeChecklistItemCount;
  }

  public void setActiveChecklistItemCount(Integer activeChecklistItemCount) {
    this.activeChecklistItemCount = activeChecklistItemCount;
  }

  public MicrosoftGraphPlannerTask appliedCategories(MicrosoftGraphPlannerAppliedCategories appliedCategories) {
    this.appliedCategories = appliedCategories;
    return this;
  }

   /**
   * Get appliedCategories
   * @return appliedCategories
  **/
  public MicrosoftGraphPlannerAppliedCategories getAppliedCategories() {
    return appliedCategories;
  }

  public void setAppliedCategories(MicrosoftGraphPlannerAppliedCategories appliedCategories) {
    this.appliedCategories = appliedCategories;
  }

  public MicrosoftGraphPlannerTask assigneePriority(String assigneePriority) {
    this.assigneePriority = assigneePriority;
    return this;
  }

   /**
   * Hint used to order items of this type in a list view. The format is defined as outlined here.
   * @return assigneePriority
  **/
  public String getAssigneePriority() {
    return assigneePriority;
  }

  public void setAssigneePriority(String assigneePriority) {
    this.assigneePriority = assigneePriority;
  }

  public MicrosoftGraphPlannerTask assignments(MicrosoftGraphPlannerAssignments assignments) {
    this.assignments = assignments;
    return this;
  }

   /**
   * Get assignments
   * @return assignments
  **/
  public MicrosoftGraphPlannerAssignments getAssignments() {
    return assignments;
  }

  public void setAssignments(MicrosoftGraphPlannerAssignments assignments) {
    this.assignments = assignments;
  }

  public MicrosoftGraphPlannerTask bucketId(String bucketId) {
    this.bucketId = bucketId;
    return this;
  }

   /**
   * Bucket ID to which the task belongs. The bucket needs to be in the plan that the task is in. It is 28 characters long and case-sensitive. Format validation is done on the service.
   * @return bucketId
  **/
  public String getBucketId() {
    return bucketId;
  }

  public void setBucketId(String bucketId) {
    this.bucketId = bucketId;
  }

  public MicrosoftGraphPlannerTask checklistItemCount(Integer checklistItemCount) {
    this.checklistItemCount = checklistItemCount;
    return this;
  }

   /**
   * Number of checklist items that are present on the task.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return checklistItemCount
  **/
  public Integer getChecklistItemCount() {
    return checklistItemCount;
  }

  public void setChecklistItemCount(Integer checklistItemCount) {
    this.checklistItemCount = checklistItemCount;
  }

  public MicrosoftGraphPlannerTask completedBy(MicrosoftGraphIdentitySet completedBy) {
    this.completedBy = completedBy;
    return this;
  }

   /**
   * Get completedBy
   * @return completedBy
  **/
  public MicrosoftGraphIdentitySet getCompletedBy() {
    return completedBy;
  }

  public void setCompletedBy(MicrosoftGraphIdentitySet completedBy) {
    this.completedBy = completedBy;
  }

  public MicrosoftGraphPlannerTask completedDateTime(OffsetDateTime completedDateTime) {
    this.completedDateTime = completedDateTime;
    return this;
  }

   /**
   * Read-only. Date and time at which the &#x27;percentComplete&#x27; of the task is set to &#x27;100&#x27;. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
   * @return completedDateTime
  **/
  public OffsetDateTime getCompletedDateTime() {
    return completedDateTime;
  }

  public void setCompletedDateTime(OffsetDateTime completedDateTime) {
    this.completedDateTime = completedDateTime;
  }

  public MicrosoftGraphPlannerTask conversationThreadId(String conversationThreadId) {
    this.conversationThreadId = conversationThreadId;
    return this;
  }

   /**
   * Thread ID of the conversation on the task. This is the ID of the conversation thread object created in the group.
   * @return conversationThreadId
  **/
  public String getConversationThreadId() {
    return conversationThreadId;
  }

  public void setConversationThreadId(String conversationThreadId) {
    this.conversationThreadId = conversationThreadId;
  }

  public MicrosoftGraphPlannerTask createdBy(MicrosoftGraphIdentitySet createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public MicrosoftGraphIdentitySet getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(MicrosoftGraphIdentitySet createdBy) {
    this.createdBy = createdBy;
  }

  public MicrosoftGraphPlannerTask createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Read-only. Date and time at which the task is created. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphPlannerTask dueDateTime(OffsetDateTime dueDateTime) {
    this.dueDateTime = dueDateTime;
    return this;
  }

   /**
   * Date and time at which the task is due. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
   * @return dueDateTime
  **/
  public OffsetDateTime getDueDateTime() {
    return dueDateTime;
  }

  public void setDueDateTime(OffsetDateTime dueDateTime) {
    this.dueDateTime = dueDateTime;
  }

  public MicrosoftGraphPlannerTask hasDescription(Boolean hasDescription) {
    this.hasDescription = hasDescription;
    return this;
  }

   /**
   * Read-only. Value is true if the details object of the task has a non-empty description and false otherwise.
   * @return hasDescription
  **/
  public Boolean isHasDescription() {
    return hasDescription;
  }

  public void setHasDescription(Boolean hasDescription) {
    this.hasDescription = hasDescription;
  }

  public MicrosoftGraphPlannerTask orderHint(String orderHint) {
    this.orderHint = orderHint;
    return this;
  }

   /**
   * Hint used to order items of this type in a list view. The format is defined as outlined here.
   * @return orderHint
  **/
  public String getOrderHint() {
    return orderHint;
  }

  public void setOrderHint(String orderHint) {
    this.orderHint = orderHint;
  }

  public MicrosoftGraphPlannerTask percentComplete(Integer percentComplete) {
    this.percentComplete = percentComplete;
    return this;
  }

   /**
   * Percentage of task completion. When set to 100, the task is considered completed.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return percentComplete
  **/
  public Integer getPercentComplete() {
    return percentComplete;
  }

  public void setPercentComplete(Integer percentComplete) {
    this.percentComplete = percentComplete;
  }

  public MicrosoftGraphPlannerTask planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Plan ID to which the task belongs.
   * @return planId
  **/
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public MicrosoftGraphPlannerTask previewType(MicrosoftGraphPlannerPreviewType previewType) {
    this.previewType = previewType;
    return this;
  }

   /**
   * Get previewType
   * @return previewType
  **/
  public MicrosoftGraphPlannerPreviewType getPreviewType() {
    return previewType;
  }

  public void setPreviewType(MicrosoftGraphPlannerPreviewType previewType) {
    this.previewType = previewType;
  }

  public MicrosoftGraphPlannerTask priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Priority of the task. The valid range of values is between 0 and 10, with the increasing value being lower priority (0 has the highest priority and 10 has the lowest priority).  Currently, Planner interprets values 0 and 1 as &#x27;urgent&#x27;, 2, 3 and 4 as &#x27;important&#x27;, 5, 6, and 7 as &#x27;medium&#x27;, and 8, 9, and 10 as &#x27;low&#x27;.  Additionally, Planner sets the value 1 for &#x27;urgent&#x27;, 3 for &#x27;important&#x27;, 5 for &#x27;medium&#x27;, and 9 for &#x27;low&#x27;.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return priority
  **/
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public MicrosoftGraphPlannerTask referenceCount(Integer referenceCount) {
    this.referenceCount = referenceCount;
    return this;
  }

   /**
   * Number of external references that exist on the task.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return referenceCount
  **/
  public Integer getReferenceCount() {
    return referenceCount;
  }

  public void setReferenceCount(Integer referenceCount) {
    this.referenceCount = referenceCount;
  }

  public MicrosoftGraphPlannerTask startDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Date and time at which the task starts. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
   * @return startDateTime
  **/
  public OffsetDateTime getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }

  public MicrosoftGraphPlannerTask title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the task.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public MicrosoftGraphPlannerTask assignedToTaskBoardFormat(MicrosoftGraphPlannerAssignedToTaskBoardTaskFormat assignedToTaskBoardFormat) {
    this.assignedToTaskBoardFormat = assignedToTaskBoardFormat;
    return this;
  }

   /**
   * Get assignedToTaskBoardFormat
   * @return assignedToTaskBoardFormat
  **/
  public MicrosoftGraphPlannerAssignedToTaskBoardTaskFormat getAssignedToTaskBoardFormat() {
    return assignedToTaskBoardFormat;
  }

  public void setAssignedToTaskBoardFormat(MicrosoftGraphPlannerAssignedToTaskBoardTaskFormat assignedToTaskBoardFormat) {
    this.assignedToTaskBoardFormat = assignedToTaskBoardFormat;
  }

  public MicrosoftGraphPlannerTask bucketTaskBoardFormat(MicrosoftGraphPlannerBucketTaskBoardTaskFormat bucketTaskBoardFormat) {
    this.bucketTaskBoardFormat = bucketTaskBoardFormat;
    return this;
  }

   /**
   * Get bucketTaskBoardFormat
   * @return bucketTaskBoardFormat
  **/
  public MicrosoftGraphPlannerBucketTaskBoardTaskFormat getBucketTaskBoardFormat() {
    return bucketTaskBoardFormat;
  }

  public void setBucketTaskBoardFormat(MicrosoftGraphPlannerBucketTaskBoardTaskFormat bucketTaskBoardFormat) {
    this.bucketTaskBoardFormat = bucketTaskBoardFormat;
  }

  public MicrosoftGraphPlannerTask details(MicrosoftGraphPlannerTaskDetails details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  public MicrosoftGraphPlannerTaskDetails getDetails() {
    return details;
  }

  public void setDetails(MicrosoftGraphPlannerTaskDetails details) {
    this.details = details;
  }

  public MicrosoftGraphPlannerTask progressTaskBoardFormat(MicrosoftGraphPlannerProgressTaskBoardTaskFormat progressTaskBoardFormat) {
    this.progressTaskBoardFormat = progressTaskBoardFormat;
    return this;
  }

   /**
   * Get progressTaskBoardFormat
   * @return progressTaskBoardFormat
  **/
  public MicrosoftGraphPlannerProgressTaskBoardTaskFormat getProgressTaskBoardFormat() {
    return progressTaskBoardFormat;
  }

  public void setProgressTaskBoardFormat(MicrosoftGraphPlannerProgressTaskBoardTaskFormat progressTaskBoardFormat) {
    this.progressTaskBoardFormat = progressTaskBoardFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphPlannerTask microsoftGraphPlannerTask = (MicrosoftGraphPlannerTask) o;
    return Objects.equals(this.activeChecklistItemCount, microsoftGraphPlannerTask.activeChecklistItemCount) &&
        Objects.equals(this.appliedCategories, microsoftGraphPlannerTask.appliedCategories) &&
        Objects.equals(this.assigneePriority, microsoftGraphPlannerTask.assigneePriority) &&
        Objects.equals(this.assignments, microsoftGraphPlannerTask.assignments) &&
        Objects.equals(this.bucketId, microsoftGraphPlannerTask.bucketId) &&
        Objects.equals(this.checklistItemCount, microsoftGraphPlannerTask.checklistItemCount) &&
        Objects.equals(this.completedBy, microsoftGraphPlannerTask.completedBy) &&
        Objects.equals(this.completedDateTime, microsoftGraphPlannerTask.completedDateTime) &&
        Objects.equals(this.conversationThreadId, microsoftGraphPlannerTask.conversationThreadId) &&
        Objects.equals(this.createdBy, microsoftGraphPlannerTask.createdBy) &&
        Objects.equals(this.createdDateTime, microsoftGraphPlannerTask.createdDateTime) &&
        Objects.equals(this.dueDateTime, microsoftGraphPlannerTask.dueDateTime) &&
        Objects.equals(this.hasDescription, microsoftGraphPlannerTask.hasDescription) &&
        Objects.equals(this.orderHint, microsoftGraphPlannerTask.orderHint) &&
        Objects.equals(this.percentComplete, microsoftGraphPlannerTask.percentComplete) &&
        Objects.equals(this.planId, microsoftGraphPlannerTask.planId) &&
        Objects.equals(this.previewType, microsoftGraphPlannerTask.previewType) &&
        Objects.equals(this.priority, microsoftGraphPlannerTask.priority) &&
        Objects.equals(this.referenceCount, microsoftGraphPlannerTask.referenceCount) &&
        Objects.equals(this.startDateTime, microsoftGraphPlannerTask.startDateTime) &&
        Objects.equals(this.title, microsoftGraphPlannerTask.title) &&
        Objects.equals(this.assignedToTaskBoardFormat, microsoftGraphPlannerTask.assignedToTaskBoardFormat) &&
        Objects.equals(this.bucketTaskBoardFormat, microsoftGraphPlannerTask.bucketTaskBoardFormat) &&
        Objects.equals(this.details, microsoftGraphPlannerTask.details) &&
        Objects.equals(this.progressTaskBoardFormat, microsoftGraphPlannerTask.progressTaskBoardFormat) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeChecklistItemCount, appliedCategories, assigneePriority, assignments, bucketId, checklistItemCount, completedBy, completedDateTime, conversationThreadId, createdBy, createdDateTime, dueDateTime, hasDescription, orderHint, percentComplete, planId, previewType, priority, referenceCount, startDateTime, title, assignedToTaskBoardFormat, bucketTaskBoardFormat, details, progressTaskBoardFormat, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphPlannerTask {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    activeChecklistItemCount: ").append(toIndentedString(activeChecklistItemCount)).append("\n");
    sb.append("    appliedCategories: ").append(toIndentedString(appliedCategories)).append("\n");
    sb.append("    assigneePriority: ").append(toIndentedString(assigneePriority)).append("\n");
    sb.append("    assignments: ").append(toIndentedString(assignments)).append("\n");
    sb.append("    bucketId: ").append(toIndentedString(bucketId)).append("\n");
    sb.append("    checklistItemCount: ").append(toIndentedString(checklistItemCount)).append("\n");
    sb.append("    completedBy: ").append(toIndentedString(completedBy)).append("\n");
    sb.append("    completedDateTime: ").append(toIndentedString(completedDateTime)).append("\n");
    sb.append("    conversationThreadId: ").append(toIndentedString(conversationThreadId)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    dueDateTime: ").append(toIndentedString(dueDateTime)).append("\n");
    sb.append("    hasDescription: ").append(toIndentedString(hasDescription)).append("\n");
    sb.append("    orderHint: ").append(toIndentedString(orderHint)).append("\n");
    sb.append("    percentComplete: ").append(toIndentedString(percentComplete)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    previewType: ").append(toIndentedString(previewType)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    referenceCount: ").append(toIndentedString(referenceCount)).append("\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    assignedToTaskBoardFormat: ").append(toIndentedString(assignedToTaskBoardFormat)).append("\n");
    sb.append("    bucketTaskBoardFormat: ").append(toIndentedString(bucketTaskBoardFormat)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    progressTaskBoardFormat: ").append(toIndentedString(progressTaskBoardFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
