/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphWindowsDeviceAccount;

/**
 * MicrosoftGraphUpdateWindowsDeviceAccountActionParameter
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphUpdateWindowsDeviceAccountActionParameter {
  @JsonProperty("calendarSyncEnabled")
  private Boolean calendarSyncEnabled = null;

  @JsonProperty("deviceAccount")
  private MicrosoftGraphWindowsDeviceAccount deviceAccount = null;

  @JsonProperty("deviceAccountEmail")
  private String deviceAccountEmail = null;

  @JsonProperty("exchangeServer")
  private String exchangeServer = null;

  @JsonProperty("passwordRotationEnabled")
  private Boolean passwordRotationEnabled = null;

  @JsonProperty("sessionInitiationProtocalAddress")
  private String sessionInitiationProtocalAddress = null;

  public MicrosoftGraphUpdateWindowsDeviceAccountActionParameter calendarSyncEnabled(Boolean calendarSyncEnabled) {
    this.calendarSyncEnabled = calendarSyncEnabled;
    return this;
  }

   /**
   * Not yet documented
   * @return calendarSyncEnabled
  **/
  public Boolean isCalendarSyncEnabled() {
    return calendarSyncEnabled;
  }

  public void setCalendarSyncEnabled(Boolean calendarSyncEnabled) {
    this.calendarSyncEnabled = calendarSyncEnabled;
  }

  public MicrosoftGraphUpdateWindowsDeviceAccountActionParameter deviceAccount(MicrosoftGraphWindowsDeviceAccount deviceAccount) {
    this.deviceAccount = deviceAccount;
    return this;
  }

   /**
   * Get deviceAccount
   * @return deviceAccount
  **/
  public MicrosoftGraphWindowsDeviceAccount getDeviceAccount() {
    return deviceAccount;
  }

  public void setDeviceAccount(MicrosoftGraphWindowsDeviceAccount deviceAccount) {
    this.deviceAccount = deviceAccount;
  }

  public MicrosoftGraphUpdateWindowsDeviceAccountActionParameter deviceAccountEmail(String deviceAccountEmail) {
    this.deviceAccountEmail = deviceAccountEmail;
    return this;
  }

   /**
   * Not yet documented
   * @return deviceAccountEmail
  **/
  public String getDeviceAccountEmail() {
    return deviceAccountEmail;
  }

  public void setDeviceAccountEmail(String deviceAccountEmail) {
    this.deviceAccountEmail = deviceAccountEmail;
  }

  public MicrosoftGraphUpdateWindowsDeviceAccountActionParameter exchangeServer(String exchangeServer) {
    this.exchangeServer = exchangeServer;
    return this;
  }

   /**
   * Not yet documented
   * @return exchangeServer
  **/
  public String getExchangeServer() {
    return exchangeServer;
  }

  public void setExchangeServer(String exchangeServer) {
    this.exchangeServer = exchangeServer;
  }

  public MicrosoftGraphUpdateWindowsDeviceAccountActionParameter passwordRotationEnabled(Boolean passwordRotationEnabled) {
    this.passwordRotationEnabled = passwordRotationEnabled;
    return this;
  }

   /**
   * Not yet documented
   * @return passwordRotationEnabled
  **/
  public Boolean isPasswordRotationEnabled() {
    return passwordRotationEnabled;
  }

  public void setPasswordRotationEnabled(Boolean passwordRotationEnabled) {
    this.passwordRotationEnabled = passwordRotationEnabled;
  }

  public MicrosoftGraphUpdateWindowsDeviceAccountActionParameter sessionInitiationProtocalAddress(String sessionInitiationProtocalAddress) {
    this.sessionInitiationProtocalAddress = sessionInitiationProtocalAddress;
    return this;
  }

   /**
   * Not yet documented
   * @return sessionInitiationProtocalAddress
  **/
  public String getSessionInitiationProtocalAddress() {
    return sessionInitiationProtocalAddress;
  }

  public void setSessionInitiationProtocalAddress(String sessionInitiationProtocalAddress) {
    this.sessionInitiationProtocalAddress = sessionInitiationProtocalAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphUpdateWindowsDeviceAccountActionParameter microsoftGraphUpdateWindowsDeviceAccountActionParameter = (MicrosoftGraphUpdateWindowsDeviceAccountActionParameter) o;
    return Objects.equals(this.calendarSyncEnabled, microsoftGraphUpdateWindowsDeviceAccountActionParameter.calendarSyncEnabled) &&
        Objects.equals(this.deviceAccount, microsoftGraphUpdateWindowsDeviceAccountActionParameter.deviceAccount) &&
        Objects.equals(this.deviceAccountEmail, microsoftGraphUpdateWindowsDeviceAccountActionParameter.deviceAccountEmail) &&
        Objects.equals(this.exchangeServer, microsoftGraphUpdateWindowsDeviceAccountActionParameter.exchangeServer) &&
        Objects.equals(this.passwordRotationEnabled, microsoftGraphUpdateWindowsDeviceAccountActionParameter.passwordRotationEnabled) &&
        Objects.equals(this.sessionInitiationProtocalAddress, microsoftGraphUpdateWindowsDeviceAccountActionParameter.sessionInitiationProtocalAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calendarSyncEnabled, deviceAccount, deviceAccountEmail, exchangeServer, passwordRotationEnabled, sessionInitiationProtocalAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphUpdateWindowsDeviceAccountActionParameter {\n");
    
    sb.append("    calendarSyncEnabled: ").append(toIndentedString(calendarSyncEnabled)).append("\n");
    sb.append("    deviceAccount: ").append(toIndentedString(deviceAccount)).append("\n");
    sb.append("    deviceAccountEmail: ").append(toIndentedString(deviceAccountEmail)).append("\n");
    sb.append("    exchangeServer: ").append(toIndentedString(exchangeServer)).append("\n");
    sb.append("    passwordRotationEnabled: ").append(toIndentedString(passwordRotationEnabled)).append("\n");
    sb.append("    sessionInitiationProtocalAddress: ").append(toIndentedString(sessionInitiationProtocalAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
