/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphManagedAppOperation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphManagedAppOperation extends MicrosoftGraphEntity {
  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("version")
  private String version = null;

  public MicrosoftGraphManagedAppOperation displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The operation name.
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MicrosoftGraphManagedAppOperation lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * The last time the app operation was modified.
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public MicrosoftGraphManagedAppOperation state(String state) {
    this.state = state;
    return this;
  }

   /**
   * The current state of the operation
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public MicrosoftGraphManagedAppOperation version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Version of the entity.
   * @return version
  **/
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphManagedAppOperation microsoftGraphManagedAppOperation = (MicrosoftGraphManagedAppOperation) o;
    return Objects.equals(this.displayName, microsoftGraphManagedAppOperation.displayName) &&
        Objects.equals(this.lastModifiedDateTime, microsoftGraphManagedAppOperation.lastModifiedDateTime) &&
        Objects.equals(this.state, microsoftGraphManagedAppOperation.state) &&
        Objects.equals(this.version, microsoftGraphManagedAppOperation.version) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, lastModifiedDateTime, state, version, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphManagedAppOperation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
