/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphScheduleChangeRequest;
import com.microsoft.graph.MicrosoftGraphScheduleChangeRequestActor;
import com.microsoft.graph.MicrosoftGraphScheduleChangeState;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphOpenShiftChangeRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphOpenShiftChangeRequest extends MicrosoftGraphScheduleChangeRequest {
  @JsonProperty("openShiftId")
  private String openShiftId = null;

  public MicrosoftGraphOpenShiftChangeRequest openShiftId(String openShiftId) {
    this.openShiftId = openShiftId;
    return this;
  }

   /**
   * ID for the open shift.
   * @return openShiftId
  **/
  public String getOpenShiftId() {
    return openShiftId;
  }

  public void setOpenShiftId(String openShiftId) {
    this.openShiftId = openShiftId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphOpenShiftChangeRequest microsoftGraphOpenShiftChangeRequest = (MicrosoftGraphOpenShiftChangeRequest) o;
    return Objects.equals(this.openShiftId, microsoftGraphOpenShiftChangeRequest.openShiftId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(openShiftId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphOpenShiftChangeRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    openShiftId: ").append(toIndentedString(openShiftId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
