/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphJson;
import com.microsoft.graph.MicrosoftGraphWorkbookFilter;

/**
 * MicrosoftGraphWorkbookTableColumn
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphWorkbookTableColumn extends MicrosoftGraphEntity {
  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("values")
  private MicrosoftGraphJson values = null;

  @JsonProperty("filter")
  private MicrosoftGraphWorkbookFilter filter = null;

  public MicrosoftGraphWorkbookTableColumn index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Returns the index number of the column within the columns collection of the table. Zero-indexed. Read-only.
   * minimum: -2147483648
   * maximum: 2147483647
   * @return index
  **/
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public MicrosoftGraphWorkbookTableColumn name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Returns the name of the table column.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MicrosoftGraphWorkbookTableColumn values(MicrosoftGraphJson values) {
    this.values = values;
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  public MicrosoftGraphJson getValues() {
    return values;
  }

  public void setValues(MicrosoftGraphJson values) {
    this.values = values;
  }

  public MicrosoftGraphWorkbookTableColumn filter(MicrosoftGraphWorkbookFilter filter) {
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  public MicrosoftGraphWorkbookFilter getFilter() {
    return filter;
  }

  public void setFilter(MicrosoftGraphWorkbookFilter filter) {
    this.filter = filter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphWorkbookTableColumn microsoftGraphWorkbookTableColumn = (MicrosoftGraphWorkbookTableColumn) o;
    return Objects.equals(this.index, microsoftGraphWorkbookTableColumn.index) &&
        Objects.equals(this.name, microsoftGraphWorkbookTableColumn.name) &&
        Objects.equals(this.values, microsoftGraphWorkbookTableColumn.values) &&
        Objects.equals(this.filter, microsoftGraphWorkbookTableColumn.filter) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, name, values, filter, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphWorkbookTableColumn {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
