/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphBroadcastMeetingCaptionSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphBroadcastMeetingCaptionSettings {
  @JsonProperty("isCaptionEnabled")
  private Boolean isCaptionEnabled = null;

  @JsonProperty("spokenLanguage")
  private String spokenLanguage = null;

  @JsonProperty("translationLanguages")
  private List<String> translationLanguages = null;

  public MicrosoftGraphBroadcastMeetingCaptionSettings isCaptionEnabled(Boolean isCaptionEnabled) {
    this.isCaptionEnabled = isCaptionEnabled;
    return this;
  }

   /**
   * Indicates whether captions are enabled for this Teams live event.
   * @return isCaptionEnabled
  **/
  public Boolean isIsCaptionEnabled() {
    return isCaptionEnabled;
  }

  public void setIsCaptionEnabled(Boolean isCaptionEnabled) {
    this.isCaptionEnabled = isCaptionEnabled;
  }

  public MicrosoftGraphBroadcastMeetingCaptionSettings spokenLanguage(String spokenLanguage) {
    this.spokenLanguage = spokenLanguage;
    return this;
  }

   /**
   * The spoken language.
   * @return spokenLanguage
  **/
  public String getSpokenLanguage() {
    return spokenLanguage;
  }

  public void setSpokenLanguage(String spokenLanguage) {
    this.spokenLanguage = spokenLanguage;
  }

  public MicrosoftGraphBroadcastMeetingCaptionSettings translationLanguages(List<String> translationLanguages) {
    this.translationLanguages = translationLanguages;
    return this;
  }

  public MicrosoftGraphBroadcastMeetingCaptionSettings addTranslationLanguagesItem(String translationLanguagesItem) {
    if (this.translationLanguages == null) {
      this.translationLanguages = new ArrayList<>();
    }
    this.translationLanguages.add(translationLanguagesItem);
    return this;
  }

   /**
   * The translation languages (choose up to 6).
   * @return translationLanguages
  **/
  public List<String> getTranslationLanguages() {
    return translationLanguages;
  }

  public void setTranslationLanguages(List<String> translationLanguages) {
    this.translationLanguages = translationLanguages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphBroadcastMeetingCaptionSettings microsoftGraphBroadcastMeetingCaptionSettings = (MicrosoftGraphBroadcastMeetingCaptionSettings) o;
    return Objects.equals(this.isCaptionEnabled, microsoftGraphBroadcastMeetingCaptionSettings.isCaptionEnabled) &&
        Objects.equals(this.spokenLanguage, microsoftGraphBroadcastMeetingCaptionSettings.spokenLanguage) &&
        Objects.equals(this.translationLanguages, microsoftGraphBroadcastMeetingCaptionSettings.translationLanguages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isCaptionEnabled, spokenLanguage, translationLanguages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphBroadcastMeetingCaptionSettings {\n");
    
    sb.append("    isCaptionEnabled: ").append(toIndentedString(isCaptionEnabled)).append("\n");
    sb.append("    spokenLanguage: ").append(toIndentedString(spokenLanguage)).append("\n");
    sb.append("    translationLanguages: ").append(toIndentedString(translationLanguages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
