/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphEntity;
import com.microsoft.graph.MicrosoftGraphManagedAppFlaggedReason;
import com.microsoft.graph.MicrosoftGraphManagedAppOperation;
import com.microsoft.graph.MicrosoftGraphManagedAppPolicy;
import com.microsoft.graph.MicrosoftGraphMobileAppIdentifier;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * MicrosoftGraphManagedAppRegistration
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphManagedAppRegistration extends MicrosoftGraphEntity {
  @JsonProperty("appIdentifier")
  private MicrosoftGraphMobileAppIdentifier appIdentifier = null;

  @JsonProperty("applicationVersion")
  private String applicationVersion = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("deviceName")
  private String deviceName = null;

  @JsonProperty("deviceTag")
  private String deviceTag = null;

  @JsonProperty("deviceType")
  private String deviceType = null;

  @JsonProperty("flaggedReasons")
  private List<MicrosoftGraphManagedAppFlaggedReason> flaggedReasons = null;

  @JsonProperty("lastSyncDateTime")
  private OffsetDateTime lastSyncDateTime = null;

  @JsonProperty("managementSdkVersion")
  private String managementSdkVersion = null;

  @JsonProperty("platformVersion")
  private String platformVersion = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("appliedPolicies")
  private List<MicrosoftGraphManagedAppPolicy> appliedPolicies = null;

  @JsonProperty("intendedPolicies")
  private List<MicrosoftGraphManagedAppPolicy> intendedPolicies = null;

  @JsonProperty("operations")
  private List<MicrosoftGraphManagedAppOperation> operations = null;

  public MicrosoftGraphManagedAppRegistration appIdentifier(MicrosoftGraphMobileAppIdentifier appIdentifier) {
    this.appIdentifier = appIdentifier;
    return this;
  }

   /**
   * Get appIdentifier
   * @return appIdentifier
  **/
  public MicrosoftGraphMobileAppIdentifier getAppIdentifier() {
    return appIdentifier;
  }

  public void setAppIdentifier(MicrosoftGraphMobileAppIdentifier appIdentifier) {
    this.appIdentifier = appIdentifier;
  }

  public MicrosoftGraphManagedAppRegistration applicationVersion(String applicationVersion) {
    this.applicationVersion = applicationVersion;
    return this;
  }

   /**
   * App version
   * @return applicationVersion
  **/
  public String getApplicationVersion() {
    return applicationVersion;
  }

  public void setApplicationVersion(String applicationVersion) {
    this.applicationVersion = applicationVersion;
  }

  public MicrosoftGraphManagedAppRegistration createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Date and time of creation
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphManagedAppRegistration deviceName(String deviceName) {
    this.deviceName = deviceName;
    return this;
  }

   /**
   * Host device name
   * @return deviceName
  **/
  public String getDeviceName() {
    return deviceName;
  }

  public void setDeviceName(String deviceName) {
    this.deviceName = deviceName;
  }

  public MicrosoftGraphManagedAppRegistration deviceTag(String deviceTag) {
    this.deviceTag = deviceTag;
    return this;
  }

   /**
   * App management SDK generated tag, which helps relate apps hosted on the same device. Not guaranteed to relate apps in all conditions.
   * @return deviceTag
  **/
  public String getDeviceTag() {
    return deviceTag;
  }

  public void setDeviceTag(String deviceTag) {
    this.deviceTag = deviceTag;
  }

  public MicrosoftGraphManagedAppRegistration deviceType(String deviceType) {
    this.deviceType = deviceType;
    return this;
  }

   /**
   * Host device type
   * @return deviceType
  **/
  public String getDeviceType() {
    return deviceType;
  }

  public void setDeviceType(String deviceType) {
    this.deviceType = deviceType;
  }

  public MicrosoftGraphManagedAppRegistration flaggedReasons(List<MicrosoftGraphManagedAppFlaggedReason> flaggedReasons) {
    this.flaggedReasons = flaggedReasons;
    return this;
  }

  public MicrosoftGraphManagedAppRegistration addFlaggedReasonsItem(MicrosoftGraphManagedAppFlaggedReason flaggedReasonsItem) {
    if (this.flaggedReasons == null) {
      this.flaggedReasons = new ArrayList<>();
    }
    this.flaggedReasons.add(flaggedReasonsItem);
    return this;
  }

   /**
   * Zero or more reasons an app registration is flagged. E.g. app running on rooted device
   * @return flaggedReasons
  **/
  public List<MicrosoftGraphManagedAppFlaggedReason> getFlaggedReasons() {
    return flaggedReasons;
  }

  public void setFlaggedReasons(List<MicrosoftGraphManagedAppFlaggedReason> flaggedReasons) {
    this.flaggedReasons = flaggedReasons;
  }

  public MicrosoftGraphManagedAppRegistration lastSyncDateTime(OffsetDateTime lastSyncDateTime) {
    this.lastSyncDateTime = lastSyncDateTime;
    return this;
  }

   /**
   * Date and time of last the app synced with management service.
   * @return lastSyncDateTime
  **/
  public OffsetDateTime getLastSyncDateTime() {
    return lastSyncDateTime;
  }

  public void setLastSyncDateTime(OffsetDateTime lastSyncDateTime) {
    this.lastSyncDateTime = lastSyncDateTime;
  }

  public MicrosoftGraphManagedAppRegistration managementSdkVersion(String managementSdkVersion) {
    this.managementSdkVersion = managementSdkVersion;
    return this;
  }

   /**
   * App management SDK version
   * @return managementSdkVersion
  **/
  public String getManagementSdkVersion() {
    return managementSdkVersion;
  }

  public void setManagementSdkVersion(String managementSdkVersion) {
    this.managementSdkVersion = managementSdkVersion;
  }

  public MicrosoftGraphManagedAppRegistration platformVersion(String platformVersion) {
    this.platformVersion = platformVersion;
    return this;
  }

   /**
   * Operating System version
   * @return platformVersion
  **/
  public String getPlatformVersion() {
    return platformVersion;
  }

  public void setPlatformVersion(String platformVersion) {
    this.platformVersion = platformVersion;
  }

  public MicrosoftGraphManagedAppRegistration userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The user Id to who this app registration belongs.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public MicrosoftGraphManagedAppRegistration version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Version of the entity.
   * @return version
  **/
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public MicrosoftGraphManagedAppRegistration appliedPolicies(List<MicrosoftGraphManagedAppPolicy> appliedPolicies) {
    this.appliedPolicies = appliedPolicies;
    return this;
  }

  public MicrosoftGraphManagedAppRegistration addAppliedPoliciesItem(MicrosoftGraphManagedAppPolicy appliedPoliciesItem) {
    if (this.appliedPolicies == null) {
      this.appliedPolicies = new ArrayList<>();
    }
    this.appliedPolicies.add(appliedPoliciesItem);
    return this;
  }

   /**
   * Zero or more policys already applied on the registered app when it last synchronized with managment service.
   * @return appliedPolicies
  **/
  public List<MicrosoftGraphManagedAppPolicy> getAppliedPolicies() {
    return appliedPolicies;
  }

  public void setAppliedPolicies(List<MicrosoftGraphManagedAppPolicy> appliedPolicies) {
    this.appliedPolicies = appliedPolicies;
  }

  public MicrosoftGraphManagedAppRegistration intendedPolicies(List<MicrosoftGraphManagedAppPolicy> intendedPolicies) {
    this.intendedPolicies = intendedPolicies;
    return this;
  }

  public MicrosoftGraphManagedAppRegistration addIntendedPoliciesItem(MicrosoftGraphManagedAppPolicy intendedPoliciesItem) {
    if (this.intendedPolicies == null) {
      this.intendedPolicies = new ArrayList<>();
    }
    this.intendedPolicies.add(intendedPoliciesItem);
    return this;
  }

   /**
   * Zero or more policies admin intended for the app as of now.
   * @return intendedPolicies
  **/
  public List<MicrosoftGraphManagedAppPolicy> getIntendedPolicies() {
    return intendedPolicies;
  }

  public void setIntendedPolicies(List<MicrosoftGraphManagedAppPolicy> intendedPolicies) {
    this.intendedPolicies = intendedPolicies;
  }

  public MicrosoftGraphManagedAppRegistration operations(List<MicrosoftGraphManagedAppOperation> operations) {
    this.operations = operations;
    return this;
  }

  public MicrosoftGraphManagedAppRegistration addOperationsItem(MicrosoftGraphManagedAppOperation operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<>();
    }
    this.operations.add(operationsItem);
    return this;
  }

   /**
   * Zero or more long running operations triggered on the app registration.
   * @return operations
  **/
  public List<MicrosoftGraphManagedAppOperation> getOperations() {
    return operations;
  }

  public void setOperations(List<MicrosoftGraphManagedAppOperation> operations) {
    this.operations = operations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphManagedAppRegistration microsoftGraphManagedAppRegistration = (MicrosoftGraphManagedAppRegistration) o;
    return Objects.equals(this.appIdentifier, microsoftGraphManagedAppRegistration.appIdentifier) &&
        Objects.equals(this.applicationVersion, microsoftGraphManagedAppRegistration.applicationVersion) &&
        Objects.equals(this.createdDateTime, microsoftGraphManagedAppRegistration.createdDateTime) &&
        Objects.equals(this.deviceName, microsoftGraphManagedAppRegistration.deviceName) &&
        Objects.equals(this.deviceTag, microsoftGraphManagedAppRegistration.deviceTag) &&
        Objects.equals(this.deviceType, microsoftGraphManagedAppRegistration.deviceType) &&
        Objects.equals(this.flaggedReasons, microsoftGraphManagedAppRegistration.flaggedReasons) &&
        Objects.equals(this.lastSyncDateTime, microsoftGraphManagedAppRegistration.lastSyncDateTime) &&
        Objects.equals(this.managementSdkVersion, microsoftGraphManagedAppRegistration.managementSdkVersion) &&
        Objects.equals(this.platformVersion, microsoftGraphManagedAppRegistration.platformVersion) &&
        Objects.equals(this.userId, microsoftGraphManagedAppRegistration.userId) &&
        Objects.equals(this.version, microsoftGraphManagedAppRegistration.version) &&
        Objects.equals(this.appliedPolicies, microsoftGraphManagedAppRegistration.appliedPolicies) &&
        Objects.equals(this.intendedPolicies, microsoftGraphManagedAppRegistration.intendedPolicies) &&
        Objects.equals(this.operations, microsoftGraphManagedAppRegistration.operations) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appIdentifier, applicationVersion, createdDateTime, deviceName, deviceTag, deviceType, flaggedReasons, lastSyncDateTime, managementSdkVersion, platformVersion, userId, version, appliedPolicies, intendedPolicies, operations, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphManagedAppRegistration {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    appIdentifier: ").append(toIndentedString(appIdentifier)).append("\n");
    sb.append("    applicationVersion: ").append(toIndentedString(applicationVersion)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    deviceTag: ").append(toIndentedString(deviceTag)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    flaggedReasons: ").append(toIndentedString(flaggedReasons)).append("\n");
    sb.append("    lastSyncDateTime: ").append(toIndentedString(lastSyncDateTime)).append("\n");
    sb.append("    managementSdkVersion: ").append(toIndentedString(managementSdkVersion)).append("\n");
    sb.append("    platformVersion: ").append(toIndentedString(platformVersion)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    appliedPolicies: ").append(toIndentedString(appliedPolicies)).append("\n");
    sb.append("    intendedPolicies: ").append(toIndentedString(intendedPolicies)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
