/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphChatMessageReactionIdentitySet;

import java.time.OffsetDateTime;
/**
 * MicrosoftGraphChatMessageReaction
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class MicrosoftGraphChatMessageReaction {
  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("reactionType")
  private String reactionType = null;

  @JsonProperty("user")
  private MicrosoftGraphChatMessageReactionIdentitySet user = null;

  public MicrosoftGraphChatMessageReaction createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public MicrosoftGraphChatMessageReaction reactionType(String reactionType) {
    this.reactionType = reactionType;
    return this;
  }

   /**
   * Supported values are like, angry, sad, laugh, heart, surprised.
   * @return reactionType
  **/
  public String getReactionType() {
    return reactionType;
  }

  public void setReactionType(String reactionType) {
    this.reactionType = reactionType;
  }

  public MicrosoftGraphChatMessageReaction user(MicrosoftGraphChatMessageReactionIdentitySet user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public MicrosoftGraphChatMessageReactionIdentitySet getUser() {
    return user;
  }

  public void setUser(MicrosoftGraphChatMessageReactionIdentitySet user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftGraphChatMessageReaction microsoftGraphChatMessageReaction = (MicrosoftGraphChatMessageReaction) o;
    return Objects.equals(this.createdDateTime, microsoftGraphChatMessageReaction.createdDateTime) &&
        Objects.equals(this.reactionType, microsoftGraphChatMessageReaction.reactionType) &&
        Objects.equals(this.user, microsoftGraphChatMessageReaction.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdDateTime, reactionType, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftGraphChatMessageReaction {\n");
    
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    reactionType: ").append(toIndentedString(reactionType)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
