/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphOnenotePatchContentCommand;

import java.util.ArrayList;
import java.util.List;
/**
 * OnenotePageidMicrosoftGraphOnenotePatchContentBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class OnenotePageidMicrosoftGraphOnenotePatchContentBody {
  @JsonProperty("commands")
  private List<MicrosoftGraphOnenotePatchContentCommand> commands = null;

  public OnenotePageidMicrosoftGraphOnenotePatchContentBody commands(List<MicrosoftGraphOnenotePatchContentCommand> commands) {
    this.commands = commands;
    return this;
  }

  public OnenotePageidMicrosoftGraphOnenotePatchContentBody addCommandsItem(MicrosoftGraphOnenotePatchContentCommand commandsItem) {
    if (this.commands == null) {
      this.commands = new ArrayList<>();
    }
    this.commands.add(commandsItem);
    return this;
  }

   /**
   * Get commands
   * @return commands
  **/
  public List<MicrosoftGraphOnenotePatchContentCommand> getCommands() {
    return commands;
  }

  public void setCommands(List<MicrosoftGraphOnenotePatchContentCommand> commands) {
    this.commands = commands;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnenotePageidMicrosoftGraphOnenotePatchContentBody onenotePageidMicrosoftGraphOnenotePatchContentBody = (OnenotePageidMicrosoftGraphOnenotePatchContentBody) o;
    return Objects.equals(this.commands, onenotePageidMicrosoftGraphOnenotePatchContentBody.commands);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commands);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnenotePageidMicrosoftGraphOnenotePatchContentBody {\n");
    
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
