/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RootMicrosoftGraphPreviewBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class RootMicrosoftGraphPreviewBody {
  @JsonProperty("page")
  private String page = null;

  @JsonProperty("zoom")
  private Double zoom = null;

  public RootMicrosoftGraphPreviewBody page(String page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  public String getPage() {
    return page;
  }

  public void setPage(String page) {
    this.page = page;
  }

  public RootMicrosoftGraphPreviewBody zoom(Double zoom) {
    this.zoom = zoom;
    return this;
  }

   /**
   * Get zoom
   * @return zoom
  **/
  public Double getZoom() {
    return zoom;
  }

  public void setZoom(Double zoom) {
    this.zoom = zoom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootMicrosoftGraphPreviewBody rootMicrosoftGraphPreviewBody = (RootMicrosoftGraphPreviewBody) o;
    return Objects.equals(this.page, rootMicrosoftGraphPreviewBody.page) &&
        Objects.equals(this.zoom, rootMicrosoftGraphPreviewBody.zoom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, zoom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootMicrosoftGraphPreviewBody {\n");
    
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    zoom: ").append(toIndentedString(zoom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
