/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphItemReference;

/**
 * RootMicrosoftGraphCopyBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class RootMicrosoftGraphCopyBody {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("parentReference")
  private MicrosoftGraphItemReference parentReference = null;

  public RootMicrosoftGraphCopyBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RootMicrosoftGraphCopyBody parentReference(MicrosoftGraphItemReference parentReference) {
    this.parentReference = parentReference;
    return this;
  }

   /**
   * Get parentReference
   * @return parentReference
  **/
  public MicrosoftGraphItemReference getParentReference() {
    return parentReference;
  }

  public void setParentReference(MicrosoftGraphItemReference parentReference) {
    this.parentReference = parentReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootMicrosoftGraphCopyBody rootMicrosoftGraphCopyBody = (RootMicrosoftGraphCopyBody) o;
    return Objects.equals(this.name, rootMicrosoftGraphCopyBody.name) &&
        Objects.equals(this.parentReference, rootMicrosoftGraphCopyBody.parentReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, parentReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootMicrosoftGraphCopyBody {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentReference: ").append(toIndentedString(parentReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
