/*
 * Partial Graph API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.graph;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsoft.graph.MicrosoftGraphSite;

import java.util.ArrayList;
import java.util.List;
/**
 * SitesMicrosoftGraphAddBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T14:23:42.636858240+01:00[Europe/Zurich]")
public class SitesMicrosoftGraphAddBody {
  @JsonProperty("value")
  private List<MicrosoftGraphSite> value = null;

  public SitesMicrosoftGraphAddBody value(List<MicrosoftGraphSite> value) {
    this.value = value;
    return this;
  }

  public SitesMicrosoftGraphAddBody addValueItem(MicrosoftGraphSite valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public List<MicrosoftGraphSite> getValue() {
    return value;
  }

  public void setValue(List<MicrosoftGraphSite> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SitesMicrosoftGraphAddBody sitesMicrosoftGraphAddBody = (SitesMicrosoftGraphAddBody) o;
    return Objects.equals(this.value, sitesMicrosoftGraphAddBody.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SitesMicrosoftGraphAddBody {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
