# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  
  microsoftConnector:
    
    # Your Azure Application (client) ID
    appId: ""
    
    # Secret key from your applications "certificates & secrets"
    # [password]
    secretKey: ""
  
  teamsNotification:
    # technical user that sends ivy-notifications
    username: ""
    # secret of the technical user
    # [password]
    userpass: ""
